export type DashboardLanguage = "ar" | "en";

export const DASHBOARD_LANGUAGE_KEY = "malikat.dashboard.language.v1";

export const dashboardEnglish: Record<string, string> = {
  "لوحة التحكم": "Dashboard",
  "فتح لوحة التحكم": "Open dashboard",
  "فتح لوحة الموارد البشرية": "Open HR dashboard",
  "التنقل بين الأنظمة الداخلية": "Internal navigation",
  "نظرة عامة": "Overview",
  "ملخص لوحة التشغيل": "Operations summary",
  "الحجوزات والعملاء والمالية": "Bookings, clients and finance",
  "الموظفات والموارد البشرية": "Staff and human resources",
  "الإدارة والتقارير": "Management and reports",
  "الموظفات والحسابات والإعدادات": "Staff, accounts and settings",
  "الحجوزات": "Bookings",
  "الحجز الإداري": "Internal booking",
  "إنشاء حجز من داخل الإدارة": "Create a booking from the dashboard",
  "إغلاق اليوم والشفت": "Day and shift closing",
  "إغلاق اليوم / الشفت": "Day / shift closing",
  "مراجعة العمليات وإقفال اليوم": "Review transactions and close the day",
  "شاشة الحجوزات TV": "Booking screen (TV)",
  "شاشة الحجوزات (TV)": "Booking screen (TV)",
  "شاشة نداء الحجوزات": "Booking queue screen",
  "عرض نداء ومتابعة الحجوزات": "Display and track booking calls",
  "العملاء": "Clients",
  "ملفات العملاء والباقات": "Client profiles and packages",
  "الإيرادات": "Income",
  "المصروفات": "Expenses",
  "ملخص الموارد البشرية": "HR overview",
  "نظرة عامة على شؤون الموظفات": "Staff affairs overview",
  "الموارد البشرية": "Human resources",
  "إدارة الموظفات": "Staff management",
  "الملفات والبيانات الوظيفية": "Profiles and employment records",
  "طلبات الموظفات": "Staff requests",
  "متابعة الطلبات والقرارات": "Track requests and decisions",
  "الاستئذانات والإجازات": "Permissions and leave",
  "مراجعة الاستئذانات والإجازات": "Review permissions and leave",
  "الحضور والبصمة": "Attendance and clocking",
  "سجل البصمة والأجهزة": "Attendance and devices",
  "متابعة البصمات والأجهزة والتنبيهات": "Track clock-ins, devices and alerts",
  "طلبات التوظيف": "Job applications",
  "مراجعة طلبات التوظيف": "Review job applications",
  "الرسائل الداخلية": "Internal messages",
  "التواصل الداخلي مع الموظفات": "Staff communications",
  "ملفات الموظفات": "Staff files",
  "العقود والمستندات والمرفقات": "Contracts, documents and attachments",
  "إنشاء حساب موظفة": "Create staff account",
  "إضافة حساب موظفة جديد": "Add a new staff account",
  "إدارة الرواتب": "Payroll",
  "مسيرات الرواتب الشهرية والاعتماد والدفع": "Monthly payroll, approval and payment",
  "تارقت الموظفات": "Staff targets",
  "متابعة المبيعات المؤهلة والشرائح وبونص الرواتب": "Track eligible sales, tiers and bonuses",
  "أداء الموظفات": "Staff performance",
  "تحليل أداء ومبيعات الموظفات": "Analyze staff performance and sales",
  "الشريكات والمساحات": "Partners and spaces",
  "الشركاء": "Partners",
  "إدارة المستأجرات ومقاعد العمل": "Manage tenants and workstations",
  "العروض والكوبونات": "Offers and coupons",
  "المخزون": "Inventory",
  "التقارير": "Reports",
  "سجل الحركات": "Activity log",
  "الولاء VIP": "VIP loyalty",
  "الولاء (VIP)": "VIP loyalty",
  "الملف الشخصي": "Profile",
  "الإعدادات الأساسية": "General settings",
  "إعدادات الحجوزات": "Booking settings",
  "إدارة الكتالوج": "Catalog management",
  "إدارة الحسابات": "Account management",
  "محتوى الموقع": "Website content",
  "إعدادات البصمة والنطاقات": "Attendance and location settings",
  "بوابة الموظفات": "Staff portal",
  "نظام التصميم V2": "Design system V2",
  "المزيد": "More",
  "القائمة الإدارية": "Management menu",
  "نفس أقسام السايدبار، مرتبة حسب الصلاحيات المتاحة لحسابك.": "Dashboard sections available to your account.",
  "المزيد من أقسام لوحة التحكم": "More dashboard sections",
  "تنقل لوحة التحكم": "Dashboard navigation",
  "التنقل داخل لوحة التحكم": "Dashboard navigation",
  "فتح القائمة": "Open menu",
  "القائمة": "Menu",
  "إغلاق": "Close",
  "خروج": "Log out",
  "تسجيل الخروج": "Log out",
  "البروفايل": "Profile",
  "فتح الملف الشخصي": "Open profile",
  "جاري تحميل بيانات القسم...": "Loading section data...",
  "جاري تحميل تنقل لوحة التحكم": "Loading dashboard navigation",
  "مستخدم": "User",
  "لوحة التشغيل اليومية": "Daily operations",
  "مرحبًا بك،": "Welcome,",
  "متابعة موحدة للحجوزات والإيرادات والتشغيل اليومي من مصدر واحد واضح.": "Bookings, revenue and daily operations in one place.",
  "البيانات متصلة": "Data connected",
  "تتحدث مع نشاط لوحة التحكم": "Updates with dashboard activity",
  "أداء الصالون اليوم": "Today's salon performance",
  "المؤشرات التشغيلية الأساسية بدون خلطها مع إجماليات الفترات المالية.": "Key daily metrics, separate from financial period totals.",
  "حجوزات اليوم": "Today's bookings",
  "فتح قائمة الحجوزات": "View bookings",
  "إيرادات اليوم": "Today's revenue",
  "غير متاح": "Unavailable",
  "فتح التقارير": "View reports",
  "تتطلب صلاحية الإيرادات": "Income access required",
  "الحجوزات المكتملة": "Completed bookings",
  "المكتملة في تاريخ اليوم": "Completed today",
  "موظفات مرتبطات بحجوزات": "Staff with bookings",
  "عدد فريد حسب حجوزات اليوم": "Unique staff booked today",
  "الملخص المالي المسجل": "Recorded financial summary",
  "إجمالي الدخل والمصروفات وصافي الربح للفترة التي يعتمدها النظام.": "Total income, expenses and net profit for the system's reporting period.",
  "إجمالي الدخل": "Total income",
  "إجمالي المصروفات": "Total expenses",
  "صافي الربح": "Net profit",
  "التشغيل اليومي": "Daily operations",
  "الجدول الزمني للحجوزات مع ملخص اليوم وآخر العمليات المالية.": "Booking schedule, daily summary and recent financial activity.",
  "جدول الحجوزات حسب الساعة": "Bookings by hour",
  "تاريخ الجدول": "Schedule date",
  "اليوم المختار مغلق حسب إعدادات ساعات العمل": "The selected day is closed according to business hours",
  "ساعات العمل": "Business hours",
  "اختاري التاريخ ثم اضغطي على الحجز لعرض تفاصيله": "Choose a date, then select a booking to view its details",
  "لا توجد حجوزات في التاريخ المحدد": "No bookings on this date",
  "اختاري تاريخًا آخر أو أضيفي حجزًا جديدًا من الإجراءات السريعة.": "Choose another date or create a booking from quick actions.",
  "إضافة حجز": "Add booking",
  "الساعة": "Hour",
  "الحجوزات داخل الساعة": "Bookings during this hour",
  "مؤكد": "Confirmed",
  "في الانتظار": "Pending",
  "ملغي": "Cancelled",
  "مكتمل": "Completed",
  "ملخص اليوم": "Today's summary",
  "الحركة المسجلة في تاريخ اليوم.": "Activity recorded today.",
  "دخل اليوم": "Today's income",
  "مصروف اليوم": "Today's expenses",
  "الصافي": "Net",
  "آخر العمليات": "Recent transactions",
  "أحدث الحركات المالية المسجلة.": "Latest recorded financial transactions.",
  "لا تملك صلاحية عرض العمليات المالية": "You do not have access to financial transactions",
  "لا توجد عمليات حديثة": "No recent transactions",
  "إجراءات سريعة": "Quick actions",
  "انتقال مباشر إلى المهام الأكثر استخدامًا داخل لوحة الإدارة.": "Go directly to common management tasks.",
  "حجز جديد": "New booking",
  "إنشاء حجز للعميلة وإسناده إلى الموظفة والخدمة المناسبة.": "Create a client booking and assign its staff member and service.",
  "إدارة الحجوزات": "Manage bookings",
  "مراجعة الحالات والمواعيد والتعديلات ضمن مساحة الحجوزات.": "Review booking statuses, times and changes.",
  "فتح الحجوزات": "Open bookings",
  "فتح تقارير الأداء والإيرادات والمصروفات للفترة المطلوبة.": "View performance, income and expense reports for the selected period.",
};

export function dashboardText(language: DashboardLanguage, arabic: string): string {
  return language === "en" ? dashboardEnglish[arabic] || arabic : arabic;
}
