import { dashboardText, type DashboardLanguage } from "./dashboardLanguage";

export type { DashboardLanguage } from "./dashboardLanguage";

const bookingEnglish: Record<string, string> = {
  "جاري تحميل الحجوزات...": "Loading bookings...",
  "يتم تجهيز قائمة الحجوزات والحالات المالية.": "Preparing bookings and payment information.",
  "تشغيل الحجوزات": "Booking operations",
  "مركز إدارة الحجوزات": "Booking management",
  "واجهة تشغيل موحدة لمتابعة الحجوزات الجديدة، المواعيد، التحصيل، والإجراءات اليومية.": "Manage new bookings, appointments, payments and daily tasks in one place.",
  "إنشاء حجز جديد": "Create booking",
  "تحديث": "Refresh",
  "ملخص عمليات الحجوزات": "Booking operations summary",
  "المؤكد والمكتمل اليوم": "Confirmed and completed today",
  "المحصّل اليوم": "Collected today",
  "حسب الحجوزات المحمّلة": "Based on loaded bookings",
  "تحتاج متابعة": "Needs attention",
  "حجوزات قديمة أو غير مغلقة": "Old or open bookings",
  "إجمالي المتبقي": "Total outstanding",
  "على الحجوزات المفتوحة فقط": "Open bookings only",
  "الوارد الجديد": "New arrivals",
  "الحجوزات الجديدة": "New bookings",
  "حجوزات اليوم والمواعيد القادمة، مرتبة حسب أقرب موعد.": "Today's and upcoming bookings, sorted by appointment time.",
  "عميلة غير معروفة": "Unknown client",
  "بدون موظفة": "No staff member",
  "لا توجد حجوزات قادمة": "No upcoming bookings",
  "ستظهر هنا حجوزات اليوم والمواعيد المستقبلية مباشرة.": "Today's and upcoming bookings will appear here.",
  "عرض الأحدث في القائمة": "Show newest in list",
  "تحديد الكل كمُطّلع عليه": "Mark all as seen",
  "مركز المتابعة": "Attention center",
  "حجوزات تحتاج إجراء": "Bookings needing action",
  "الحجوزات المتأخرة أو التي بقيت بحالة مفتوحة.": "Past bookings that are still open.",
  "قديم بالانتظار": "Old pending",
  "قديم ومؤكد": "Old confirmed",
  "عربون غير مغلق": "Open deposit",
  "بدون دفع": "Unpaid",
  "لا توجد حجوزات متأخرة": "No overdue bookings",
  "البحث والفلاتر": "Search and filters",
  "مساحة العمل": "Workspace",
  "البحث وإدارة القائمة": "Search and manage bookings",
  "نتيجة مطابقة": "Matching results",
  "بحث الحجوزات": "Search bookings",
  "ابحثي بالاسم، الجوال، رقم الحجز، الخدمة أو الموظفة...": "Search by name, phone, booking number, service or staff...",
  "مسح البحث": "Clear search",
  "الفترة": "Period",
  "كل الحجوزات": "All bookings",
  "اليوم": "Today",
  "أمس": "Yesterday",
  "هذا الأسبوع": "This week",
  "هذا الشهر": "This month",
  "الشهر الماضي": "Last month",
  "نطاق مخصص": "Custom range",
  "اختاري الفترة": "Choose period",
  "فلاتر متقدمة": "Advanced filters",
  "مسح الفلاتر": "Clear filters",
  "فلترة حالة الحجز": "Filter booking status",
  "الكل": "All",
  "بالانتظار": "Pending",
  "من تاريخ": "From date",
  "إلى تاريخ": "To date",
  "اختاري التاريخ": "Choose date",
  "مسح": "Clear",
  "مسح التاريخ": "Clear date",
  "اختيار": "Choose",
  "الشهر السابق": "Previous month",
  "الشهر التالي": "Next month",
  "استثناء حالة": "Exclude status",
  "بدون استثناء": "No exclusion",
  "استثناء: ": "Exclude: ",
  "حالة السداد": "Payment status",
  "مدفوع بالكامل": "Paid in full",
  "مدفوع جزئيًا": "Partially paid",
  "غير مدفوع": "Unpaid",
  "كل حالات السداد": "All payment statuses",
  "طريقة الدفع": "Payment method",
  "كل الطرق": "All methods",
  "كل طرق الدفع": "All payment methods",
  "كاش": "Cash",
  "شبكة": "Card",
  "تحويل": "Transfer",
  "مختلط": "Mixed",
  "دفع مختلط": "Mixed payment",
  "أخرى": "Other",
  "الموظفة": "Staff member",
  "كل الموظفات": "All staff",
  "الخدمة": "Service",
  "كل الخدمات": "All services",
  "مصدر الحجز": "Booking source",
  "كل المصادر": "All sources",
  "موقع العميلات": "Client website",
  "الداشبورد": "Dashboard",
  "الحجز الداخلي": "Internal booking",
  "غير محدد": "Unspecified",
  "الترتيب": "Sort order",
  "الأحدث أولًا": "Newest first",
  "الأقدم أولًا": "Oldest first",
  "اختاري الترتيب": "Choose sort order",
  "الحجوزات القديمة": "Older bookings",
  "بدون فلتر": "No filter",
  "الأقدم من اليوم": "Before today",
  "الأقدم من 7 أيام": "Older than 7 days",
  "الأقدم من 30 يومًا": "Older than 30 days",
  "قديم من": "Older from",
  "قديم إلى": "Older until",
  "المحمّل": "Loaded",
  "المطابق": "Matching",
  "المعروض": "Shown",
  "الصفحة": "Page",
  "المتبقي ضمن النتائج": "Outstanding in results",
  "حجز محدد": "Bookings selected",
  "ضمن النتائج الحالية": "In current results",
  "إلغاء تحديد الصفحة": "Deselect page",
  "تحديد الصفحة": "Select page",
  "تحديد كل النتائج": "Select all results",
  "إلغاء التحديد": "Clear selection",
  "الحجوزات العادية": "Regular bookings",
  "الحجوزات الداخلية": "Internal bookings",
  "تظهر هنا الحجوزات العادية فقط، ويظهر الحجز الداخلي المستقبلي قبل الدفع مؤقتًا في هذا القسم.": "Regular bookings appear here. Future internal bookings appear here temporarily until payment.",
  "تظهر هنا جميع الحجوزات الداخلية بشكل مستقل، ولا يبقى أي حجز داخلي داخل القسم العادي بعد الدفع أو التأكيد.": "Internal bookings appear separately after payment or confirmation.",
  "حجز": "booking",
  "حجوزات داخلية": "internal bookings",
  "حجوزات عادية": "regular bookings",
  "منها": "Including",
  "حجز داخلي مستقبلي قبل الدفع": "future internal booking before payment",
  "تحديد حجوزات قسم": "Select bookings in section",
  "تحديد الحجز": "Select booking",
  "الحجز": "Booking",
  "العميلة": "Client",
  "الخدمة والموظفة": "Service and staff",
  "الموعد": "Appointment",
  "التحصيل": "Payment",
  "الإجراءات": "Actions",
  "حجز مجمّع": "Grouped booking",
  "المرجع": "Reference",
  "خدمات": "services",
  "فتح تفاصيل الحجز": "Open booking details",
  "جديد": "New",
  "آخر تحديث": "Last updated",
  "غير محددة": "Unassigned",
  "الإجمالي": "Total",
  "مدفوع": "Paid",
  "متبقي": "Remaining",
  "بدون سعر": "No price",
  "بانتظار السداد": "Awaiting payment",
  "لا يوجد سعر محدد": "No price specified",
  "لا يوجد مبلغ محدد": "No amount specified",
  "غير مدفوع (بانتظار السداد)": "Unpaid (awaiting payment)",
  "عربون (دفع جزئي)": "Deposit (partial payment)",
  "حجز داخلي": "Internal booking",
  "دفع جزئي": "Partially paid",
  "فتح": "Open",
  "تجهيز...": "Preparing...",
  "طباعة": "Print",
  "طباعة الفاتورة": "Print invoice",
  "تعديل": "Edit",
  "الاسترجاع": "Refund",
  "استرجاع": "Refund",
  "الاسترجاع مسجل": "Refund recorded",
  "تغيير حالة الحجز": "Change booking status",
  "إزالة الحجز من القائمة مع حفظ السجلات المالية": "Remove booking while keeping financial records",
  "حذف": "Delete",
  "حذف الحجز": "Delete booking",
  "تأكيد": "Confirm",
  "إلغاء": "Cancel",
  "تحديد هذا الحجز": "Select this booking",
  "رقم الحجز": "Booking number",
  "الجوال": "Phone",
  "التاريخ": "Date",
  "الحالة": "Status",
  "نوع الحجز": "Booking type",
  "الدفع": "Payment",
  "تفاصيل": "Details",
  "جاري تجهيز الفاتورة...": "Preparing invoice...",
  "لا توجد نتائج مطابقة": "No matching results",
  "لا توجد": "No",
  "حالياً": "at the moment",
  "غيّر البحث أو الفلاتر الحالية لعرض حجوزات هذا القسم.": "Change the search or filters to see bookings in this section.",
  "عند إضافة حجوزات لهذا القسم ستظهر هنا مباشرة.": "Bookings added to this section will appear here.",
  "إعادة ضبط الفلاتر": "Reset filters",
  "التنقل بين صفحات الحجوزات": "Booking pages",
  "عرض": "Showing",
  "من": "of",
  "لكل صفحة": "Per page",
  "عدد الحجوزات في الصفحة": "Bookings per page",
  "الأولى": "First",
  "السابق": "Previous",
  "التالي": "Next",
  "الأخيرة": "Last",
  "تفاصيل الحجز": "Booking details",
  "بيانات الحجز": "Booking information",
  "نفس البيانات الحالية مع ترتيب أوضح ومسافات أنظف بين البطاقات.": "Current booking information, organized for easier reading.",
  "تم إنشاء الحجز": "Booking created",
  "اسم الزبون": "Client name",
  "رقم الهاتف": "Phone number",
  "نقاط العميلة": "Client points",
  "نقطة": "points",
  "ولاء العميلة": "Client loyalty",
  "المصدر": "Source",
  "الوقت": "Time",
  "مدة الخدمة": "Service duration",
  "دقيقة": "minutes",
  "السعر الإجمالي": "Total price",
  "نوع الدفع": "Payment type",
  "سجل الحجز": "Booking history",
  "تسلسل الأحداث للحجز من الأحدث إلى الأقدم.": "Booking events, newest first.",
  "جاري تحميل سجل الحجز...": "Loading booking history...",
  "بواسطة": "By",
  "تفاصيل العملية": "Action details",
  "لا توجد أحداث مسجلة لهذا الحجز حتى الآن.": "No events recorded for this booking yet.",
  "الخدمات داخل الحجز": "Services in booking",
  "المدة": "Duration",
  "السعر": "Price",
  "ملاحظات سابقة على العميلة": "Previous client notes",
  "لا توجد ملاحظات سابقة لهذه العميلة.": "No previous notes for this client.",
  "ملاحظات الإدارة (خاصة)": "Private management notes",
  "أضف ملاحظات هنا...": "Add notes here...",
  "حفظ الملاحظة": "Save note",
  "تم الحفظ": "Saved",
  "إدارة الاسترجاع": "Manage refund",
  "تسجيل استرجاع": "Record refund",
  "تعديل الحجز": "Edit booking",
  "تأكيد الإجراء الجماعي للحجوزات": "Confirm bulk booking update",
  "تأكيد الإجراء الجماعي": "Confirm bulk action",
  "عدد الحجوزات التي ستتغير": "Bookings to update",
  "الحالة الحالية": "Current status",
  "الحالة الجديدة": "New status",
  "التاريخ/الفلاتر المستخدمة": "Date / active filters",
  "بدون فلاتر": "No filters",
  "تأكيد التحديث الجماعي": "Confirm bulk update",
  "جاري التحديث...": "Updating...",
  "قيمة الحجز": "Booking value",
  "حالة الاسترجاع: تم الاسترجاع": "Refund status: refunded",
  "حالة الاسترجاع: غير مسترجع": "Refund status: no refund",
  "المبلغ": "Amount",
  "الطريقة": "Method",
  "لا يوجد استرجاع مسجل لهذا الحجز حالياً.": "There is no refund recorded for this booking.",
  "مبلغ الاسترجاع": "Refund amount",
  "طريقة الاسترجاع": "Refund method",
  "تاريخ الاسترجاع": "Refund date",
  "سبب الاسترجاع": "Refund reason",
  "تفاصيل إضافية": "Additional details",
  "مثال: إلغاء قبل الموعد": "Example: cancelled before appointment",
  "أي تفاصيل داخلية للاسترجاع": "Any internal refund details",
  "يمكن التراجع عن الاسترجاع من هنا": "You can reverse the refund here",
  "إلغاء الاسترجاع": "Reverse refund",
  "جاري الإلغاء...": "Cancelling...",
  "حفظ الاسترجاع": "Save refund",
  "جاري الحفظ...": "Saving...",
  "تأكيد الحجز مع الدفع": "Confirm booking and payment",
  "تأكيد الحجز": "Confirm booking",
  "إجمالي الحجز": "Booking total",
  "نوع الدفع وقت التأكيد": "Payment type on confirmation",
  "دفع كامل": "Paid in full",
  "عربون": "Deposit",
  "اختاري نوع الدفع": "Choose payment type",
  "اختاري طريقة الدفع": "Choose payment method",
  "مبلغ الكاش": "Cash amount",
  "مبلغ الشبكة": "Card amount",
  "المجموع": "Total",
  "مبلغ العربون": "Deposit amount",
  "مثال: 150": "Example: 150",
  "جاري التأكيد...": "Confirming...",
  "رجوع": "Back",
  "تأكيد إلغاء الحجز": "Confirm booking cancellation",
  "هل تريد بالفعل إلغاء هذا الحجز؟": "Are you sure you want to cancel this booking?",
  "تأكيد الإلغاء": "Confirm cancellation",
  "تعذر تسجيل الاسترجاع.": "Could not record the refund.",
  "تعذر إلغاء الاسترجاع.": "Could not reverse the refund.",
  "أدخل مبلغ استرجاع صحيح.": "Enter a valid refund amount.",
  "مبلغ الاسترجاع لا يمكن أن يتجاوز قيمة الحجز.": "Refund amount cannot exceed booking value.",
  "سبب الاسترجاع مطلوب.": "Refund reason is required.",
  "أدخلي كلمة مرور الحساب": "Enter your account password",
  "إجراء حساس": "Sensitive action",
  "الإجراء المطلوب": "Requested action",
  "التحقق بكلمة مرور الحساب": "Verify account password",
  "تأكيد كلمة مرور الحساب": "Confirm account password",
  "جاري التحقق...": "Verifying...",
  "سيتم التحقق من كلمة مرور الحساب المسجل حاليًا قبل تنفيذ الإجراء.": "Your current account password will be verified before this action.",
  "سيختفي الحجز من صفحة الحجوزات، مع الاحتفاظ بالفاتورة والمدفوعات والسجل المالي للمراجعة.": "The booking will be removed from the bookings page. Its invoice, payments and financial history will remain available for review.",
  "كلمة مرور حسابك الحالي": "Your current account password",
  "متابعة": "Continue",
  "أدخلي كلمة مرور الحساب الحالي.": "Enter your current account password.",
  "كلمة المرور غير صحيحة.": "Incorrect password.",
  "تم إيقاف المحاولات مؤقتًا بسبب كثرة المحاولات. انتظري قليلًا ثم أعيدي المحاولة.": "Too many attempts. Wait a moment and try again.",
  "انتهت صلاحية التحقق. سجّلي الخروج ثم ادخلي مرة أخرى.": "Verification expired. Sign out and sign in again.",
  "تعذر التحقق من كلمة المرور.": "Could not verify the password.",
  "المتبقي": "Remaining",
  "المدفوع": "Paid",
  "تنبيه: هذا الإجراء سيؤثر في عدة حجوزات محددة فقط. لن يتم تعديل أي حجز غير محدد.": "This action only updates the selected bookings. Other bookings will not change.",
  "خدمة": "Service",
  "لا يوجد دفع": "No payment",
  "مثال: 120": "Example: 120",
  "بحث": "Search",
  "كل الحالات": "All statuses",
  "حجوزات قديمة ما زالت بالانتظار": "Older bookings still pending",
  "مدفوع جزئيا": "Partially paid",
  "بدون اسم": "Unnamed",
  "اختيار العميلة": "Select client",
  "اختيار الخدمات": "Select services",
  "الموظفة والموعد": "Staff and appointment",
  "تحديد الوقت": "Select time",
  "المراجعة والدفع": "Review and payment",
  "وضع الحجز": "Booking mode",
  "خطوات الحجز": "Booking steps",
  "ابحثي بالاسم أو رقم الجوال أو رقم العضوية (MK)": "Search by name, phone or membership number (MK)",
  "جاري البحث في بيانات السيرفر...": "Searching server data...",
  "نتائج البحث": "Search results",
  "العميلات الأخيرات": "Recent clients",
  "إضافة عميلة جديدة": "Add new client",
  "سنفحص رقم الجوال أولًا حتى لا يتم إنشاء سجل مكرر.": "We will check the phone number first to avoid creating a duplicate client.",
  "مثال: رانيا الحربي": "Example: Rania Alharbi",
  "البريد الإلكتروني (اختياري)": "Email (optional)",
  "تم اختيار العميلة الموجودة. لم يتم إنشاء سجل جديد.": "Existing client selected. No new record was created.",
  "اختيار العميلة الموجودة": "Select existing client",
  "إعادة التحقق والحفظ": "Verify again and save",
  "حفظ واختيار العميلة": "Save and select client",
  "تعذر التحقق من رقم الجوال. لن يتم إنشاء سجل جديد قبل نجاح التحقق.": "Could not verify the phone number. No new client will be created until verification succeeds.",
  "اكتبي اسم العميلة كاملًا.": "Enter the client's full name.",
  "أدخلي رقم جوال سعودي صحيح من 10 أرقام.": "Enter a valid 10-digit Saudi mobile number.",
  "تم العثور على عميلة مسجلة بهذا الرقم. اختاري السجل الموجود للمتابعة.": "A registered client was found with this number. Select the existing record to continue.",
  "تم اختيار العميلة للحجز بنجاح.": "Client selected for booking successfully.",
  "غير متصل بالإنترنت. لم يتم إنشاء العميلة. أعيدي الاتصال ثم حاولي مرة أخرى.": "Offline. The client was not created. Reconnect and try again.",
  "انقطع الاتصال أثناء حفظ العميلة. النتيجة غير مؤكدة؛ أعيدي الاتصال وابحثي برقم الجوال قبل إعادة المحاولة.": "Connection was lost while saving the client. The result is uncertain; reconnect and search by phone number before trying again.",
  "تعذر التحقق من رقم الجوال أو حفظ العميلة. حاولي مرة أخرى.": "Could not verify the phone number or save the client. Try again.",
  "لم يتم العثور على عميلة مطابقة.": "No matching client found.",
  "تعذر جلب بيانات العميلات من السيرفر.": "Could not load client data from the server.",
  "ابحثي عن خدمة...": "Search for a service...",
  "قسم": "Section",
  "تصنيف": "Category",
  "جاري تحميل الخدمات...": "Loading services...",
  "لا توجد خدمات مطابقة في هذا القسم.": "No matching services in this section.",
  "المدة حسب الخدمة": "Duration depends on service",
  "تعذر تحميل إعدادات الحجز من Core D1. أعيدي المحاولة قبل حفظ الحجز.": "Could not load booking settings from Core D1. Try again before saving.",
  "لا توجد عروض نشطة حالياً.": "No active offers at the moment.",
  "تعذر جلب العروض النشطة.": "Could not load active offers.",
  "لا توجد أقسام خدمات نشطة.": "No active service sections.",
  "تعذر جلب قائمة الخدمات من السيرفر.": "Could not load the service list from the server.",
  "تعذر جلب خدمات هذا القسم.": "Could not load services for this section.",
  "خصم مبلغ ثابت": "Fixed amount discount",
  "خصم نسبة": "Percentage discount",
  "تعذر جلب توفر الموظفات من Core HR. أعيدي المحاولة.": "Could not load staff availability from Core HR. Try again.",
  "تعذر جلب الأوقات المتاحة. حاولي مرة أخرى.": "Could not load available times. Try again.",
  "تاريخ الحجز": "Booking date",
  "أنت تقوم بإنشاء حجز بتاريخ سابق": "You are creating a booking with a past date",
  "الصالون مغلق في هذا اليوم حسب إعدادات الدوام.": "The salon is closed on this day according to working-hour settings.",
  "جاري تحميل الموظفات...": "Loading staff...",
  "مكتمل": "Complete",
  "اختاري الموظفة": "Select staff member",
  "الأوقات المتاحة": "Available times",
  "العميلة لديها خدمة من": "The client has a service from",
  "بسبب": "Because of",
  "اختاري الموظفة أولًا.": "Select a staff member first.",
  "جاري فحص المواعيد...": "Checking appointments...",
  "لا توجد أوقات متاحة لهذه الموظفة في التاريخ المختار.": "No available times for this staff member on the selected date.",
  "هذا الموعد يتعارض مع خدمة أخرى في نفس حجز العميلة. اختاري وقتًا مختلفًا.": "This appointment conflicts with another service in the same client booking. Choose a different time.",
  "لا توجد موظفة مؤهلة ومتاحة لهذه الخدمة في هذا اليوم.": "No eligible staff member is available for this service on this day.",
  "أدخلي كود الكوبون أولاً.": "Enter the coupon code first.",
  "الكوبون غير صحيح أو منتهي أو غير نشط.": "The coupon is invalid, expired or inactive.",
  "الكوبون لا ينطبق على الخدمات المختارة.": "The coupon does not apply to the selected services.",
  "تعذر التحقق من الكوبون الآن.": "Could not verify the coupon right now.",
  "اختاري العميلة أولًا.": "Select a client first.",
  "إعدادات الحجز لم تُحمّل من Core D1 بعد. أعيدي فتح الصفحة أو حاولي مرة أخرى.": "Booking settings have not loaded from Core D1 yet. Reopen the page or try again.",
  "أضيفي خدمة واحدة على الأقل.": "Add at least one service.",
  "أكملي الموظفة والوقت لجميع الخدمات بدون تعارض.": "Complete staff and time selection for all services without conflicts.",
  "الخصم المحدد غير صالح.": "The selected discount is invalid.",
  "تحققي من الكوبون قبل حفظ الحجز.": "Verify the coupon before saving the booking.",
  "قيمة العربون يجب أن تكون أكبر من صفر وأقل من إجمالي الحجز.": "Deposit amount must be greater than zero and less than the booking total.",
  "تم تحديث المواعيد؛ الوقت المختار أصبح محجوزًا أو يتداخل مع حجز آخر. اختاري وقتًا جديدًا.": "Appointments were refreshed; the selected time is now booked or overlaps another booking. Choose a new time.",
  "الموعد المختار لم يعد متاحًا. تمت إعادتك إلى خطوة الموعد بعد تحديث الأوقات.": "The selected appointment is no longer available. You were returned to the appointment step after refreshing times.",
  "تعذر ربط الحجز بحساب العميلة المحدد.": "Could not link the booking to the selected client account.",
  "عدة موظفات": "Multiple staff members",
  "الموعد محجوز": "Appointment already booked",
  "سبق حجز هذا الوقت قبل إتمام العملية. أعيدي اختيار المواعيد من القائمة المحدثة.": "This time was booked before the operation completed. Select appointments again from the refreshed list.",
  "الموعد محجوز بالفعل. تمت إعادتك إلى خطوة الموعد ولم يتم إنشاء حجز مكرر.": "The appointment is already booked. You were returned to the appointment step and no duplicate booking was created.",
  "غير متصل بالإنترنت. لم يتم إنشاء الحجز. أعيدي الاتصال ثم حاولي مرة أخرى.": "Offline. The booking was not created. Reconnect and try again.",
  "انقطع الاتصال أثناء حفظ الحجز. نتيجة العملية غير مؤكدة؛ لا تعيدي الحفظ. أعيدي الاتصال وافتحي صفحة الحجوزات للتحقق أولًا.": "Connection was lost while saving the booking. The result is uncertain; do not save again. Reconnect and check the bookings page first.",
  "لا توجد بيانات فاتورة جاهزة للطباعة.": "No invoice data is ready to print.",
  "تم منع فتح نافذة الفاتورة. فعّلي النوافذ المنبثقة للموقع ثم حاولي مرة أخرى.": "The invoice window was blocked. Enable pop-ups for this site and try again.",
  "تم حفظ الحجز بنجاح": "Booking saved successfully",
  "تم ربط": "Linked",
  "بالعميلة والموظفات المختارات.": "to the selected client and staff.",
  "إضافة خصم أو كوبون": "Add discount or coupon",
  "إخفاء خيارات الخصم": "Hide discount options",
  "+ إضافة خصم أو كوبون": "+ Add discount or coupon",
  "بدون خصم": "No discount",
  "مبلغ ثابت": "Fixed amount",
  "نسبة": "Percentage",
  "عرض محفوظ": "Saved offer",
  "كوبون": "Coupon",
  "قيمة الخصم": "Discount value",
  "النسبة": "Percentage",
  "حد أقصى اختياري": "Optional maximum",
  "بدون حد": "No limit",
  "جاري تحميل العروض...": "Loading offers...",
  "خصم متوقع": "Expected discount",
  "خدمات محددة": "Selected services",
  "تصنيفات محددة": "Selected categories",
  "كود الكوبون": "Coupon code",
  "تحقق": "Verify",
  "الإجمالي المؤهل": "Eligible subtotal",
  "الخصم": "Discount",
  "نوع التحصيل": "Collection type",
  "بدون دفع الآن": "No payment now",
  "قيمة العربون": "Deposit amount",
  "ملاحظة الحجز (اختياري)": "Booking note (optional)",
  "أي تفاصيل مهمة للموظفة أو الاستقبال...": "Any important details for staff or reception...",
  "الإجمالي قبل الخصم": "Subtotal before discount",
  "الإجمالي بعد الخصم": "Total after discount",
  "المدفوع الآن": "Paid now",
  "العودة للموعد": "Back to appointment",
  "جاري حفظ الحجز...": "Saving booking...",
  "حفظ كحجز غير مدفوع": "Save as unpaid booking",
  "ملخص الحجز": "Booking summary",
  "لم يتم اختيار عميلة بعد": "No client selected yet",
  "اختاري عميلة للمتابعة": "Select a client to continue",
  "حجز داخل الصالون": "In-salon booking",
  "لم تتم إضافة خدمات بعد": "No services added yet",
  "الإجمالي الفرعي": "Subtotal",
  "المتابعة للخدمات": "Continue to services",
  "المتابعة للموظفة والموعد": "Continue to staff and appointment",
  "المتابعة للمراجعة والدفع": "Continue to review and payment",
  "راجعي وأكدي الحجز أعلاه": "Review and confirm the booking above",
  "هذه نسخة V2 تجريبية منفصلة، ولم تستبدل نظام الحجز الحالي.": "This is a separate V2 version and does not replace the current booking system.",
  "تأكيد الحجز بتاريخ سابق": "Confirm past-date booking",
  "تاريخ الحجز المحدد سابق لتاريخ اليوم. هل تريد متابعة إنشاء الحجز؟": "The selected booking date is before today. Do you want to continue creating the booking?",
  "تأكيد وإنشاء الحجز": "Confirm and create booking",
  "الخصم غير نشط.": "The discount is inactive.",
  "الخصم خارج فترة الصلاحية.": "The discount is outside its validity period.",
  "تم تجاوز حد استخدام الخصم.": "The discount usage limit has been reached.",
  "لا توجد خدمات مؤهلة لهذا الخصم.": "No services are eligible for this discount.",
  "لم يتحقق الحد الأدنى للخصم.": "The discount minimum has not been met.",
  "نوع الخصم غير صحيح.": "The discount type is invalid.",
  "قيمة الخصم غير صحيحة.": "The discount value is invalid.",
  "النسبة لا يمكن أن تتجاوز 100%.": "The percentage cannot exceed 100%.",
  "الخصم الناتج يساوي صفر.": "The resulting discount is zero.",
  "نشطة": "Active",
  "مستنفدة": "Exhausted",
  "منتهية": "Expired",
  "ملغاة": "Cancelled",
  "شراء باقة": "Package purchase",
  "حجز جلسة": "Session booking",
  "استهلاك جلسة": "Session redemption",
  "تأكيد استهلاك": "Confirm redemption",
  "إعادة جلسة محجوزة": "Return booked session",
  "استرجاع جلسة": "Refund session",
  "إلغاء باقة": "Cancel package",
  "تعديل إداري": "Administrative adjustment",
  "إضافة جلسة يدوية": "Add manual session",
  "استرجاع إداري": "Administrative refund",
  "حركة جلسة": "Session movement",
  "تعذر تحميل بيانات الباقات والجلسات.": "Could not load package and session data.",
  "عميلة بدون اسم": "Unnamed client",
  "عدد الجلسات يجب أن يكون رقمًا صحيحًا من 1 إلى 1000.": "Session count must be an integer from 1 to 1000.",
  "اكتبي سبب التعديل ليظهر في سجل الجلسات.": "Enter the adjustment reason so it appears in the session log.",
  "لا يمكن خصم عدد أكبر من الجلسات المتبقية.": "You cannot deduct more sessions than the remaining balance.",
  "تعذر تعديل رصيد الجلسات.": "Could not adjust the session balance.",
  "اكتبي اسم الباقة.": "Enter the package name.",
  "تعذر تعديل بيانات الباقة.": "Could not update package information.",
  "تعذر حذف الباقة.": "Could not delete the package.",
  "أدخلي اسم العميلة.": "Enter the client name.",
  "أدخلي رقم جوال سعودي صحيح.": "Enter a valid Saudi mobile number.",
  "اختاري الباقة أو الخدمة المرتبطة بالجلسة.": "Select the package or service linked to the session.",
  "يوجد أكثر من ملف عميلة بنفس رقم الجوال. يجب دمج الملفات المكررة أولًا.": "More than one client record has this phone number. Merge duplicate records first.",
  "إضافة جلسة للعميلة من لوحة الإدارة": "Add a client session from the admin dashboard",
  "تعذر إضافة الجلسة للعميلة.": "Could not add the session for the client.",
  "نظرة عامة": "Overview",
  "العميلات المشتركات": "Subscribed clients",
  "الباقات": "Packages",
  "سجل الجلسات": "Session log",
  "إدارة الباقات والجلسات": "Package and session management",
  "جاري التحديث": "Refreshing",
  "تحديث البيانات": "Refresh data",
  "أقسام إدارة الجلسات": "Session management sections",
  "ابحثي باسم العميلة أو الجوال أو الباقة أو رقم الحجز...": "Search by client, phone, package or booking number...",
  "بدون رقم فاتورة": "No invoice number",
  "محفظة الجلسات": "Session wallet",
  "محفظة العميلة": "Client wallet",
  "إدارة الرصيد": "Manage balance",
  "تعديل جلسات الباقة": "Adjust package sessions",
  "التعديل يطبّق على الباقة الحالية فقط، ويُحفظ كحركة إدارية في سجل الجلسات.": "The adjustment applies only to the current package and is saved as an administrative movement in the session log.",
  "حفظ تعديل الجلسات": "Save session adjustment",
  "نوع التعديل": "Adjustment type",
  "مثال: تعويض جلسة أو تصحيح رصيد": "Example: compensation session or balance correction",
  "بيانات الباقة": "Package information",
  "تعديل بيانات الباقة": "Edit package information",
  "عدّلي اسم الباقة أو تاريخ الانتهاء فقط. رصيد الجلسات له إجراء مستقل ومحفوظ في السجل.": "Edit only the package name or expiry date. Session balance has a separate action recorded in the log.",
  "حفظ بيانات الباقة": "Save package information",
  "جلسة يدوية": "Manual session",
  "إضافة جلسة لعميلة": "Add session for client",
  "أدخلي بيانات العميلة وحددي الباقة وعدد الجلسات. إذا لم يكن لها ملف، سيتم إنشاؤه تلقائيًا داخل Core D1.": "Enter client details, select the package and session count. If the client has no record, one will be created automatically in Core D1.",
  "جاري الإضافة...": "Adding...",
  "حفظ وإضافة الجلسة": "Save and add session",
  "مثال: غادة العليان": "Example: Ghada Alolayan",
  "اختاري الباقة أو الخدمة": "Select package or service",
  "لا توجد باقات نشطة": "No active packages",
  "سبب الإضافة أو أي ملاحظة داخلية": "Addition reason or internal note",
  "الحجز الإداري": "Admin booking",
  "إنشاء حجز جديد بخطوات واضحة وسريعة.": "Create a new booking with a clear, fast workflow.",
  "حجز جديد": "New booking",
  "الباقات والجلسات": "Packages and sessions",
  "البحث عن العميلة": "Find client",
  "ابحثي بالاسم أو رقم الجوال أو رقم العضوية MK.": "Search by name, phone or MK membership number.",
  "عميلات": "clients",
  "استخدامات": "uses",
  "عميلة": "Client",
  "جلسات متبقية": "sessions remaining",
  "أو": "or",
  "اسم العميلة": "Client name",
  "رقم الجوال": "Phone number",
  "جاري التحقق من رقم الجوال...": "Checking phone number...",
  "نتأكد أن العميلة غير مسجلة مسبقًا.": "Checking that the client is not already registered.",
  "تم العثور على عميلة مسجلة": "Registered client found",
  "سجل موجود": "Existing record",
  "رقم العضوية": "Membership number",
  "لن يتم إنشاء سجل جديد. اختاري العميلة الموجودة للمتابعة بالحجز.": "No new record will be created. Select the existing client to continue booking.",
  "الاسم الذي كتبتيه مختلف عن الاسم المسجل؛ لن نستبدل بيانات العميلة تلقائيًا.": "The entered name differs from the registered name; client data will not be replaced automatically.",
  "تعذر التحقق من رقم الجوال": "Could not verify phone number",
  "رقم الجوال غير مسجل حاليًا": "Phone number is not currently registered",
  "يمكن إنشاء عميلة جديدة بهذا الرقم.": "A new client can be created with this number.",
  "نصيحة": "Tip",
  "استخدمي الاسم أو رقم الجوال أو رقم العضوية للوصول إلى العميلة بسرعة.": "Use the name, phone number or membership number to find the client quickly.",
  "القائمة مرتبطة الآن بكتالوج الخدمات الحقيقي.": "The list is connected to the live service catalog.",
  "الموظفات والأوقات مرتبطة الآن ببيانات الدوام والحجوزات الفعلية.": "Staff and times are connected to actual schedules and bookings.",
  "راجعي الحجز ثم اختاري طريقة ونوع التحصيل.": "Review the booking, then choose collection type and payment method.",
  "خصم هذه الخدمة": "Discount for this service",
  "حفظ الحجز بعربون": "Save booking with deposit",
  "حفظ الحجز وتحصيل": "Save booking and collect",
  "إدارة اشتراكات العميلات، أرصدة الجلسات، والانتهاء وسجل الحركات من مصدر واحد.": "Manage client subscriptions, session balances, expiry and movement history from one source.",
  "تعذر تحميل الباقات والجلسات": "Could not load packages and sessions",
  "إعادة المحاولة": "Try again",
  "الباقات النشطة": "Active packages",
  "الجلسات المتبقية": "Remaining sessions",
  "الجلسات المستخدمة": "Used sessions",
  "الباقات التي تحتاج متابعة": "Packages needing attention",
  "رصيد منخفض أو انتهاء خلال 30 يومًا.": "Low balance or expiry within 30 days.",
  "عرض الكل": "View all",
  "جلسات": "sessions",
  "لا توجد باقات تحتاج متابعة حاليًا.": "No packages need attention right now.",
  "آخر حركات الجلسات": "Recent session movements",
  "آخر عمليات الشراء والحجز والاستهلاك والاسترجاع.": "Latest purchase, booking, redemption and refund activity.",
  "السجل الكامل": "Full log",
  "لا توجد حركات جلسات مسجلة حتى الآن.": "No session movements recorded yet.",
  "المستخدم": "Used",
  "المحجوز": "Reserved",
  "الإجراء": "Action",
  "عرض المحفظة": "Open wallet",
  "لا توجد عميلات مشتركات مطابقة للبحث.": "No subscribed clients match the search.",
  "الباقة": "Package",
  "الانتهاء": "Expiry",
  "فاتورة": "Invoice",
  "تعديل الجلسات": "Adjust sessions",
  "لا توجد باقات مطابقة للبحث.": "No packages match the search.",
  "نوع الحركة": "Movement type",
  "التغير": "Change",
  "الرصيد قبل": "Balance before",
  "الرصيد بعد": "Balance after",
  "لا توجد حركات مطابقة للبحث.": "No movements match the search.",
  "فتح محفظة العميلة": "Open client wallet",
  "لا توجد باقات تحتاج متابعة.": "No packages need attention.",
  "تنتهي": "Expires",
  "آخر الحركات": "Recent movements",
  "لا توجد حركات مسجلة.": "No movements recorded.",
  "الرصيد الحالي": "Current balance",
  "إضافة جلسات": "Add sessions",
  "خصم جلسات": "Deduct sessions",
  "عدد الجلسات": "Session count",
  "سبب التعديل": "Adjustment reason",
  "الرصيد بعد التعديل": "Balance after adjustment",
  "اسم الباقة": "Package name",
  "تاريخ الانتهاء": "Expiry date",
  "الباقة أو الخدمة المرتبطة": "Linked package or service",
  "عدد الجلسات المراد إضافتها": "Sessions to add",
  "ملاحظة": "Note",
  "جلسات في الكتالوج": "sessions in catalog",
  "جاري تحميل بيانات الباقات والجلسات...": "Loading package and session data...",
  "حذف نهائيًا من Cloudflare D1 مع سجل حركاتها؟": "permanently from Cloudflare D1 along with its movement history?",
  "تمت إضافة": "Added",
  "جلسة إلى": "session(s) to",
  "بنجاح.": "successfully.",
  "إلى": "To",
  "موظفة": "Staff member",
};

export function bookingsText(language: DashboardLanguage, arabic: string): string {
  if (language === "ar") return arabic;
  if (arabic.endsWith(":")) return `${bookingsText(language, arabic.slice(0, -1))}:`;
  return bookingEnglish[arabic] ?? dashboardText(language, arabic);
}
