import { dashboardText, type DashboardLanguage } from "./dashboardLanguage";

export type { DashboardLanguage } from "./dashboardLanguage";

const reportsEnglish: Record<string, string> = {
  "يناير": "January",
  "فبراير": "February",
  "مارس": "March",
  "أبريل": "April",
  "مايو": "May",
  "يونيو": "June",
  "يوليو": "July",
  "أغسطس": "August",
  "سبتمبر": "September",
  "أكتوبر": "October",
  "نوفمبر": "November",
  "ديسمبر": "December",
  "مؤكد": "Confirmed",
  "مكتمل": "Completed",
  "ملغي": "Cancelled",
  "انتظار": "Pending",
  "مرفوض": "Rejected",
  "نشط": "Active",
  "مسترجع": "Refunded",
  "ملغي/Voided": "Cancelled / Voided",
  "حجز": "Booking",
  "فاتورة": "Invoice",
  "داخلي": "Internal",
  "استرجاع": "Refund",
  "دخل آخر": "Other income",
  "كاش": "Cash",
  "شبكة": "Card",
  "تحويل": "Transfer",
  "مختلط": "Mixed",
  "أخرى": "Other",
  "الكل": "All",
  "الإدارة": "Management",
  "خطأ غير معروف": "Unknown error",
  "تعذر تحميل الحجوزات": "Could not load bookings",
  "تعذر تحميل الإيرادات": "Could not load income",
  "تعذر تحميل المصروفات": "Could not load expenses",
  "تعذر تحميل كشوف الرواتب": "Could not load payroll records",
  "تعذر احتساب مسير جميع الموظفات": "Could not calculate payroll for all staff",
  "لوحة التقارير العامة": "General reports dashboard",
  "تعذر إنشاء ملف PDF. أعد المحاولة بعد اكتمال تحميل البيانات.": "Could not create the PDF. Try again after data finishes loading.",
  "تعذر إنشاء ملف Excel. أعد المحاولة بعد اكتمال تحميل البيانات.": "Could not create the Excel file. Try again after data finishes loading.",
  "جاري تجهيز PDF...": "Preparing PDF...",
  "تصدير PDF": "Export PDF",
  "جاري تجهيز Excel...": "Preparing Excel...",
  "تصدير Excel": "Export Excel",
  "اليوم": "Today",
  "هذا الأسبوع": "This week",
  "هذا الشهر": "This month",
  "هذه السنة": "This year",
  "فترة مخصصة": "Custom period",
  "الفترة الحالية": "Current period",
  "الشهر": "Month",
  "من": "From",
  "إلى": "To",
  "طريقة الدفع": "Payment method",
  "المصدر": "Source",
  "الحالة": "Status",
  "الفترة": "Period",
  "التحليل المالي": "Financial analysis",
  "اللوحة المالية": "Financial dashboard",
  "متابعة موحدة للإيرادات والمصروفات وصافي الربح، مع المقارنات الزمنية ودورة الرواتب والتفاصيل المطابقة للفلاتر الحالية. العرض الشهري تقويمي، بينما تُعرض دورة الرواتب المحاسبية للفترة من يوم 28 إلى يوم 27.": "A unified view of income, expenses and net profit, with time comparisons, payroll cycle data and details matching the current filters. Monthly views use calendar months, while the accounting payroll cycle runs from day 28 to day 27.",
  "آخر مزامنة": "Last sync",
  "تصدير التقرير الكامل": "Export full report",
  "الملخص، الفلاتر، دورة الرواتب، الإيرادات والمصروفات": "Summary, filters, payroll cycle, income and expenses",
  "دورة الرواتب (28-27)": "Payroll cycle (28-27)",
  "الإغلاق المحاسبي ثابت يوم": "Accounting close is fixed on day",
  "الدورة": "Cycle",
  "رواتب": "Salaries",
  "صافي مسير جميع الموظفات بعد الإضافات والخصومات": "Net payroll for all staff after additions and deductions",
  "أوفر تايم": "Overtime",
  "مسجل يوميًا بتاريخ يومه الفعلي": "Recorded daily using the actual date",
  "مصروفات أخرى": "Other expenses",
  "باقي المصروفات": "Remaining expenses",
  "إجمالي الإيرادات": "Total income",
  "حسب الفترة والفلاتر الحالية": "Based on the current period and filters",
  "إجمالي المصروفات": "Total expenses",
  "المصروفات المسجلة داخل الفترة": "Expenses recorded within the period",
  "صافي الربح / الخسارة": "Net profit / loss",
  "الإيرادات بعد خصم المصروفات": "Income after deducting expenses",
  "مقارنة الأشهر (تقويميًا)": "Calendar month comparison",
  "مقابل": "vs.",
  "الإيرادات": "Income",
  "المصروفات": "Expenses",
  "صافي الربح": "Net profit",
  "اتجاه التدفقات": "Cash-flow trend",
  "الشهرية": "Monthly",
  "اليومية": "Daily",
  "مقارنة الإيرادات والمصروفات خلال الفترة المحددة": "Compare income and expenses during the selected period",
  "ملخص الرسم": "Chart summary",
  "نطاق الرسم": "Chart range",
  "يومي": "Daily",
  "شهري": "Monthly",
  "رسم اتجاه الإيرادات والمصروفات": "Income and expense trend chart",
  "تشغيل الحجوزات": "Booking operations",
  "حالة الحجوزات": "Booking statuses",
  "توزيع الحالات خلال الفترة الحالية": "Status distribution during the current period",
  "رسم حالات الحجوزات": "Booking status chart",
  "لا توجد حجوزات في الفترة": "No bookings in this period",
  "ستظهر حالات الحجوزات هنا فور تسجيل حركات جديدة.": "Booking statuses will appear here as soon as new activity is recorded.",
  "مزيج الإيرادات": "Income mix",
  "مصادر الإيرادات": "Income sources",
  "نسبة مساهمة كل مصدر في إجمالي الدخل": "Contribution of each source to total income",
  "رسم توزيع مصادر الإيرادات": "Income source distribution chart",
  "لا توجد إيرادات في الفترة": "No income in this period",
  "غيّر الفترة أو الفلاتر لعرض توزيع مصادر الإيرادات.": "Change the period or filters to view the income-source distribution.",
  "تفاصيل الإيرادات": "Income details",
  "عدد الحركات": "Movement count",
  "التاريخ/الوقت": "Date / time",
  "رقم الحجز MK": "MK booking number",
  "الموظفة": "Staff member",
  "الملاحظة": "Note",
  "المبلغ": "Amount",
  "لا توجد بيانات إيراد داخل الفترة.": "No income data within the period.",
  "تفاصيل المصروفات": "Expense details",
  "عدد السجلات": "Record count",
  "التاريخ": "Date",
  "التصنيف": "Category",
  "الوصف": "Description",
  "من أضافه": "Added by",
  "لا توجد مصروفات داخل الفترة.": "No expenses within the period.",
  "جاري احتساب مسير جميع الموظفات...": "Calculating payroll for all staff...",
  "جاري مزامنة البيانات...": "Syncing data...",
  "سجل حجز بدون ملاحظة": "Booking record without a note",
  "فاتورة بدون ملاحظة": "Invoice without a note",
  "دفع داخلي بدون ملاحظة": "Internal payment without a note",
  "استرجاع بدون ملاحظة": "Refund without a note",
  "دخل يدوي بدون ملاحظة": "Manual income without a note",
  "دخل آخر بدون ملاحظة": "Other income without a note",
  "كامل": "Full",
  "عربون": "Deposit",
  "جزئي": "Partial",
  "التقرير المالي العام": "General financial report",
  "ملخص مالي موحد مع الحركات المطابقة للفلاتر الحالية": "Unified financial summary with movements matching the current filters",
  "الملخص المالي": "Financial summary",
  "الحركات المالية": "Financial movements",
  "نوع الفترة": "Period type",
  "مصدر الإيراد": "Income source",
  "حالة الإيراد": "Income status",
  "دورة الرواتب": "Payroll cycle",
  "غير محددة": "Unspecified",
  "فترة دورة الرواتب": "Payroll cycle period",
  "عدد حركات الإيراد": "Income movement count",
  "عدد المصروفات": "Expense count",
  "رواتب الدورة": "Cycle salaries",
  "أوفر تايم الدورة": "Cycle overtime",
  "إجمالي مصروفات الدورة": "Total cycle expenses",
  "نوع الحركة": "Movement type",
  "المرجع": "Reference",
  "المصدر / التصنيف": "Source / category",
  "الموظفة / من أضافه": "Staff member / added by",
  "الوصف والملاحظات": "Description and notes",
  "الأثر المالي": "Financial impact",
  "إيراد": "Income",
  "مصروف": "Expense",
  "بدون مرجع": "No reference",
  "حركة إيراد": "Income movement",
  "لا توجد حركات مالية مطابقة للفلاتر الحالية.": "No financial movements match the current filters.",
  "يعتمد التقرير على النتائج والفلاتر الظاهرة وقت التصدير، وليس على السجلات المستبعدة بالفلاتر.": "The report uses the results and filters visible at export time, not records excluded by filters.",
  "لا تتوفر بيانات اتجاه إضافية للفترة الحالية.": "No additional trend data is available for the current period."
};

export function reportsText(language: DashboardLanguage, arabic: string): string {
  if (language === "ar") return arabic;
  return reportsEnglish[arabic] ?? dashboardText(language, arabic);
}
