import { dashboardText, type DashboardLanguage } from "./dashboardLanguage";

export type { DashboardLanguage } from "./dashboardLanguage";

const incomeEnglish: Record<string, string> = {
  "الإدارة المالية": "Financial management",
  "الإيرادات": "Income",
  "متابعة وتسجيل الإيرادات اليومية مع توحيد طرق الدفع والتقارير المالية.": "Track and record daily income with standardized payment methods and financial reports.",
  "إجراءات صفحة الإيرادات": "Income page actions",
  "إضافة دخل": "Add income",
  "تحميل PDF": "Download PDF",
  "Excel منسّق": "Formatted Excel",
  "ملخص الإيرادات": "Income summary",
  "إجمالي الإيرادات": "Total income",
  "حسب الفترة المحددة": "For the selected period",
  "إيرادات الكاش": "Cash income",
  "المدفوع نقدًا": "Paid in cash",
  "إيرادات الشبكة": "Card income",
  "مدفوعات البطاقات": "Card payments",
  "التحويلات": "Transfers",
  "التحويلات البنكية": "Bank transfers",
  "دخل آخر": "Other income",
  "الإيرادات اليدوية والأخرى": "Manual and other income",
  "إجمالي الاسترجاع": "Total refunds",
  "الحركات المالية السالبة": "Negative financial transactions",
  "البحث والفلاتر": "Search and filters",
  "تؤثر فترة التاريخ في المؤشرات، بينما يطبق البحث وطريقة الدفع على السجلات المعروضة.": "The date period affects the metrics, while search and payment method filter the displayed records.",
  "مسح الفلاتر": "Clear filters",
  "بحث": "Search",
  "المصدر، الملاحظة، المبلغ، العميلة أو رقم الحجز": "Source, note, amount, client or booking number",
  "طريقة الدفع": "Payment method",
  "من تاريخ": "From date",
  "بداية الفترة": "Period start",
  "إلى تاريخ": "To date",
  "نهاية الفترة": "Period end",
  "سجل الإيرادات": "Income records",
  "سجل معروض من أصل": "records shown out of",
  "جارٍ التحديث": "Refreshing",
  "تعذر تحميل الإيرادات": "Could not load income",
  "جارٍ تحميل الإيرادات": "Loading income",
  "لا توجد إيرادات مطابقة": "No matching income records",
  "غيّر نطاق البحث أو امسح الفلاتر لعرض بقية السجلات.": "Change the search range or clear filters to show the remaining records.",
  "ابدأ بإضافة أول حركة إيراد.": "Start by adding the first income transaction.",
  "التاريخ": "Date",
  "المبلغ": "Amount",
  "الدفع": "Payment",
  "العميلة والحجز": "Client and booking",
  "المصدر": "Source",
  "الملاحظة": "Note",
  "ملخص الدفع": "Payment summary",
  "الإجراءات": "Actions",
  "عرض التفاصيل": "View details",
  "تعديل": "Edit",
  "حذف": "Delete",
  "من الحجوزات": "From bookings",
  "العميلة": "Client",
  "الحجز": "Booking",
  "عرض": "View",
  "إضافة حركة إيراد": "Add income transaction",
  "سجّل بيانات الحركة المالية، ثم احفظها لتظهر في المؤشرات والتقارير.": "Enter the financial transaction details, then save it to include it in metrics and reports.",
  "جارٍ الحفظ...": "Saving...",
  "حفظ الحركة": "Save transaction",
  "المبلغ (ر.س)": "Amount (SAR)",
  "طريقة السداد": "Payment method",
  "مثال: بيع منتج أو تعديل يدوي": "Example: product sale or manual adjustment",
  "السبب أو المرجع": "Reason or reference",
  "اكتب سبب الحركة أو مرجعها": "Enter the transaction reason or reference",
  "تعديل الدفع للحجز": "Edit booking payment",
  "تعديل مبلغ الإيراد": "Edit income amount",
  "يتطلب تعديل الحركات المالية إدخال الرقم السري المعتمد.": "Editing financial transactions requires the authorized PIN.",
  "تعديل آمن": "Secure edit",
  "حفظ التعديل": "Save changes",
  "الرقم السري": "PIN",
  "أدخل الرقم السري": "Enter PIN",
  "إجمالي الحجز (ر.س)": "Booking total (SAR)",
  "نوع الدفع": "Payment type",
  "المبلغ المدفوع (ر.س)": "Paid amount (SAR)",
  "المدفوع": "Paid",
  "المتبقي": "Remaining",
  "المبلغ الجديد (ر.س)": "New amount (SAR)",
  "حذف سجل الإيراد؟": "Delete income record?",
  "لن يظهر السجل في المؤشرات أو التقارير بعد الحذف.": "The record will no longer appear in metrics or reports after deletion.",
  "إجراء حساس": "Sensitive action",
  "جارٍ الحذف...": "Deleting...",
  "تأكيد الحذف": "Confirm deletion",
  "تراجع": "Cancel",
  "الرقم السري للحذف": "Deletion PIN",
  "تفاصيل حركة الإيراد": "Income transaction details",
  "عرض سريع للسجل وبيانات الحجز المرتبطة.": "Quick view of the record and linked booking data.",
  "تعديل الحركة": "Edit transaction",
  "إغلاق": "Close",
  "المبلغ المسجل": "Recorded amount",
  "حركة استرجاع": "Refund transaction",
  "حركة إيراد": "Income transaction",
  "رقم الحجز": "Booking number",
  "غير مرتبط بحجز": "Not linked to a booking",
  "كاش": "Cash",
  "شبكة": "Card",
  "تحويل": "Transfer",
  "مختلط": "Mixed",
  "أخرى": "Other",
  "كل طرق الدفع": "All payment methods",
  "دفع كامل": "Full payment",
  "عربون": "Deposit",
  "كامل": "Full",
  "غير محدد": "Unspecified",
  "شراء باقة": "Package purchase",
  "بدون حجز": "No booking",
  "حجز": "Booking",
  "فاتورة": "Invoice",
  "عميلة غير محددة": "Unspecified client",
  "حجز داخلي": "Internal booking",
  "غير متوفر": "Unavailable",
  "سجل حجز بدون ملاحظة": "Booking record with no note",
  "فاتورة بدون ملاحظة": "Invoice with no note",
  "دفع داخلي بدون ملاحظة": "Internal payment with no note",
  "دخل يدوي بدون ملاحظة": "Manual income with no note",
  "استرجاع بدون ملاحظة": "Refund with no note",
  "بدون ملاحظة": "No note",
  "استرجاع": "Refund",
  "مدفوع": "Paid",
  "كاش/شبكة": "Cash/Card",
  "نقد": "Cash",
  "مدى": "Mada",
  "بطاق": "Card",
  "دخل": "Income",
  "⚠️ لا توجد صلاحيات كافية.": "⚠️ Insufficient permissions.",
  "⚠️ المسار غير موجود.": "⚠️ Endpoint not found.",
  "⚠️ الاستعلام يحتاج Index.": "⚠️ This query requires an index.",
  "تعذر تنفيذ العملية.": "Could not complete the operation.",
  "يدوي": "Manual",
  "تم تحديث بيانات الإيرادات": "Income data refreshed",
  "سجّل دخول الإدارة أولاً": "Sign in to the management account first",
  "بيانات غير صحيحة": "Invalid data",
  "سبب/مرجع الدخل مطلوب": "Income reason/reference is required",
  "تمت إضافة سجل الإيراد": "Income record added",
  "الاسترجاع يُدار من صفحة الحجوزات حتى تبقى الفاتورة والمدفوعات متطابقة.": "Refunds are managed from the bookings page to keep invoices and payments reconciled.",
  "لا تملك صلاحية إدارة الإيرادات.": "You do not have permission to manage income.",
  "إيراد الحجز يُدار من الحجز نفسه حتى تبقى الفاتورة والمدفوعات والإيراد متطابقة.": "Booking income is managed from the booking itself to keep the invoice, payments and income reconciled.",
  "إيراد الحجز لا يُحذف مباشرة من صفحة الإيرادات.": "Booking income cannot be deleted directly from the income page.",
  "الرقم السري غير صحيح": "Incorrect PIN",
  "تم حذف سجل الإيراد": "Income record deleted",
  "لا تملك صلاحية إدارة دفعات الحجوزات.": "You do not have permission to manage booking payments.",
  "الدفع المختلط يُعدّل من صفحة الحجوزات حتى يتم توزيع المبلغ على طرق الدفع بشكل صريح.": "Mixed payments are edited from the bookings page so the amount can be allocated explicitly across payment methods.",
  "إجمالي الحجز غير صحيح.": "The booking total is invalid.",
  "مبلغ العربون غير صحيح.": "The deposit amount is invalid.",
  "مبلغ العربون لا يمكن أن يتجاوز إجمالي الحجز.": "The deposit cannot exceed the booking total.",
  "المبلغ المدفوع غير صحيح.": "The paid amount is invalid.",
  "تم تعديل طريقة الدفع وتحديث الإيراد": "Payment method updated and income reconciled",
  "المبلغ غير صحيح.": "The amount is invalid.",
  "تم تعديل المبلغ": "Amount updated",
  "الكل": "All",
  "لوحة الإيرادات": "Income dashboard",
  "ما فيه بيانات للتصدير": "There is no data to export",
  "تم تحميل ملف PDF": "PDF downloaded",
  "تعذر إنشاء ملف PDF": "Could not create the PDF",
  "دفعت": "Paid",
  "المتبقي": "Remaining",
  "إلغاء": "Cancel",
  "تحديث": "Refresh",
  "إعادة المحاولة": "Try again",
  "تقرير الإيرادات": "Income report",
  "حركات الإيرادات والمدفوعات المطابقة للفلاتر الحالية": "Income and payment transactions matching the current filters",
  "تفاصيل الإيرادات": "Income details",
  "طريقة الدفع": "Payment method",
  "المصدر / البحث": "Source / search",
  "عدد حركات الإيراد": "Income transactions",
  "رقم الحجز / الفاتورة": "Booking / invoice number",
  "الخدمات": "Services",
  "الموظفة": "Staff member",
  "الإجمالي": "Total",
  "الحالة": "Status",
  "ملاحظات": "Notes",
  "لا توجد إيرادات مطابقة للفلاتر الحالية.": "No income records match the current filters.",
  "النظام": "System",
  "المرجع الكامل": "Full reference",
  "تعديل دفعة حجز": "Booking payment edit",
  "فاتورة من الاستقبال": "Reception invoice",
  "دفع حجز داخلي": "Internal booking payment",
  "طريقة الدفع": "Payment method",
};

export function incomeText(language: DashboardLanguage, arabic: string): string {
  if (language === "ar") return arabic;
  return incomeEnglish[arabic] ?? dashboardText(language, arabic);
}
