import { dashboardText, type DashboardLanguage } from "./dashboardLanguage";

export type { DashboardLanguage } from "./dashboardLanguage";

const clientsEnglish: Record<string, string> = {
  "إدارة العملاء": "Client management",
  "ملفات العميلات وحجوزاتهن وبيانات التواصل في مساحة واحدة منظّمة.": "Client profiles, bookings and contact details in one organized workspace.",
  "ملخص النتائج": "Results summary",
  "المصدر الحالي": "Current source",
  "بحث وأدوات العملاء": "Client search and tools",
  "ابحثي بالاسم أو رقم الجوال": "Search by name or phone number",
  "البحث باسم العميلة أو رقم الجوال": "Search by client name or phone number",
  "مسح البحث": "Clear search",
  "استيراد Excel": "Import Excel",
  "تصدير Excel": "Export Excel",
  "جارٍ التحديث": "Refreshing",
  "تحديث البيانات": "Refresh data",
  "جميع العميلات": "All clients",
  "لديها حجوزات": "Has bookings",
  "بدون حجوزات": "No bookings",
  "لديها باقات نشطة": "Has active packages",
  "كل الزيارات": "All visits",
  "خلال 30 يومًا": "Within 30 days",
  "خلال 90 يومًا": "Within 90 days",
  "لم تزر بعد": "No visit yet",
  "كل المصادر": "All sources",
  "ملف موحّد وحجوزات": "Unified profile + bookings",
  "ملف العميلة": "Client profile",
  "سجل الحجوزات": "Booking history",
  "الأحدث زيارة": "Latest visit",
  "الأحدث تسجيلًا": "Newest profile",
  "الأكثر حجزًا": "Most bookings",
  "فلاتر العملاء": "Client filters",
  "تصفية النتائج": "Filter results",
  "اختاري شريحة أو رتّبي السجلات للوصول أسرع.": "Choose a segment or sort records to find clients faster.",
  "شرائح العملاء": "Client segments",
  "آخر زيارة": "Last visit",
  "المصدر": "Source",
  "الترتيب": "Sort",
  "مسح الفلاتر": "Clear filters",
  "إجمالي العملاء": "Total clients",
  "كل الملفات الفريدة": "All unique profiles",
  "إجمالي الحجوزات": "Total bookings",
  "الحجوزات المرتبطة بالعميلات": "Bookings linked to clients",
  "العملاء النشطون": "Active clients",
  "حالة الملف نشطة": "Profile status is active",
  "الجدد هذا الشهر": "New this month",
  "ملفات أُنشئت خلال الشهر": "Profiles created this month",
  "عملاء VIP": "VIP clients",
  "العميلات المميزات": "VIP clients",
  "متوسط الحجوزات": "Average bookings",
  "لكل عميلة": "Per client",
  "إحصائيات العملاء": "Client statistics",
  "ملف موحّد": "Unified profile",
  "من سجل الحجوزات": "From booking history",
  "نشطة": "Active",
  "غير نشطة": "Inactive",
  "موقوفة": "Suspended",
  "غير محددة": "Unspecified",
  "عادية": "Regular",
  "اتصال": "Call",
  "نسخ رقم الجوال": "Copy phone number",
  "فتح واتساب": "Open WhatsApp",
  "عرض ملف العميلة": "View client profile",
  "عرض الملف": "View profile",
  "جارٍ تحميل العملاء": "Loading clients",
  "دليل العملاء": "Client directory",
  "ملفات العميلات": "Client profiles",
  "نتيجة": "results",
  "العميلة": "Client",
  "رقم الجوال": "Phone number",
  "البريد الإلكتروني": "Email",
  "المدينة": "City",
  "تاريخ الميلاد": "Birthdate",
  "رقم العضوية": "Membership ID",
  "الحالة": "Status",
  "عدد الحجوزات": "Bookings",
  "الإجراءات": "Actions",
  "حجزًا": "bookings",
  "قائمة العملاء للجوال": "Mobile client list",
  "تعذر تحميل بيانات العملاء": "Could not load client data",
  "لم يتم العثور على عميلات مطابقات": "No matching clients found",
  "لا توجد بيانات عملاء حتى الآن": "No client data yet",
  "جرّبي عبارة بحث أخرى أو امسحي الفلاتر الحالية.": "Try another search or clear the current filters.",
  "يمكنك إضافة عميلة من الحجز الإداري أو استيراد ملف Excel جاهز.": "Add a client through internal booking or import an Excel file.",
  "إعادة المحاولة": "Try again",
  "مسح البحث والفلاتر": "Clear search and filters",
  "إضافة عميلة": "Add client",
  "تعذر تحميل الحجوزات": "Could not load bookings",
  "تعذر تحميل ملفات العملاء": "Could not load client profiles",
  "تم نسخ رقم الجوال": "Phone number copied",
  "تعذر نسخ رقم الجوال": "Could not copy phone number",
  "غير مصرح": "Access denied",
  "هذه الصفحة متاحة للإدارة والاستقبال حسب الصلاحيات الحالية.": "This page is available to management and reception according to current permissions.",
  "مؤكد": "Confirmed",
  "في الانتظار": "Pending",
  "ملغي": "Cancelled",
  "مكتمل": "Completed",
  "ريال": "SAR",
  "لا يوجد نشاط": "No activity",
  "غير متوفر": "Unavailable",
  "رقم الجوال مستخدم في ملف عميلة أخرى. أدخلي رقمًا مختلفًا.": "This phone number is already used by another client profile. Enter a different number.",
  "رقم الجوال غير صحيح. استخدمي إحدى الصيغ السعودية المعتمدة.": "The phone number is invalid. Use a valid Saudi phone format.",
  "اسم العميلة مطلوب ولا يمكن أن يتكون من مسافات فقط.": "Client name is required and cannot contain spaces only.",
  "تعذر حفظ بيانات العميلة.": "Could not save client data.",
  "هذه العميلة غير مرتبطة بعد بمعرّف Core D1 موحّد.": "This client is not yet linked to a unified Core D1 ID.",
  "تعذر تحميل السجل المالي للعميلة": "Could not load the client's financial record",
  "لا يمكن تعديل عميلة غير مرتبطة بسجل Core D1.": "A client not linked to a Core D1 record cannot be edited.",
  "أدخلي رقم جوال سعوديًا صحيحًا مثل 0500000000.": "Enter a valid Saudi mobile number such as 0500000000.",
  "تم حفظ اسم العميلة ورقم الجوال في Core بنجاح.": "Client name and phone number were saved to Core successfully.",
  "تم حفظ بيانات العميلة في Core بنجاح.": "Client profile was saved to Core successfully.",
  "تاريخ الميلاد غير صحيح. استخدمي الصيغة YYYY-MM-DD.": "Birthdate is invalid. Use YYYY-MM-DD.",
  "غير مسجلة": "Not recorded",
  "لا يمكن حفظ ملاحظة لعميلة غير مرتبطة بسجل Core D1.": "A note cannot be saved for a client not linked to a Core D1 record.",
  "تم حفظ الملاحظة في Core.": "The note was saved to Core.",
  "تعذر حفظ الملاحظة في Core.": "Could not save the note to Core.",
  "أدخل عدد نقاط صحيحًا غير صفري وسبب التعديل.": "Enter a non-zero whole number of points and a reason.",
  "تم تسجيل حركة النقاط بنجاح.": "Points adjustment recorded successfully.",
  "تعذر تعديل النقاط": "Could not adjust points",
  "بدون رقم جوال": "No phone number",
  "البيانات الأساسية": "Basic information",
  "بيانات العميلة": "Client information",
  "تعديل البيانات": "Edit information",
  "اسم العميلة": "Client name",
  "أدخلي اسم العميلة": "Enter client name",
  "جارٍ حفظ التعديلات...": "Saving changes...",
  "حفظ التعديلات": "Save changes",
  "غير مسجل": "Not recorded",
  "التعديل متاح للمديرة أو المشرفة فقط.": "Editing is available to managers only.",
  "إجمالي الصرف": "Total spend",
  "السجل المالي والولاء": "Financial record and loyalty",
  "السجل الموحد للعميلة": "Unified client record",
  "الحجوزات والدفعات والاسترجاعات والنقاط من Core D1.": "Bookings, payments, refunds and points from Core D1.",
  "جارٍ تحميل السجل...": "Loading record...",
  "صافي المدفوع": "Net paid",
  "الاسترجاعات": "Refunds",
  "الرصيد الحالي": "Current balance",
  "نقطة": "points",
  "آخر نشاط": "Last activity",
  "النقاط والولاء": "Points and loyalty",
  "المستوى": "Level",
  "مكتسبة": "Earned",
  "مستخدمة": "Used",
  "معكوسة": "Reversed",
  "لا توجد حركات نقاط.": "No points transactions.",
  "عدد النقاط": "Points",
  "سبب التعديل": "Adjustment reason",
  "سبب تعديل النقاط": "Points adjustment reason",
  "جارٍ الحفظ": "Saving",
  "تسجيل الحركة": "Record adjustment",
  "الدفعات والاسترجاعات": "Payments and refunds",
  "دفعة": "Payment",
  "استرجاع": "Refund",
  "لا توجد حركات مالية.": "No financial transactions.",
  "العروض المستخدمة": "Used offers",
  "لم تُستخدم عروض مسجلة.": "No recorded offers have been used.",
  "ملاحظات إدارية داخلية": "Internal management notes",
  "مثال: تفضّل موظفة معينة، حساسية، أو أوقات مناسبة...": "Example: preferred staff member, sensitivity, or suitable times...",
  "جارٍ حفظ الملاحظة...": "Saving note...",
  "حفظ الملاحظة": "Save note",
  "السجل": "History",
  "حجوزات العميلة": "Client bookings",
  "رقم الحجز": "Booking number",
  "الخدمة": "Service",
  "الموظفة": "Staff member",
  "التاريخ والوقت": "Date and time",
  "الإجمالي": "Total",
  "لا توجد حجوزات مسجلة لهذه العميلة.": "No bookings are recorded for this client.",
  "استيراد عميلات من Excel": "Import clients from Excel",
  "تتم المطابقة برقم الجوال من دون حذف أي سجل.": "Clients are matched by phone number without deleting any record.",
  "دمج آمن": "Safe merge",
  "الملف لا يحتوي على ورقة بيانات.": "The file does not contain a worksheet.",
  "ملف Excel فارغ.": "The Excel file is empty.",
  "لم نجد صفوفًا صالحة. يجب أن يحتوي كل صف على رقم جوال.": "No valid rows were found. Each row must contain a phone number.",
  "تعذر قراءة ملف Excel.": "Could not read the Excel file.",
  "لا توجد بيانات جاهزة للحفظ.": "There is no data ready to save.",
  "حدث خطأ أثناء حفظ بيانات العميلات.": "An error occurred while saving client data.",
  "جارٍ الحفظ والدمج": "Saving and merging",
  "حفظ ودمج": "Save and merge",
  "اختاري ملف Excel": "Choose an Excel file",
  "الأعمدة المدعومة: الاسم، الجوال، VIP، ملاحظة.": "Supported columns: name, phone, VIP, note.",
  "معاينة البيانات": "Data preview",
  "الاسم": "Name",
  "الجوال": "Phone",
  "ملاحظة": "Note",
  "تم عرض أول 80 صفًا من": "Showing the first 80 rows of",
  "عميلة": "clients",
  "عميلة بدون اسم": "Unnamed client",
  "لا توجد زيارة": "No visit",
  "بيانات العميلة موجودة في السجل الموحد ومرتبطة بحجوزات": "Client data exists in the unified record and is linked to bookings",
  "ملف عميلة محفوظ في Core D1 ولا توجد له حجوزات حتى الآن": "Client profile is stored in Core D1 and has no bookings yet",
  "العميلة ظاهرة من سجل الحجوزات ولم يرتبط بها ملف Core موحد بعد": "Client appears from booking history and is not yet linked to a unified Core profile",
  "شراء": "Purchase",
  "حجز": "Reservation",
  "استخدام": "Use",
  "إلغاء واسترجاع": "Cancel and restore",
  "إلغاء باقة": "Cancel package",
  "تعديل إداري": "Administrative adjustment",
  "استرجاع إداري": "Administrative restore",
  "تعذر تحميل الباقات والجلسات.": "Could not load packages and sessions.",
  "عدد الجلسات المراد إضافتها أو خصمها (مثال: 1 أو -1)": "Number of sessions to add or deduct (example: 1 or -1)",
  "سبب التعديل الإداري": "Administrative adjustment reason",
  "يلزم إدخال عدد صحيح وسبب واضح.": "Enter a whole number and a clear reason.",
  "تعذر تعديل الرصيد.": "Could not adjust the balance.",
  "سبب إلغاء الباقة": "Package cancellation reason",
  "تعذر إلغاء الباقة.": "Could not cancel the package.",
  "سبب استرجاع الجلسة المستخدمة": "Reason for restoring the used session",
  "تعذر استرجاع الجلسة.": "Could not restore the session.",
  "لا يوجد مرجع فاتورة لهذه الباقة.": "There is no invoice reference for this package.",
  "تعذر العثور على الفاتورة الأصلية في Core D1.": "Could not find the original invoice in Core D1.",
  "لا يوجد clientId ثابت لهذا الملف؛ لا يمكن عرض الرصيد بالاعتماد على الهاتف فقط.": "This profile has no stable clientId; the balance cannot be shown using the phone number alone.",
  "الباقات والجلسات": "Packages and sessions",
  "لا توجد باقات مسجلة.": "No packages recorded.",
  "فاتورة": "Invoice",
  "المتبقي": "Remaining",
  "المحجوز": "Reserved",
  "المستخدم": "Used",
  "الشراء": "Purchased",
  "الانتهاء": "Expires",
  "الخدمات": "Services",
  "سجل الحركات": "Transaction history",
  "الحجوزات المرتبطة": "Linked bookings",
  "استرجاع جلسة": "Restore session",
  "فتح الفاتورة الأصلية": "Open original invoice",
  "تعديل الرصيد": "Adjust balance",
  "تأكيد إلغاء": "Confirm cancellation of",
  "الباقة": "Package",
  "الجلسات": "Sessions",
  "قبل الخصم": "Before discount",
  "الخصم": "Discount",
  "المدفوع": "Paid",
  "تاريخ الانتهاء": "Expiry date",
  "بدون انتهاء": "No expiry",
  "طباعة": "Print",
  "تحديث": "Refresh",
  "إلغاء": "Cancel",
  "غير محدد": "Unspecified",
  "إلغاء الباقة": "Cancel package",
};

export function clientsText(language: DashboardLanguage, arabic: string): string {
  if (language === "ar") return arabic;
  return clientsEnglish[arabic] ?? dashboardText(language, arabic);
}
