import { dashboardText, type DashboardLanguage } from "./dashboardLanguage";

export type { DashboardLanguage } from "./dashboardLanguage";

const settingsEnglish: Record<string, string> = {
  "هوية المنصة": "Platform identity",
  "اسم الصالون والجوال والمدينة": "Salon name, phone and city",
  "ظهور الأقسام": "Section visibility",
  "التحكم في أقسام لوحة التحكم": "Control dashboard sections",
  "سياسات التشغيل": "Operating policies",
  "صلاحيات وسلوك الأدوار داخل النظام": "Role permissions and behavior in the system",
  "نظرة عامة": "Overview",
  "ملخص سريع للوحة الرئيسية": "Quick summary of the main dashboard",
  "الحجوزات": "Bookings",
  "مواعيد العميلات وجدولة الزيارات": "Client appointments and visit scheduling",
  "العميلات": "Clients",
  "ملفات العميلات وسجل التعامل": "Client profiles and history",
  "الموظفات": "Staff",
  "إدارة الفريق والملفات الوظيفية": "Team and employment record management",
  "العروض والكوبونات": "Offers and coupons",
  "العروض، الباقات، وأكواد الخصم": "Offers, packages and discount codes",
  "التقارير": "Reports",
  "تقارير الأداء والحركة": "Performance and activity reports",
  "الإيرادات": "Income",
  "ملخص الدخل والمدفوعات": "Income and payment summary",
  "المصروفات": "Expenses",
  "سجل المصروفات التشغيلية": "Operating expense records",
  "تغيير حالة الحجز للموظفات": "Allow staff to change booking status",
  "تمكين الموظفة من تحديث حالة الموعد المرتبط بها.": "Allow a staff member to update the status of their assigned appointment.",
  "تغيير حالة الحجز للاستقبال": "Allow reception to change booking status",
  "تمكين الاستقبال من تحديث حالات الحجوزات اليومية.": "Allow reception to update daily booking statuses.",
  "مشاهدة العميلات للموظفات": "Allow staff to view clients",
  "السماح للموظفة باستعراض بيانات العميلات حسب الصلاحية.": "Allow staff to view client data according to permissions.",
  "إدارة الحسابات للـ Admin": "Allow Admin to manage accounts",
  "السماح للأدمن بإنشاء وتعديل الحسابات من صفحات الإدارة.": "Allow Admin users to create and edit accounts from management pages.",
  "جاري تحميل الإعدادات": "Loading settings",
  "الصفحات المباشرة": "Direct pages",
  "روابط متاحة حسب صلاحيات الحساب": "Links available according to account permissions",
  "الأقسام المفعلة": "Enabled sections",
  "من أقسام لوحة التحكم": "of dashboard sections",
  "السياسات النشطة": "Active policies",
  "سياسات تشغيل وصلاحيات": "Operating policies and permissions",
  "الحالة الحالية": "Current status",
  "قابل للتعديل": "Editable",
  "عرض محدود": "Limited view",
  "يمكن الحفظ مباشرة": "Changes can be saved directly",
  "حسب الصلاحيات الممنوحة": "According to granted permissions",
  "تم حفظ الإعدادات بنجاح": "Settings saved successfully",
  "تعذر حفظ الإعدادات": "Could not save settings",
  "غير مصرح": "Access denied",
  "لا يملك هذا الحساب صلاحية لفتح إعدادات لوحة التحكم.": "This account does not have permission to open dashboard settings.",
  "الإعدادات الأساسية": "Basic settings",
  "إعدادات لوحة التحكم": "Dashboard settings",
  "إدارة هوية الصالون، ظهور الأقسام، وسياسات التشغيل من مساحة واحدة واضحة.": "Manage salon identity, section visibility and operating policies from one clear workspace.",
  "أقسام متاحة": "available sections",
  "ملخص الإعدادات": "Settings summary",
  "أقسام الإعدادات الأساسية": "Basic settings sections",
  "أقسام مفعلة": "enabled sections",
  "سياسات نشطة": "active policies",
  "الإعدادات": "Settings",
  "البيانات الأساسية التي تظهر في الشاشات العامة والإدارية.": "Basic information shown across public and management screens.",
  "تحكم في الأقسام التي تظهر داخل لوحة التحكم والصفحات المرتبطة بها.": "Control which sections appear in the dashboard and its linked pages.",
  "صلاحيات تشغيلية تتحكم بسلوك الأدوار داخل النظام.": "Operating permissions that control role behavior in the system.",
  "جاهز للتعديل": "Ready to edit",
  "عرض فقط": "View only",
  "اسم الصالون": "Salon name",
  "الجوال": "Phone",
  "المدينة": "City",
  "مثال: MALIKAT": "Example: MALIKAT",
  "المدينة المنورة": "Madinah",
  "ظاهر": "Visible",
  "مخفي": "Hidden",
  "مفعلة": "Enabled",
  "متوقفة": "Disabled",
  "تحتاج صلاحية": "Requires permission",
  "لتعديل هذه القيم.": "to edit these values.",
  "حفظ إعدادات المنصة": "Save platform settings",
  "الحفظ يطبق على كل الشاشات التي تعتمد على AppSettings.": "Saved changes apply to every screen that uses AppSettings.",
  "تحتاج صلاحية settings.general.manage": "Requires settings.general.manage permission",
  "حفظ الإعدادات": "Save settings",
  "حفظ التغييرات": "Save changes"
  "إعدادات التواصل": "Contact settings",
  "بيانات التواصل واللوكيشن": "Contact and location details",
  "إدارة بيانات التواصل التي تظهر في الموقع، نص العنوان، الخريطة، ورسائل العميلات الواردة.": "Manage contact details shown on the website, address text, map and incoming client messages.",
  "آخر 20 رسالة": "Latest 20 messages",
  "إخفاء الرسائل": "Hide messages",
  "عرض الرسائل": "Show messages",
  "جديد": "new",
  "ملخص بيانات التواصل": "Contact details summary",
  "الحقول المعبأة": "Completed fields",
  "من بيانات التواصل الأساسية": "of basic contact fields",
  "إجمالي الرسائل": "Total messages",
  "آخر 20 رسالة فقط": "Latest 20 messages only",
  "الرسائل الجديدة": "New messages",
  "تحتاج مراجعة": "Needs review",
  "لا توجد رسائل جديدة": "No new messages",
  "الخريطة": "Map",
  "مربوطة": "Linked",
  "غير مربوطة": "Not linked",
  "بيانات التواصل الأساسية": "Basic contact details",
  "الجوال والواتساب والبريد والمدينة المستخدمة في واجهات العميلات.": "Phone, WhatsApp, email and city used in client-facing interfaces.",
  "4 حقول": "4 fields",
  "واتساب": "WhatsApp",
  "البريد الإلكتروني": "Email",
  "العنوان والخريطة": "Address and map",
  "نص الظهور في صفحة التواصل وساعات العمل ورابط Google Maps Embed.": "Display text for the contact page, opening hours and Google Maps Embed URL.",
  "الخريطة مربوطة": "Map linked",
  "بدون خريطة": "No map",
  "العنوان": "Address",
  "شارع... حي... المدينة...": "Street... district... city...",
  "العنوان المعروض في صفحة Contact": "Address shown on the Contact page",
  "اتركه فارغًا لاستخدام العنوان تلقائيًا": "Leave blank to use the address automatically",
  "إذا كان فارغًا، يستخدم النظام قيمة العنوان تلقائيًا عند الحفظ.": "If left blank, the system uses the address automatically when saving.",
  "ساعات العمل": "Opening hours",
  "استخدم رابط Embed نفسه المستخدم داخل iframe في صفحة التواصل.": "Use the same Embed URL used inside the iframe on the contact page.",
  "آخر الرسائل": "Latest messages",
  "آخر 20 رسالة واردة من نموذج التواصل، مع حالة القراءة.": "The latest 20 messages from the contact form, including read status.",
  "رسالة": "message",
  "رسائل": "messages",
  "جديدة": "New",
  "مقروءة": "Read",
  "تحديد كمقروء": "Mark as read",
  "الاسم": "Name",
  "البريد": "Email",
  "لا توجد رسائل حالياً": "No messages currently",
  "ستظهر رسائل العميلات هنا عند وصولها من نموذج التواصل.": "Client messages will appear here when they arrive from the contact form.",
  "حفظ بيانات التواصل": "Save contact details",
  "احفظ بعد تعديل البيانات حتى تنعكس على الصفحات التي تعتمد على مستند settings/public.": "Save after editing so changes appear on pages that use the settings/public document.",
  "الحساب الحالي يملك صلاحية العرض فقط ولا يستطيع تعديل بيانات التواصل.": "The current account has view-only access and cannot edit contact details.",
  "تحتاج صلاحية settings.content.manage": "Requires settings.content.manage permission",
  "جاري الحفظ…": "Saving…",
  "تم حفظ بيانات التواصل": "Contact details saved",
  "تعذر حفظ بيانات التواصل": "Could not save contact details"
};

export function settingsText(language: DashboardLanguage, arabic: string): string {
  if (language === "ar") return arabic;
  return settingsEnglish[arabic] ?? dashboardText(language, arabic);
}
