import { dashboardText, type DashboardLanguage } from "./dashboardLanguage";

export type { DashboardLanguage } from "./dashboardLanguage";

const dayAuditEnglish: Record<string, string> = {
  "تعذر تحميل جرد اليوم من Core.": "Could not load the day audit from Core.",
  "جاري تجهيز جرد اليوم": "Preparing day audit",
  "مقفل": "Closed",
  "مفتوح": "Open",
  "وقت الإغلاق": "Closing time",
  "إيراد الشبكة": "Card revenue",
  "إيراد التحويل (خارج القفل)": "Bank transfer revenue (outside cash reconciliation)",
  "جرد اليوم": "Day audit",
  "تاريخ الجرد": "Audit date",
  "الحالة": "Status",
  "إيراد الجرد (الكاش + الشبكة)": "Audit revenue (cash + card)",
  "إيراد الكاش": "Cash revenue",
  "الكاش اليدوي": "Physical cash",
  "فرق الكاش (الكاش اليدوي - إيراد الكاش)": "Cash difference (physical cash - recorded cash)",
  "تم إعداد الجرد آليًا من لوحة التحكم": "Audit generated automatically from the dashboard",
  "تعذر فتح نافذة الطباعة. فعّل النوافذ المنبثقة للموقع ثم أعد المحاولة.": "Could not open the print window. Allow pop-ups for this site and try again.",
  "الكاش اليدوي لا يمكن أن يكون رقمًا سالبًا.": "Physical cash cannot be negative.",
  "تعذر تحديث بيانات الجرد قبل الإقفال. لم يتم إقفال اليوم.": "Could not refresh audit data before closing. The day was not closed.",
  "الجرد اليومي": "Daily audit",
  "الجرد والإقفال اليومي": "Daily audit & closing",
  "مطابقة تحصيلات النظام مع الكاش الفعلي وإصدار محضر جرد واضح قبل إقفال اليوم.": "Reconcile system collections with physical cash and generate a clear audit record before closing the day.",
  "اليوم": "Today",
  "اليوم مقفل": "Day closed",
  "اليوم مفتوح": "Day open",
  "تم إقفال هذا اليوم في": "This day was closed at",
  "القيم محفوظة وغير قابلة للتعديل.": "Values are saved and cannot be edited.",
  "ملخص الجرد": "Audit summary",
  "إجمالي التحصيل": "Total collected",
  "تحصيل الكاش": "Cash collected",
  "حسب المدفوعات المسجلة": "Based on recorded payments",
  "الشبكة والتحويل": "Card & transfer",
  "شبكة": "Card",
  "تحويل": "Transfer",
  "فرق الكاش": "Cash difference",
  "الكاش الفعلي ناقص تحصيل الكاش": "Physical cash minus recorded cash",
  "عدّ الكاش": "Cash count",
  "إدخال الكاش الفعلي": "Enter physical cash",
  "أدخل المبلغ الموجود فعليًا في الصندوق، ثم راجع الفرق قبل الإقفال.": "Enter the cash physically present in the till, then review the difference before closing.",
  "مبلغ الكاش الموجود": "Cash in till",
  "تم تثبيت المبلغ عند إقفال اليوم.": "The amount was locked when the day was closed.",
  "استخدم المبلغ المحسوب فعليًا من الصندوق.": "Use the amount physically counted in the till.",
  "نتيجة المطابقة الحالية": "Current reconciliation result",
  "متطابق": "Matched",
  "عجز": "Shortage",
  "زيادة": "Overage",
  "طباعة مسودة الجرد": "Print audit draft",
  "تم إقفال اليوم": "Day closed",
  "طباعة وإقفال اليوم": "Print & close day",
  "التسوية": "Reconciliation",
  "تفصيل التسوية": "Reconciliation breakdown",
  "ملخص قنوات الدفع الداخلة في جرد التاريخ المحدد.": "Summary of payment channels included in the selected date audit.",
  "تحصيل الكاش بالنظام": "Recorded cash collection",
  "تحصيل الشبكة": "Card collection",
  "التحويل البنكي": "Bank transfer",
  "الكاش الفعلي": "Physical cash",
  "فرق الكاش النهائي": "Final cash difference",
  "قاعدة الإقفال": "Closing rule",
  "التحويل البنكي يظهر في الإجمالي، لكنه لا يدخل في مقارنة الكاش الفعلي مع صندوق الاستقبال.": "Bank transfers appear in the total but are excluded from the physical-cash reconciliation with the reception till."
};

export function dayAuditText(language: DashboardLanguage, arabic: string): string {
  if (language === "ar") return arabic;
  return dayAuditEnglish[arabic] ?? dashboardText(language, arabic);
}
