import { dashboardText, type DashboardLanguage } from "./dashboardLanguage";

export type { DashboardLanguage } from "./dashboardLanguage";

const settingsEnglish: Record<string, string> = {
  "هوية المنصة": "Platform identity",
  "اسم الصالون والجوال والمدينة": "Salon name, phone and city",
  "ظهور الأقسام": "Section visibility",
  "التحكم في أقسام لوحة التحكم": "Control dashboard sections",
  "سياسات التشغيل": "Operating policies",
  "صلاحيات وسلوك الأدوار داخل النظام": "Role permissions and behavior in the system",
  "نظرة عامة": "Overview",
  "ملخص سريع للوحة الرئيسية": "Quick summary of the main dashboard",
  "الحجوزات": "Bookings",
  "مواعيد العميلات وجدولة الزيارات": "Client appointments and visit scheduling",
  "العميلات": "Clients",
  "ملفات العميلات وسجل التعامل": "Client profiles and history",
  "الموظفات": "Staff",
  "إدارة الفريق والملفات الوظيفية": "Team and employment record management",
  "العروض والكوبونات": "Offers and coupons",
  "العروض، الباقات، وأكواد الخصم": "Offers, packages and discount codes",
  "التقارير": "Reports",
  "تقارير الأداء والحركة": "Performance and activity reports",
  "الإيرادات": "Income",
  "ملخص الدخل والمدفوعات": "Income and payment summary",
  "المصروفات": "Expenses",
  "سجل المصروفات التشغيلية": "Operating expense records",
  "تغيير حالة الحجز للموظفات": "Allow staff to change booking status",
  "تمكين الموظفة من تحديث حالة الموعد المرتبط بها.": "Allow a staff member to update the status of their assigned appointment.",
  "تغيير حالة الحجز للاستقبال": "Allow reception to change booking status",
  "تمكين الاستقبال من تحديث حالات الحجوزات اليومية.": "Allow reception to update daily booking statuses.",
  "مشاهدة العميلات للموظفات": "Allow staff to view clients",
  "السماح للموظفة باستعراض بيانات العميلات حسب الصلاحية.": "Allow staff to view client data according to permissions.",
  "إدارة الحسابات للـ Admin": "Allow Admin to manage accounts",
  "السماح للأدمن بإنشاء وتعديل الحسابات من صفحات الإدارة.": "Allow Admin users to create and edit accounts from management pages.",
  "جاري تحميل الإعدادات": "Loading settings",
  "الصفحات المباشرة": "Direct pages",
  "روابط متاحة حسب صلاحيات الحساب": "Links available according to account permissions",
  "الأقسام المفعلة": "Enabled sections",
  "من أقسام لوحة التحكم": "of dashboard sections",
  "السياسات النشطة": "Active policies",
  "سياسات تشغيل وصلاحيات": "Operating policies and permissions",
  "الحالة الحالية": "Current status",
  "قابل للتعديل": "Editable",
  "عرض محدود": "Limited view",
  "يمكن الحفظ مباشرة": "Changes can be saved directly",
  "حسب الصلاحيات الممنوحة": "According to granted permissions",
  "تم حفظ الإعدادات بنجاح": "Settings saved successfully",
  "تعذر حفظ الإعدادات": "Could not save settings",
  "غير مصرح": "Access denied",
  "لا يملك هذا الحساب صلاحية لفتح إعدادات لوحة التحكم.": "This account does not have permission to open dashboard settings.",
  "الإعدادات الأساسية": "Basic settings",
  "إعدادات لوحة التحكم": "Dashboard settings",
  "إدارة هوية الصالون، ظهور الأقسام، وسياسات التشغيل من مساحة واحدة واضحة.": "Manage salon identity, section visibility and operating policies from one clear workspace.",
  "أقسام متاحة": "available sections",
  "ملخص الإعدادات": "Settings summary",
  "أقسام الإعدادات الأساسية": "Basic settings sections",
  "أقسام مفعلة": "enabled sections",
  "سياسات نشطة": "active policies",
  "الإعدادات": "Settings",
  "البيانات الأساسية التي تظهر في الشاشات العامة والإدارية.": "Basic information shown across public and management screens.",
  "تحكم في الأقسام التي تظهر داخل لوحة التحكم والصفحات المرتبطة بها.": "Control which sections appear in the dashboard and its linked pages.",
  "صلاحيات تشغيلية تتحكم بسلوك الأدوار داخل النظام.": "Operating permissions that control role behavior in the system.",
  "جاهز للتعديل": "Ready to edit",
  "عرض فقط": "View only",
  "اسم الصالون": "Salon name",
  "الجوال": "Phone",
  "المدينة": "City",
  "مثال: MALIKAT": "Example: MALIKAT",
  "المدينة المنورة": "Madinah",
  "ظاهر": "Visible",
  "مخفي": "Hidden",
  "مفعلة": "Enabled",
  "متوقفة": "Disabled",
  "تحتاج صلاحية": "Requires permission",
  "لتعديل هذه القيم.": "to edit these values.",
  "حفظ إعدادات المنصة": "Save platform settings",
  "الحفظ يطبق على كل الشاشات التي تعتمد على AppSettings.": "Saved changes apply to every screen that uses AppSettings.",
  "تحتاج صلاحية settings.general.manage": "Requires settings.general.manage permission",
  "حفظ الإعدادات": "Save settings",
  "حفظ التغييرات": "Save changes"
  "إعدادات التواصل": "Contact settings",
  "بيانات التواصل واللوكيشن": "Contact and location details",
  "إدارة بيانات التواصل التي تظهر في الموقع، نص العنوان، الخريطة، ورسائل العميلات الواردة.": "Manage contact details shown on the website, address text, map and incoming client messages.",
  "آخر 20 رسالة": "Latest 20 messages",
  "إخفاء الرسائل": "Hide messages",
  "عرض الرسائل": "Show messages",
  "جديد": "new",
  "ملخص بيانات التواصل": "Contact details summary",
  "الحقول المعبأة": "Completed fields",
  "من بيانات التواصل الأساسية": "of basic contact fields",
  "إجمالي الرسائل": "Total messages",
  "آخر 20 رسالة فقط": "Latest 20 messages only",
  "الرسائل الجديدة": "New messages",
  "تحتاج مراجعة": "Needs review",
  "لا توجد رسائل جديدة": "No new messages",
  "الخريطة": "Map",
  "مربوطة": "Linked",
  "غير مربوطة": "Not linked",
  "بيانات التواصل الأساسية": "Basic contact details",
  "الجوال والواتساب والبريد والمدينة المستخدمة في واجهات العميلات.": "Phone, WhatsApp, email and city used in client-facing interfaces.",
  "4 حقول": "4 fields",
  "واتساب": "WhatsApp",
  "البريد الإلكتروني": "Email",
  "العنوان والخريطة": "Address and map",
  "نص الظهور في صفحة التواصل وساعات العمل ورابط Google Maps Embed.": "Display text for the contact page, opening hours and Google Maps Embed URL.",
  "الخريطة مربوطة": "Map linked",
  "بدون خريطة": "No map",
  "العنوان": "Address",
  "شارع... حي... المدينة...": "Street... district... city...",
  "العنوان المعروض في صفحة Contact": "Address shown on the Contact page",
  "اتركه فارغًا لاستخدام العنوان تلقائيًا": "Leave blank to use the address automatically",
  "إذا كان فارغًا، يستخدم النظام قيمة العنوان تلقائيًا عند الحفظ.": "If left blank, the system uses the address automatically when saving.",
  "ساعات العمل": "Opening hours",
  "استخدم رابط Embed نفسه المستخدم داخل iframe في صفحة التواصل.": "Use the same Embed URL used inside the iframe on the contact page.",
  "آخر الرسائل": "Latest messages",
  "آخر 20 رسالة واردة من نموذج التواصل، مع حالة القراءة.": "The latest 20 messages from the contact form, including read status.",
  "رسالة": "message",
  "رسائل": "messages",
  "جديدة": "New",
  "مقروءة": "Read",
  "تحديد كمقروء": "Mark as read",
  "الاسم": "Name",
  "البريد": "Email",
  "لا توجد رسائل حالياً": "No messages currently",
  "ستظهر رسائل العميلات هنا عند وصولها من نموذج التواصل.": "Client messages will appear here when they arrive from the contact form.",
  "حفظ بيانات التواصل": "Save contact details",
  "احفظ بعد تعديل البيانات حتى تنعكس على الصفحات التي تعتمد على مستند settings/public.": "Save after editing so changes appear on pages that use the settings/public document.",
  "الحساب الحالي يملك صلاحية العرض فقط ولا يستطيع تعديل بيانات التواصل.": "The current account has view-only access and cannot edit contact details.",
  "تحتاج صلاحية settings.content.manage": "Requires settings.content.manage permission",
  "جاري الحفظ…": "Saving…",
  "تم حفظ بيانات التواصل": "Contact details saved",
  "تعذر حفظ بيانات التواصل": "Could not save contact details"
  "السبت": "Saturday",
  "الأحد": "Sunday",
  "الإثنين": "Monday",
  "الثلاثاء": "Tuesday",
  "الأربعاء": "Wednesday",
  "الخميس": "Thursday",
  "الجمعة": "Friday",
  "5 دقائق": "5 minutes",
  "10 دقائق": "10 minutes",
  "15 دقيقة": "15 minutes",
  "30 دقيقة": "30 minutes",
  "20 دقيقة": "20 minutes",
  "بدون بفر": "No buffer",
  "مفتوح بساعات مخصصة": "Open with custom hours",
  "مغلق بالكامل": "Fully closed",
  "عام": "General",
  "مواعيد الدوام": "Business hours",
  "وضع الموسم": "Season mode",
  "الاستثناءات": "Exceptions",
  "من": "From",
  "إلى": "To",
  "تعذر": "Could not",
  "فشل": "Failed",
  "أيام العمل": "Working days",
  "الدوام الأسبوعي المفتوح": "Open weekly schedule",
  "الفترات الخاصة بتاريخ محدد": "Date-specific periods",
  "خطوة الحجز": "Booking interval",
  "دقة فتح المواعيد": "Appointment slot granularity",
  "التتابع": "Sequential booking",
  "مفعّل": "Enabled",
  "متوقف": "Disabled",
  "منع الفراغات بين الحجوزات": "Prevent gaps between bookings",
  "❌ حددي من/إلى تاريخ للاستثناء": "❌ Select a from/to date for the exception",
  "❌ تاريخ البداية يجب أن يكون قبل أو يساوي تاريخ النهاية": "❌ The start date must be before or equal to the end date",
  "❌ وقت البداية والنهاية لا يمكن أن يكونا متطابقين": "❌ Start and end times cannot be identical",
  "❌ حددي من/إلى تاريخ للاستثناء أو اضغطي تنظيف": "❌ Select a from/to date for the exception or clear the form",
  "✅ تم حفظ الإعدادات": "✅ Settings saved",
  "البداية والنهاية لا يمكن أن تكونا نفس الوقت": "start and end times cannot be the same",
  "❌ فشل الحفظ: الصلاحيات (Rules) تمنع الكتابة": "❌ Save failed: security rules prevent writing",
  "❌ تعذر حفظ الإعدادات": "❌ Could not save settings",
  "تم نسخ وقت": "Copied the time for",
  "إلى بقية الأيام": "to the remaining days",
  "إعدادات الحجوزات الحالية متاحة لحسابات Owner/Admin فقط.": "Booking settings are available to Owner/Admin accounts only.",
  "الحجز متوقف": "Booking disabled",
  "الحجز متاح": "Booking available",
  "ملخص إعدادات الحجوزات": "Booking settings summary",
  "أقسام إعدادات الحجوزات": "Booking settings sections",
  "الحجز متوقف مؤقتًا": "Booking temporarily disabled",
  "أيام مفتوحة": "open days",
  "التتابع مفعل": "Sequential booking enabled",
  "ضبط الهدر والتتابع": "Gap and sequence controls",
  "فترة محفوظة": "saved periods",
  "إعدادات الحجوزات": "Booking settings",
  "جدولة وتشغيل الحجوزات": "Booking scheduling and operations",
  "إدارة إتاحة الحجز، دقة المواعيد، ساعات العمل، وضع الموسم، والاستثناءات من مساحة واحدة.": "Manage booking availability, appointment granularity, business hours, season mode and exceptions from one workspace.",
  "تحكم سريع في إتاحة الحجز ورسالة الصيانة التي تظهر للعميلات.": "Quick controls for booking availability and the maintenance message shown to clients.",
  "اضبط دقة المواعيد، الرسوم، وأيام العمل الأسبوعية من مكان واحد.": "Configure appointment granularity, fees and weekly working days in one place.",
  "أدوات تقلل الفراغات وتساعد على ترتيب اليوم وقت الضغط والمواسم.": "Tools that reduce gaps and help organize the day during busy periods and seasons.",
  "فترات خاصة بتاريخ محدد لإغلاق يوم أو تغيير ساعات العمل مؤقتًا.": "Date-specific periods for closing a day or temporarily changing business hours.",
  "تحكم إداري": "Management control",
  "وضع الصيانة": "Maintenance mode",
  "إيقاف الحجز مؤقتًا للعميلات مع إبقاء الإدارة متاحة.": "Temporarily disable client booking while keeping management access available.",
  "مفتوح": "Open",
  "رسالة الصيانة التي تظهر للعميلات": "Maintenance message shown to clients",
  "مثال: الحجز متوقف مؤقتًا للصيانة، نعود قريبًا": "Example: booking is temporarily unavailable for maintenance. We will be back soon.",
  "تُحفظ هذه القيمة داخل AppSettings وتظهر عند إيقاف الحجز.": "This value is stored in AppSettings and shown when booking is disabled.",
  "خطوة الوقت": "Time step",
  "5/10 دقائق لدقة أعلى، و30 دقيقة لجدولة أبسط.": "Use 5/10 minutes for finer precision, or 30 minutes for simpler scheduling.",
  "البفر بعد كل حجز": "Buffer after each booking",
  "المسافة الزمنية الإضافية بعد نهاية الموعد.": "Additional time added after each appointment.",
  "رسوم أدوات البديكير/المناكير": "Manicure/pedicure tools fee",
  "ريال": "SAR",
  "تظهر فقط إذا اختارت العميلة الأدوات من المشغل.": "Shown only if the client selects salon-provided tools.",
  "إدارة الدوام الأسبوعي": "Weekly schedule management",
  "اختاري يومًا للمراجعة أو انسخي أوقاته إلى بقية الأسبوع.": "Select a day to review or copy its hours to the rest of the week.",
  "نسخ وقت اليوم لبقية الأيام": "Copy today's hours to other days",
  "مغلق": "Closed",
  "اليوم مغلق": "Closed today",
  "يتجاوز منتصف الليل": "Crosses midnight",
  "يتم الحفظ في booking.businessHours مع slotStepMin وbufferMin وmaniPediToolsFee، وصفحة الحجز تقرأها من AppSettings.": "Saved in booking.businessHours with slotStepMin, bufferMin and maniPediToolsFee; the booking page reads them from AppSettings.",
  "ترتيب اليوم تلقائيًا": "Auto-arrange the day",
  "تفعيل ترتيب وقت الحجز خلال فترة الموسم المحددة.": "Enable booking-time arrangement during the selected season period.",
  "إجبار الحجز المتتابع": "Force sequential booking",
  "منع الفراغات بين المواعيد داخل نفس اليوم.": "Prevent gaps between appointments on the same day.",
  "من تاريخ": "From date",
  "إلى تاريخ": "To date",
  "تُحفظ الفترة داخل booking.seasonFill، بينما تنفيذ ترتيب اليوم يبقى في Booking.tsx وtimeSlots.ts كما هو.": "The period is stored in booking.seasonFill, while day-arrangement execution remains in Booking.tsx and timeSlots.ts.",
  "وضع الفترة": "Period mode",
  "وقت البداية": "Start time",
  "وقت النهاية": "End time",
  "سبب داخلي (اختياري)": "Internal reason (optional)",
  "مثال: دوام رمضان / جدول حملة صبغات": "Example: Ramadan hours / color campaign schedule",
  "أيام مستهدفة داخل الفترة": "Target days within the period",
  "اختياري؛ اتركيها فارغة لتطبيق الاستثناء على كل الأيام.": "Optional; leave blank to apply the exception to all days.",
  "أيام مغلقة داخل الفترة": "Closed days within the period",
  "اختياري؛ تستخدم لإغلاق أيام محددة داخل نفس الفترة.": "Optional; use this to close specific days within the same period.",
  "حفظ التعديل": "Save changes",
  "إضافة استثناء": "Add exception",
  "إلغاء التعديل": "Cancel edit",
  "تنظيف": "Clear",
  "الاستثناءات المحفوظة": "Saved exceptions",
  "الأولوية: الإغلاق الخاص بالتاريخ، ثم الاستثناء، ثم الدوام الأسبوعي.": "Priority: date-specific closure, then exception, then weekly schedule.",
  "فترة": "periods",
  "لا توجد استثناءات": "No exceptions",
  "أضف فترة خاصة إذا احتجت تغيير الدوام أو إغلاق أيام بتاريخ محدد.": "Add a special period when you need to change business hours or close specific dates.",
  "ساعات": "Hours",
  "إغلاق": "Closure",
  "ساعات مخصصة": "Custom hours",
  "الميلادي": "Gregorian",
  "الهجري": "Hijri",
  "الأيام المستهدفة": "Target days",
  "الأيام المغلقة": "Closed days",
  "الكل": "All",
  "لا يوجد": "None",
  "السبب": "Reason",
  "تعديل": "Edit",
  "حذف": "Delete",
  "حفظ إعدادات الحجوزات": "Save booking settings",
  "احفظ بعد التعديل حتى تنعكس القيم في صفحة الحجز.": "Save after editing so the values are reflected on the booking page.",
};

export function settingsText(language: DashboardLanguage, arabic: string): string {
  if (language === "ar") return arabic;
  return settingsEnglish[arabic] ?? dashboardText(language, arabic);
}
