import { dashboardText, type DashboardLanguage } from "./dashboardLanguage";

export type { DashboardLanguage } from "./dashboardLanguage";

const expensesEnglish: Record<string, string> = {
  "الإدارة المالية": "Financial management",
  "المصروفات": "Expenses",
  "إدارة المصروفات التشغيلية والرواتب، ومراجعة النواقص والتقارير من مساحة واحدة.": "Manage operating expenses and payroll, and review missing data and reports from one workspace.",
  "إجراءات صفحة المصروفات": "Expenses page actions",
  "إضافة مصروف": "Add expense",
  "تحديث": "Refresh",
  "تحميل PDF": "Download PDF",
  "Excel منسّق": "Formatted Excel",
  "ترحيل القديم": "Migrate legacy data",
  "ملخص المصروفات": "Expenses summary",
  "إجمالي المصروفات": "Total expenses",
  "مصروفات الرواتب": "Payroll expenses",
  "المصروفات التشغيلية": "Operating expenses",
  "تحتاج ملاحظة": "Missing notes",
  "ضمن الفترة الحالية": "Within the current period",
  "سجل محسوب تلقائيًا": "auto-calculated records",
  "سجل يدوي": "manual records",
  "الفترة المرجعية": "Reference period",
  "الفترة المعروضة": "Displayed period",
  "الدورة المرجعية": "Reference cycle",
  "التصنيفات الظاهرة": "Visible categories",
  "إغلاق الرواتب": "Payroll close",
  "يوم": "Day",
  "من كل شهر": "of each month",
  "الفلاتر": "Filters",
  "سجل المصروفات": "Expense records",
  "غيّر الفترة والتصنيف وطريقة الدفع أو ابحث داخل السجلات.": "Change the period, category or payment method, or search within the records.",
  "عرض الكل": "Show all",
  "بدون ملاحظات": "Missing notes",
  "تصفير الفلاتر": "Clear filters",
  "وضع العرض": "View mode",
  "الشهر المرجعي": "Reference month",
  "التصنيف": "Category",
  "طريقة الدفع": "Payment method",
  "البحث": "Search",
  "الوصف، الموظفة، المصدر أو الملاحظات": "Description, staff member, source or notes",
  "تفاصيل المصروفات": "Expense details",
  "سجل مطابق للفلاتر الحالية": "records match the current filters",
  "لا توجد مصروفات مطابقة": "No matching expenses",
  "غيّر الفلاتر أو أضف مصروفًا جديدًا لبدء عرض البيانات.": "Change the filters or add a new expense to start showing data.",
  "التاريخ": "Date",
  "النوع": "Type",
  "الوصف": "Description",
  "الموظفة": "Staff member",
  "الدفع": "Payment",
  "المبلغ": "Amount",
  "المصدر": "Source",
  "ملاحظات": "Notes",
  "إجراء": "Action",
  "بدون ملاحظة": "No note",
  "عرض التفاصيل": "View details",
  "التفاصيل": "Details",
  "تعديل": "Edit",
  "حذف": "Delete",
  "سجّل بيانات المصروف ليظهر مباشرة في السجل والتقارير.": "Enter the expense details so it appears immediately in records and reports.",
  "جارٍ الحفظ...": "Saving...",
  "حفظ المصروف": "Save expense",
  "إلغاء": "Cancel",
  "اسم المصروف": "Expense name",
  "مثال: شراء منتجات": "Example: product purchase",
  "المبلغ (ر.س)": "Amount (SAR)",
  "أي تفاصيل إضافية": "Any additional details",
  "إضافة تصنيف سريع": "Quick add category",
  "سيُحفظ ضمن إعدادات التصنيفات المالية.": "It will be saved in the financial category settings.",
  "مثال: تأمين": "Example: insurance",
  "إضافة": "Add",
  "تعديل المصروف": "Edit expense",
  "عدّل بيانات السجل اليدوي ثم احفظ التغييرات.": "Edit the manual record details, then save the changes.",
  "تعديل السجل": "Edit record",
  "حفظ التعديل": "Save changes",
  "تأكيد الإجراء": "Confirm action",
  "تأكيد": "Confirm",
  "تراجع": "Cancel",
  "تعذر تنفيذ العملية": "Could not complete the operation",
  "تم تنفيذ العملية": "Operation completed",
  "حسنًا": "OK",
  "تفاصيل المصروف": "Expense details",
  "عرض سريع لبيانات السجل ومصدره.": "Quick view of the record details and its source.",
  "إغلاق": "Close",
  "المبلغ المسجل": "Recorded amount",
  "دورة الرواتب": "Payroll cycle",
  "لا توجد ملاحظات": "No notes",
  "غير مصرح": "Access denied",
  "هذه الصفحة خاصة بالمالك والإدارة فقط.": "This page is limited to the owner and management.",
  "شهر تقويمي (1-آخر الشهر)": "Calendar month (1-end of month)",
  "شهر تقويمي": "Calendar month",
  "حسب الفترة": "By period",
  "راتب": "Salary",
  "أوفر تايم": "Overtime",
  "تشغيلي": "Operating",
  "رواتب": "Payroll",
  "تشغيل": "Operations",
  "كاش": "Cash",
  "شبكة": "Card",
  "تحويل": "Transfer",
  "مختلط": "Mixed",
  "أخرى": "Other",
  "الكل": "All",
  "غير محدد": "Unspecified",
  "الإدارة": "Management",
  "عدد المصروفات": "Expense count",
  "الرواتب": "Payroll",
  "الأوفر تايم": "Overtime",
  "التشغيلية": "Operating",
  "أضيف بواسطة": "Added by",
  "تقرير المصروفات": "Expenses report",
  "المصروفات التشغيلية والرواتب المطابقة للفلاتر الحالية": "Operating expenses and payroll matching the current filters",
  "لا توجد مصروفات مطابقة للفلاتر الحالية.": "No expenses match the current filters.",
  "لوحة المصروفات": "Expenses dashboard",
  "⚠️ لا توجد صلاحيات كافية. تأكد من صلاحيات Core D1 وتسجيل الدخول.": "⚠️ Insufficient permissions. Check Core D1 permissions and sign-in status.",
  "⚠️ المسار غير موجود. تأكد من اسم الـ collection ومسار السيرفس.": "⚠️ Endpoint not found. Check the collection name and service path.",
  "⚠️ الاستعلام يحتاج Index.": "⚠️ This query requires an index.",
  "تعذر تنفيذ العملية. راجع Console لمعرفة السبب.": "Could not complete the operation. Check the console for details.",
  "تعذر تحديث بيانات الرواتب من المصدر التشغيلي. قد تكون أرقام المصروفات المعروضة غير مكتملة أو تعتمد على آخر بيانات رواتب تم تحميلها بنجاح.": "Could not refresh payroll data from the operational source. Displayed expense figures may be incomplete or may rely on the last successfully loaded payroll data.",
  "لا يوجد مستخدم مسجل دخول. سجّل دخول الإدارة ثم جرّب.": "No signed-in user. Sign in to the management account and try again.",
  "اكتب اسم المصروف": "Enter the expense name",
  "اختر التصنيف": "Select a category",
  "اختر التاريخ": "Select a date",
  "اكتب مبلغ صحيح": "Enter a valid amount",
  "تمت إضافة المصروف بنجاح": "Expense added successfully",
  "هذا السجل محسوب تلقائيًا (راتب/أوفر تايم) ولا يمكن حذفه يدويًا.": "This record is calculated automatically (salary/overtime) and cannot be deleted manually.",
  "تأكيد الحذف": "Confirm deletion",
  "متأكد تبغى حذف المصروف؟": "Are you sure you want to delete this expense?",
  "هذا السجل محسوب تلقائيًا (راتب/أوفر تايم) ولا يمكن تعديله يدويًا.": "This record is calculated automatically (salary/overtime) and cannot be edited manually.",
  "تم التعديل ✅": "Changes saved ✅",
  "تم ترحيل المصروفات مسبقًا ✅": "Expenses were already migrated ✅",
  "لا توجد مصروفات قديمة في LocalStorage ✅": "No legacy expenses found in LocalStorage ✅",
  "ترحيل المصروفات": "Migrate expenses",
  "ملاحظة: العملية مرة واحدة ولن تتكرر.": "Note: this is a one-time operation and will not repeat.",
  "كل السجلات موجودة بالفعل في Firestore ✅": "All records already exist in Firestore ✅",
  "تعذر التصدير لأن بيانات الرواتب غير مكتملة. أعد تحميل الصفحة بعد عودة مصدر الرواتب.": "Export is unavailable because payroll data is incomplete. Reload the page after the payroll source is available again.",
  "ما فيه بيانات للتصدير": "There is no data to export",
  "تمت إضافة التصنيف ✅ (راح ننقله للإعدادات لاحقًا)": "Category added ✅ (it will be moved to settings later)",
  "الفترة": "Period",
  "رمز التقرير": "Report code",
  "تاريخ التصدير": "Export date",
  "أنشأه": "Generated by",
  "الفلاتر المطبقة": "Applied filters",
  "بدون فلاتر إضافية": "No additional filters",
  "ملخص التقرير": "Report summary",
  "كل الفترات": "All periods",
  "من": "From",
  "إلى": "To",
  "النظام": "System"
};

export function expensesText(language: DashboardLanguage, arabic: string): string {
  if (language === "ar") return arabic;
  return expensesEnglish[arabic] ?? dashboardText(language, arabic);
}
