import { dashboardText, type DashboardLanguage } from "./dashboardLanguage";

export type { DashboardLanguage } from "./dashboardLanguage";

const bookingEnglish: Record<string, string> = {
  "جاري تحميل الحجوزات...": "Loading bookings...",
  "يتم تجهيز قائمة الحجوزات والحالات المالية.": "Preparing bookings and payment information.",
  "تشغيل الحجوزات": "Booking operations",
  "مركز إدارة الحجوزات": "Booking management",
  "واجهة تشغيل موحدة لمتابعة الحجوزات الجديدة، المواعيد، التحصيل، والإجراءات اليومية.": "Manage new bookings, appointments, payments and daily tasks in one place.",
  "إنشاء حجز جديد": "Create booking",
  "تحديث": "Refresh",
  "ملخص عمليات الحجوزات": "Booking operations summary",
  "المؤكد والمكتمل اليوم": "Confirmed and completed today",
  "المحصّل اليوم": "Collected today",
  "حسب الحجوزات المحمّلة": "Based on loaded bookings",
  "تحتاج متابعة": "Needs attention",
  "حجوزات قديمة أو غير مغلقة": "Old or open bookings",
  "إجمالي المتبقي": "Total outstanding",
  "على الحجوزات المفتوحة فقط": "Open bookings only",
  "الوارد الجديد": "New arrivals",
  "الحجوزات الجديدة": "New bookings",
  "حجوزات اليوم والمواعيد القادمة، مرتبة حسب أقرب موعد.": "Today's and upcoming bookings, sorted by appointment time.",
  "عميلة غير معروفة": "Unknown client",
  "بدون موظفة": "No staff member",
  "لا توجد حجوزات قادمة": "No upcoming bookings",
  "ستظهر هنا حجوزات اليوم والمواعيد المستقبلية مباشرة.": "Today's and upcoming bookings will appear here.",
  "عرض الأحدث في القائمة": "Show newest in list",
  "تحديد الكل كمُطّلع عليه": "Mark all as seen",
  "مركز المتابعة": "Attention center",
  "حجوزات تحتاج إجراء": "Bookings needing action",
  "الحجوزات المتأخرة أو التي بقيت بحالة مفتوحة.": "Past bookings that are still open.",
  "قديم بالانتظار": "Old pending",
  "قديم ومؤكد": "Old confirmed",
  "عربون غير مغلق": "Open deposit",
  "بدون دفع": "Unpaid",
  "لا توجد حجوزات متأخرة": "No overdue bookings",
  "البحث والفلاتر": "Search and filters",
  "مساحة العمل": "Workspace",
  "البحث وإدارة القائمة": "Search and manage bookings",
  "نتيجة مطابقة": "Matching results",
  "بحث الحجوزات": "Search bookings",
  "ابحثي بالاسم، الجوال، رقم الحجز، الخدمة أو الموظفة...": "Search by name, phone, booking number, service or staff...",
  "مسح البحث": "Clear search",
  "الفترة": "Period",
  "كل الحجوزات": "All bookings",
  "اليوم": "Today",
  "أمس": "Yesterday",
  "هذا الأسبوع": "This week",
  "هذا الشهر": "This month",
  "الشهر الماضي": "Last month",
  "نطاق مخصص": "Custom range",
  "اختاري الفترة": "Choose period",
  "فلاتر متقدمة": "Advanced filters",
  "مسح الفلاتر": "Clear filters",
  "فلترة حالة الحجز": "Filter booking status",
  "الكل": "All",
  "بالانتظار": "Pending",
  "من تاريخ": "From date",
  "إلى تاريخ": "To date",
  "اختاري التاريخ": "Choose date",
  "مسح": "Clear",
  "مسح التاريخ": "Clear date",
  "اختيار": "Choose",
  "الشهر السابق": "Previous month",
  "الشهر التالي": "Next month",
  "استثناء حالة": "Exclude status",
  "بدون استثناء": "No exclusion",
  "استثناء: ": "Exclude: ",
  "حالة السداد": "Payment status",
  "مدفوع بالكامل": "Paid in full",
  "مدفوع جزئيًا": "Partially paid",
  "غير مدفوع": "Unpaid",
  "كل حالات السداد": "All payment statuses",
  "طريقة الدفع": "Payment method",
  "كل الطرق": "All methods",
  "كل طرق الدفع": "All payment methods",
  "كاش": "Cash",
  "شبكة": "Card",
  "تحويل": "Transfer",
  "مختلط": "Mixed",
  "دفع مختلط": "Mixed payment",
  "أخرى": "Other",
  "الموظفة": "Staff member",
  "كل الموظفات": "All staff",
  "الخدمة": "Service",
  "كل الخدمات": "All services",
  "مصدر الحجز": "Booking source",
  "كل المصادر": "All sources",
  "موقع العميلات": "Client website",
  "الداشبورد": "Dashboard",
  "الحجز الداخلي": "Internal booking",
  "غير محدد": "Unspecified",
  "الترتيب": "Sort order",
  "الأحدث أولًا": "Newest first",
  "الأقدم أولًا": "Oldest first",
  "اختاري الترتيب": "Choose sort order",
  "الحجوزات القديمة": "Older bookings",
  "بدون فلتر": "No filter",
  "الأقدم من اليوم": "Before today",
  "الأقدم من 7 أيام": "Older than 7 days",
  "الأقدم من 30 يومًا": "Older than 30 days",
  "قديم من": "Older from",
  "قديم إلى": "Older until",
  "المحمّل": "Loaded",
  "المطابق": "Matching",
  "المعروض": "Shown",
  "الصفحة": "Page",
  "المتبقي ضمن النتائج": "Outstanding in results",
  "حجز محدد": "Bookings selected",
  "ضمن النتائج الحالية": "In current results",
  "إلغاء تحديد الصفحة": "Deselect page",
  "تحديد الصفحة": "Select page",
  "تحديد كل النتائج": "Select all results",
  "إلغاء التحديد": "Clear selection",
  "الحجوزات العادية": "Regular bookings",
  "الحجوزات الداخلية": "Internal bookings",
  "تظهر هنا الحجوزات العادية فقط، ويظهر الحجز الداخلي المستقبلي قبل الدفع مؤقتًا في هذا القسم.": "Regular bookings appear here. Future internal bookings appear here temporarily until payment.",
  "تظهر هنا جميع الحجوزات الداخلية بشكل مستقل، ولا يبقى أي حجز داخلي داخل القسم العادي بعد الدفع أو التأكيد.": "Internal bookings appear separately after payment or confirmation.",
  "حجز": "booking",
  "حجوزات داخلية": "internal bookings",
  "حجوزات عادية": "regular bookings",
  "منها": "Including",
  "حجز داخلي مستقبلي قبل الدفع": "future internal booking before payment",
  "تحديد حجوزات قسم": "Select bookings in section",
  "تحديد الحجز": "Select booking",
  "الحجز": "Booking",
  "العميلة": "Client",
  "الخدمة والموظفة": "Service and staff",
  "الموعد": "Appointment",
  "التحصيل": "Payment",
  "الإجراءات": "Actions",
  "حجز مجمّع": "Grouped booking",
  "المرجع": "Reference",
  "خدمات": "services",
  "فتح تفاصيل الحجز": "Open booking details",
  "جديد": "New",
  "آخر تحديث": "Last updated",
  "غير محددة": "Unassigned",
  "الإجمالي": "Total",
  "مدفوع": "Paid",
  "متبقي": "Remaining",
  "بدون سعر": "No price",
  "بانتظار السداد": "Awaiting payment",
  "لا يوجد سعر محدد": "No price specified",
  "لا يوجد مبلغ محدد": "No amount specified",
  "غير مدفوع (بانتظار السداد)": "Unpaid (awaiting payment)",
  "عربون (دفع جزئي)": "Deposit (partial payment)",
  "حجز داخلي": "Internal booking",
  "دفع جزئي": "Partially paid",
  "فتح": "Open",
  "تجهيز...": "Preparing...",
  "طباعة": "Print",
  "طباعة الفاتورة": "Print invoice",
  "تعديل": "Edit",
  "الاسترجاع": "Refund",
  "استرجاع": "Refund",
  "الاسترجاع مسجل": "Refund recorded",
  "تغيير حالة الحجز": "Change booking status",
  "إزالة الحجز من القائمة مع حفظ السجلات المالية": "Remove booking while keeping financial records",
  "حذف": "Delete",
  "حذف الحجز": "Delete booking",
  "تأكيد": "Confirm",
  "إلغاء": "Cancel",
  "تحديد هذا الحجز": "Select this booking",
  "رقم الحجز": "Booking number",
  "الجوال": "Phone",
  "التاريخ": "Date",
  "الحالة": "Status",
  "نوع الحجز": "Booking type",
  "الدفع": "Payment",
  "تفاصيل": "Details",
  "جاري تجهيز الفاتورة...": "Preparing invoice...",
  "لا توجد نتائج مطابقة": "No matching results",
  "لا توجد": "No",
  "حالياً": "at the moment",
  "غيّر البحث أو الفلاتر الحالية لعرض حجوزات هذا القسم.": "Change the search or filters to see bookings in this section.",
  "عند إضافة حجوزات لهذا القسم ستظهر هنا مباشرة.": "Bookings added to this section will appear here.",
  "إعادة ضبط الفلاتر": "Reset filters",
  "التنقل بين صفحات الحجوزات": "Booking pages",
  "عرض": "Showing",
  "من": "of",
  "لكل صفحة": "Per page",
  "عدد الحجوزات في الصفحة": "Bookings per page",
  "الأولى": "First",
  "السابق": "Previous",
  "التالي": "Next",
  "الأخيرة": "Last",
  "تفاصيل الحجز": "Booking details",
  "بيانات الحجز": "Booking information",
  "نفس البيانات الحالية مع ترتيب أوضح ومسافات أنظف بين البطاقات.": "Current booking information, organized for easier reading.",
  "تم إنشاء الحجز": "Booking created",
  "اسم الزبون": "Client name",
  "رقم الهاتف": "Phone number",
  "نقاط العميلة": "Client points",
  "نقطة": "points",
  "ولاء العميلة": "Client loyalty",
  "المصدر": "Source",
  "الوقت": "Time",
  "مدة الخدمة": "Service duration",
  "دقيقة": "minutes",
  "السعر الإجمالي": "Total price",
  "نوع الدفع": "Payment type",
  "سجل الحجز": "Booking history",
  "تسلسل الأحداث للحجز من الأحدث إلى الأقدم.": "Booking events, newest first.",
  "جاري تحميل سجل الحجز...": "Loading booking history...",
  "بواسطة": "By",
  "تفاصيل العملية": "Action details",
  "لا توجد أحداث مسجلة لهذا الحجز حتى الآن.": "No events recorded for this booking yet.",
  "الخدمات داخل الحجز": "Services in booking",
  "المدة": "Duration",
  "السعر": "Price",
  "ملاحظات سابقة على العميلة": "Previous client notes",
  "لا توجد ملاحظات سابقة لهذه العميلة.": "No previous notes for this client.",
  "ملاحظات الإدارة (خاصة)": "Private management notes",
  "أضف ملاحظات هنا...": "Add notes here...",
  "حفظ الملاحظة": "Save note",
  "تم الحفظ": "Saved",
  "إدارة الاسترجاع": "Manage refund",
  "تسجيل استرجاع": "Record refund",
  "تعديل الحجز": "Edit booking",
  "تأكيد الإجراء الجماعي للحجوزات": "Confirm bulk booking update",
  "تأكيد الإجراء الجماعي": "Confirm bulk action",
  "عدد الحجوزات التي ستتغير": "Bookings to update",
  "الحالة الحالية": "Current status",
  "الحالة الجديدة": "New status",
  "التاريخ/الفلاتر المستخدمة": "Date / active filters",
  "بدون فلاتر": "No filters",
  "تأكيد التحديث الجماعي": "Confirm bulk update",
  "جاري التحديث...": "Updating...",
  "قيمة الحجز": "Booking value",
  "حالة الاسترجاع: تم الاسترجاع": "Refund status: refunded",
  "حالة الاسترجاع: غير مسترجع": "Refund status: no refund",
  "المبلغ": "Amount",
  "الطريقة": "Method",
  "لا يوجد استرجاع مسجل لهذا الحجز حالياً.": "There is no refund recorded for this booking.",
  "مبلغ الاسترجاع": "Refund amount",
  "طريقة الاسترجاع": "Refund method",
  "تاريخ الاسترجاع": "Refund date",
  "سبب الاسترجاع": "Refund reason",
  "تفاصيل إضافية": "Additional details",
  "مثال: إلغاء قبل الموعد": "Example: cancelled before appointment",
  "أي تفاصيل داخلية للاسترجاع": "Any internal refund details",
  "يمكن التراجع عن الاسترجاع من هنا": "You can reverse the refund here",
  "إلغاء الاسترجاع": "Reverse refund",
  "جاري الإلغاء...": "Cancelling...",
  "حفظ الاسترجاع": "Save refund",
  "جاري الحفظ...": "Saving...",
  "تأكيد الحجز مع الدفع": "Confirm booking and payment",
  "تأكيد الحجز": "Confirm booking",
  "إجمالي الحجز": "Booking total",
  "نوع الدفع وقت التأكيد": "Payment type on confirmation",
  "دفع كامل": "Paid in full",
  "عربون": "Deposit",
  "اختاري نوع الدفع": "Choose payment type",
  "اختاري طريقة الدفع": "Choose payment method",
  "مبلغ الكاش": "Cash amount",
  "مبلغ الشبكة": "Card amount",
  "المجموع": "Total",
  "مبلغ العربون": "Deposit amount",
  "مثال: 150": "Example: 150",
  "جاري التأكيد...": "Confirming...",
  "رجوع": "Back",
  "تأكيد إلغاء الحجز": "Confirm booking cancellation",
  "هل تريد بالفعل إلغاء هذا الحجز؟": "Are you sure you want to cancel this booking?",
  "تأكيد الإلغاء": "Confirm cancellation",
  "تعذر تسجيل الاسترجاع.": "Could not record the refund.",
  "تعذر إلغاء الاسترجاع.": "Could not reverse the refund.",
  "أدخل مبلغ استرجاع صحيح.": "Enter a valid refund amount.",
  "مبلغ الاسترجاع لا يمكن أن يتجاوز قيمة الحجز.": "Refund amount cannot exceed booking value.",
  "سبب الاسترجاع مطلوب.": "Refund reason is required.",
  "أدخلي كلمة مرور الحساب": "Enter your account password",
  "إجراء حساس": "Sensitive action",
  "الإجراء المطلوب": "Requested action",
  "التحقق بكلمة مرور الحساب": "Verify account password",
  "تأكيد كلمة مرور الحساب": "Confirm account password",
  "جاري التحقق...": "Verifying...",
  "سيتم التحقق من كلمة مرور الحساب المسجل حاليًا قبل تنفيذ الإجراء.": "Your current account password will be verified before this action.",
  "سيختفي الحجز من صفحة الحجوزات، مع الاحتفاظ بالفاتورة والمدفوعات والسجل المالي للمراجعة.": "The booking will be removed from the bookings page. Its invoice, payments and financial history will remain available for review.",
  "كلمة مرور حسابك الحالي": "Your current account password",
  "متابعة": "Continue",
  "أدخلي كلمة مرور الحساب الحالي.": "Enter your current account password.",
  "كلمة المرور غير صحيحة.": "Incorrect password.",
  "تم إيقاف المحاولات مؤقتًا بسبب كثرة المحاولات. انتظري قليلًا ثم أعيدي المحاولة.": "Too many attempts. Wait a moment and try again.",
  "انتهت صلاحية التحقق. سجّلي الخروج ثم ادخلي مرة أخرى.": "Verification expired. Sign out and sign in again.",
  "تعذر التحقق من كلمة المرور.": "Could not verify the password.",
  "المتبقي": "Remaining",
  "المدفوع": "Paid",
  "تنبيه: هذا الإجراء سيؤثر في عدة حجوزات محددة فقط. لن يتم تعديل أي حجز غير محدد.": "This action only updates the selected bookings. Other bookings will not change.",
  "خدمة": "Service",
  "لا يوجد دفع": "No payment",
  "مثال: 120": "Example: 120",
  "بحث": "Search",
  "كل الحالات": "All statuses",
  "حجوزات قديمة ما زالت بالانتظار": "Older bookings still pending",
  "مدفوع جزئيا": "Partially paid",
};

export function bookingsText(language: DashboardLanguage, arabic: string): string {
  if (language === "ar") return arabic;
  if (arabic.endsWith(":")) return `${bookingsText(language, arabic.slice(0, -1))}:`;
  return bookingEnglish[arabic] ?? dashboardText(language, arabic);
}
