import { dashboardText, type DashboardLanguage } from "./dashboardLanguage";

export type { DashboardLanguage } from "./dashboardLanguage";

const offersEnglish: Record<string, string> = {
  "مسودة": "Draft",
  "مجدول": "Scheduled",
  "نشط": "Active",
  "منتهي": "Expired",
  "موقوف": "Disabled",
  "محذوف": "Deleted",
  "مفعّل": "Enabled",
  "مفعّلة": "Enabled",
  "موقوفة": "Disabled",
  "منشور": "Published",
  "مخفي": "Hidden",
  "غير معروض للبيع": "Not for sale",
  "متاحة للبيع": "Available for sale",
  "غير معروضة": "Not for sale",
  "قيمة الخصم": "Discount value",
  "إجمالي مرات الاستخدام": "Total usage limit",
  "عدد مرات الاستخدام الحالية": "Current usage count",
  "الحد الأدنى للطلب": "Minimum order",
  "الحد الأعلى للخصم": "Maximum discount",
  "الحد لكل عميلة": "Limit per client",
  "السعر قبل الخصم": "Price before discount",
  "السعر بعد الخصم": "Price after discount",
  "ترتيب الظهور": "Display order",
  "يجب أن تكون قيمته عددًا صحيحًا ضمن النطاق المسموح.": "Value must be an integer within the allowed range.",
  "القيمة المدخلة غير صحيحة.": "The entered value is invalid.",
  "أحد الحقول العددية غير صحيح. راجع حدود الاستخدام والأسعار وترتيب الظهور.": "One of the numeric fields is invalid. Review usage limits, prices and display order.",
  "قيمة الخصم غير صحيحة. استخدم رقمًا موجبًا وبحد أقصى منزلتين عشريتين.": "The discount value is invalid. Use a positive number with at most two decimal places.",
  "تعذر حفظ العرض في قاعدة البيانات.": "Could not save the offer to the database.",
  "قسم الشعر": "Hair section",
  "العناية بالشعر": "Hair care",
  "قسم الصبغات": "Color section",
  "الصبغات والمعالجات": "Color and treatments",
  "قسم المكياج": "Makeup section",
  "قسم الأظافر": "Nails section",
  "قسم الشمع": "Waxing section",
  "استشارة": "Consultation",
  "استشوار": "Blow-dry",
  "الخدمات": "Services",
  "العناية بالأظافر": "Nail care",
  "المكياج": "Makeup",
  "قسم عام": "General section",
  "غير محدد": "Unspecified",
  "عام": "General",
  "احجزي الآن": "Book now",
  "عنوان العرض والكود مكتملان": "Offer title and code are complete",
  "قيمة الخصم صحيحة": "Discount value is valid",
  "فترة العرض صحيحة": "Offer period is valid",
  "نطاق التطبيق محدد": "Application scope is selected",
  "الاستهداف جاهز": "Targeting is ready",
  "تعذر تحميل العروض أو الباقات من Core API.": "Could not load offers or packages from the Core API.",
  "تم اختيار صورة": "Image selected",
  "اكتب عنوان العرض": "Enter the offer title",
  "اكتب الكود أو اضغط توليد": "Enter a code or generate one",
  "قيمة الخصم لازم تكون رقمًا أكبر من صفر": "Discount value must be greater than zero",
  "قيمة الخصم تقبل منزلتين عشريتين كحد أقصى": "Discount value supports at most two decimal places",
  "النسبة المئوية لا تتجاوز 100%": "Percentage cannot exceed 100%",
  "تاريخ البداية لازم يكون قبل النهاية": "Start date must be before end date",
  "أسعار العرض لا يمكن أن تكون سالبة": "Offer prices cannot be negative",
  "السعر بعد الخصم يجب ألا يتجاوز السعر السابق": "Price after discount cannot exceed the original price",
  "أدخلي معرف عميلة واحدة على الأقل للاستهداف المحدد": "Enter at least one client ID for specific targeting",
  "اختر خدمة واحدة على الأقل أو اجعل العرض على جميع الخدمات": "Select at least one service or apply the offer to all services",
  "اختر تصنيفًا واحدًا على الأقل أو غيّر نطاق العرض": "Select at least one category or change the offer scope",
  "حدود الاستخدام والطلب والخصم لا يمكن أن تكون سالبة": "Usage, order and discount limits cannot be negative",
  "تعذر تحديث حالة العرض.": "Could not update offer status.",
  "لا يمكن حذف عرض مستخدم": "An offer that has been used cannot be deleted",
  "حذف العرض (نقل للمحذوفات)؟": "Delete this offer and move it to deleted items?",
  "تعذر حذف العرض.": "Could not delete the offer.",
  "استرجاع العرض من المحذوفات؟": "Restore this offer from deleted items?",
  "تعذر استرجاع العرض.": "Could not restore the offer.",
  "⚠️ حذف نهائي؟ لا يمكن التراجع": "⚠️ Permanently delete? This cannot be undone",
  "تعذر حذف العرض نهائيًا.": "Could not permanently delete the offer.",
  "أدخل السعر قبل الخصم أولًا": "Enter the original price first",
  "اسم الباقة مكتمل": "Package name is complete",
  "تم اختيار خدمة واحدة على الأقل": "At least one service is selected",
  "السعر وعدد الجلسات صالحان": "Price and session count are valid",
  "فترة الإتاحة صحيحة": "Availability period is valid",
  "قسم غير محدد": "Unspecified section",
  "تصنيف غير محدد": "Unspecified category",
  "اكتب اسم الباقة": "Enter the package name",
  "تاريخ بداية الباقة يجب أن يكون قبل تاريخ الانتهاء": "Package start date must be before the end date",
  "تاريخ انتهاء الباقة يجب أن يكون اليوم أو بعده": "Package end date must be today or later",
  "اختر خدمة واحدة على الأقل": "Select at least one service",
  "عدد الجلسات يجب أن يكون أكبر من صفر": "Session count must be greater than zero",
  "سعر الباقة لا يمكن أن يكون سالبًا": "Package price cannot be negative",
  "تم تحديث الباقة بنجاح": "Package updated successfully",
  "تم حفظ الباقة بنجاح": "Package saved successfully",
  "تعذر حفظ الباقة في Core API.": "Could not save the package in the Core API.",
  "هل أنت متأكد من حذف هذه الباقة؟": "Are you sure you want to delete this package?",
  "تم حذف الباقة": "Package deleted",
  "تعذر حذف الباقة من Core API.": "Could not delete the package from the Core API.",
  "الباقة منتهية. عدّل تاريخ الانتهاء إلى اليوم أو بعده ثم احفظها.": "The package has expired. Change the end date to today or later, then save it.",
  "تعذر تحديث حالة الباقة.": "Could not update package status.",
  "العروض والباقات": "Offers and packages",
  "إدارة الحملات الترويجية والكوبونات والباقات من مساحة موحدة، مع متابعة الحالة والتواريخ والاستخدام.": "Manage promotions, coupons and packages from one workspace, with status, date and usage tracking.",
  "إجراءات العروض والباقات": "Offers and packages actions",
  "إغلاق نموذج العرض": "Close offer form",
  "إضافة عرض": "Add offer",
  "إغلاق نموذج الباقة": "Close package form",
  "إنشاء باقة": "Create package",
  "تحديث": "Refresh",
  "العروض النشطة": "Active offers",
  "من أصل": "out of",
  "عرض": "offers",
  "العروض المجدولة": "Scheduled offers",
  "منتهٍ أو موقوف": "expired or disabled",
  "الباقات النشطة": "Active packages",
  "باقة": "packages",
  "المعروض للبيع": "Available for sale",
  "عروض مستخدمة": "used offers",
  "الباقات المحفوظة": "Saved packages",
  "إدارة الباقات الجاهزة للبيع، جلساتها، أسعارها وصلاحيتها من مكان واحد.": "Manage sale-ready packages, sessions, prices and validity from one place.",
  "لا توجد باكيجات محفوظة": "No saved packages",
  "تجديد": "Renew",
  "إيقاف": "Disable",
  "تفعيل": "Enable",
  "الاسم": "Name",
  "السعر": "Price",
  "عدد الجلسات": "Sessions",
  "الصلاحية": "Validity",
  "يبدأ": "Starts",
  "ينتهي": "Ends",
  "الحالة": "Status",
  "الوصف": "Description",
  "تعديل": "Edit",
  "حذف": "Delete",
  "تعديل الباقة": "Edit package",
  "إنشاء باقة جديدة": "Create new package",
  "أدخل البيانات التجارية، حدّد الخدمات، ثم راجع الملخص قبل الحفظ. سيتم تحديث نفس السجل عند التعديل.": "Enter the commercial details, select services, then review the summary before saving. The same record will be updated when editing.",
  "إغلاق": "Close",
  "تفريغ": "Clear",
  "حفظ التعديلات": "Save changes",
  "إنشاء الباقة": "Create package",
  "البيانات الأساسية": "Basic information",
  "الاسم والوصف اللذان سيظهران للعميلة وفي لوحة الإدارة.": "The name and description shown to the client and in the admin dashboard.",
  "اسم الباقة": "Package name",
  "مطلوب": "Required",
  "مثال: باقة العناية الشهرية": "Example: Monthly Care Package",
  "استخدم اسمًا واضحًا وقصيرًا يسهل تمييزه في الحجز.": "Use a clear, short name that is easy to identify in booking.",
  "المعرف الداخلي": "Internal ID",
  "يُنشأ تلقائيًا عند تركه فارغًا": "Generated automatically when left blank",
  "للاستخدام التقني فقط، ولا يظهر للعميلة.": "For technical use only; it is not shown to the client.",
  "وصف الباقة": "Package description",
  "اكتب فائدة الباقة وما الذي تحصل عليه العميلة...": "Describe the package benefits and what the client receives...",
  "التسعير والجلسات": "Pricing and sessions",
  "اضبط سعر البيع، الرصيد، مدة الصلاحية وترتيب الظهور.": "Set the sale price, session balance, validity and display order.",
  "سعر الباقة": "Package price",
  "ر.س": "SAR",
  "جلسة": "session",
  "مدة الصلاحية": "Validity period",
  "يوم": "days",
  "متوسط سعر الجلسة حاليًا": "Current average price per session",
  "الإتاحة والنشر": "Availability and publishing",
  "حدد فترة ظهور الباقة وحالتها في البيع والحجز.": "Set the package visibility period and its sale/booking status.",
  "تاريخ البداية": "Start date",
  "تاريخ الانتهاء": "End date",
  "الباقة مفعّلة": "Package enabled",
  "تُعامل كسجل نشط داخل النظام.": "Treated as an active record in the system.",
  "معروضة للبيع والحجز": "Available for sale and booking",
  "تظهر في القنوات المسموح لها ببيع الباقات.": "Shown in channels allowed to sell packages.",
  "الصورة والشروط": "Image and terms",
  "ارفع صورة مناسبة وأضف شروط الاستخدام عند الحاجة.": "Upload a suitable image and add usage terms when needed.",
  "معاينة صورة الباقة": "Package image preview",
  "تغيير صورة الباقة": "Change package image",
  "رفع صورة الباقة": "Upload package image",
  "شروط استخدام الباقة": "Package terms",
  "مثال: غير قابلة للتحويل، الحجز المسبق مطلوب...": "Example: non-transferable, advance booking required...",
  "إزالة الصورة": "Remove image",
  "الخدمات المشمولة": "Included services",
  "اختر الخدمات التي يمكن للعميلة استخدام رصيد الجلسات عليها.": "Select the services on which the client can use the package session balance.",
  "محددة": "selected",
  "ابحث باسم الخدمة أو السعر أو المدة...": "Search by service name, price or duration...",
  "تحديد النتائج": "Select results",
  "إلغاء النتائج": "Clear results",
  "جميع الخدمات": "All services",
  "المحددة": "Selected",
  "غير المحددة": "Unselected",
  "خدمة ضمن الباقة": "services in package",
  "خدمة": "service",
  "دقيقة": "min",
  "لا توجد خدمات مطابقة للبحث": "No services match the search",
  "لا توجد خدمات محددة حسب البحث الحالي": "No selected services match the current search",
  "كل الخدمات الحالية محددة بالفعل": "All current services are already selected",
  "صورة الباقة": "Package image",
  "معاينة الباقة": "Package preview",
  "سيظهر وصف الباقة هنا بعد إدخاله.": "The package description will appear here after you enter it.",
  "سعر البيع": "Sale price",
  "للجلسة": "per session",
  "بداية الإتاحة": "Availability start",
  "نهاية الإتاحة": "Availability end",
  "جاهزية الحفظ": "Save readiness",
  "إلغاء والعودة": "Cancel and return",
  "مركز العروض": "Offers center",
  "اعرض الحملات حسب حالتها، ثم ابحث مباشرة بالعنوان أو كود الخصم.": "View campaigns by status, then search directly by title or discount code.",
  "كل العروض": "All offers",
  "سارية الآن": "Active now",
  "مجدولة": "Scheduled",
  "منتهية/موقوفة": "Expired / disabled",
  "محذوفة": "Deleted",
  "بحث بالعنوان أو الكود...": "Search by title or code...",
  "نتائج العروض": "Offer results",
  "لا توجد عروض مطابقة لهذا التصنيف. اختر «كل العروض» لعرض السارية والمجدولة والمنتهية.": "No offers match this filter. Select “All offers” to view active, scheduled and expired offers.",
  "العنوان": "Title",
  "الكود": "Code",
  "الخصم": "Discount",
  "الفترة": "Period",
  "الاستخدام": "Usage",
  "النطاق": "Scope",
  "خدمات محددة": "Selected services",
  "الكل": "All",
  "استرجاع": "Restore",
  "حذف نهائي": "Delete permanently",
  "تعديل العرض": "Edit offer",
  "إنشاء عرض جديد": "Create new offer",
  "إدارة بيانات العرض، التسعير، حدود الاستخدام، النطاق، الاستهداف، النشر والصورة من مساحة عمل واحدة.": "Manage offer details, pricing, usage limits, scope, targeting, publishing and image from one workspace.",
  "حفظ العرض": "Save offer",
  "هوية العرض": "Offer identity",
  "البيانات التي تظهر للعميلة في التطبيق وصفحات العروض.": "Information shown to the client in the app and offer pages.",
  "عنوان العرض": "Offer title",
  "مثال: عرض نهاية الأسبوع": "Example: Weekend offer",
  "اكتب عنوانًا واضحًا ومباشرًا يسهل فهمه.": "Use a clear, direct title that is easy to understand.",
  "كود العرض": "Offer code",
  "توليد": "Generate",
  "يُستخدم عند تطبيق العرض بالكوبون أو داخل الحجز.": "Used when applying the offer via coupon or during booking.",
  "وصف العرض": "Offer description",
  "اكتب وصفًا مختصرًا، شروط الاستفادة، وما الذي تحصل عليه العميلة...": "Write a short description, eligibility terms and what the client receives...",
  "الوصف هو المكان الأنسب لشرح الشروط والملاحظات للعميلة.": "The description is the best place to explain terms and notes to the client.",
  "الخصم والتسعير": "Discount and pricing",
  "حدد آلية الخصم والأسعار المعروضة وحدود الحماية المالية.": "Set the discount method, displayed prices and financial safeguards.",
  "نوع الخصم": "Discount type",
  "مبلغ ثابت": "Fixed amount",
  "خصم قيمة محددة بالريال": "Discount a fixed SAR amount",
  "نسبة مئوية": "Percentage",
  "خصم نسبة من قيمة الخدمة": "Discount a percentage of the service value",
  "ريال": "SAR",
  "الخصم المحسوب": "Calculated discount",
  "السعر المقترح بعد الخصم": "Suggested price after discount",
  "التوفير الظاهر": "Displayed saving",
  "احتساب السعر تلقائيًا": "Calculate price automatically",
  "ضع 0 لعدم تحديد حد إجمالي.": "Enter 0 for no total limit.",
  "ضع 0 للسماح بدون حد فردي.": "Enter 0 for no per-client limit.",
  "الفترة وحالة النشر": "Period and publishing status",
  "تحكم في موعد ظهور العرض وحالته داخل النظام وتطبيق العميلة.": "Control when the offer appears and its status in the system and client app.",
  "حالة النشر": "Publishing status",
  "الحالة الفعلية حسب التاريخ": "Effective status by date",
  "تفعيل العرض": "Enable offer",
  "يسمح للنظام بتطبيق الخصم خلال فترة العرض.": "Allows the system to apply the discount during the offer period.",
  "النشر للعميلات": "Publish to clients",
  "إظهار العرض في تطبيق العميلة وصفحات العروض.": "Show the offer in the client app and offer pages.",
  "الجمهور وزر الإجراء": "Audience and action button",
  "حدد من يمكنه رؤية العرض وإلى أين ينتقل زر الحجز.": "Choose who can see the offer and where the booking button goes.",
  "جميع العميلات": "All clients",
  "عرض عام متاح لكل الحسابات المؤهلة.": "A public offer available to all eligible accounts.",
  "عميلات محددات": "Specific clients",
  "استهداف قائمة معرفات أو حسابات بعينها.": "Target a specific list of IDs or accounts.",
  "معرفات العميلات المستهدفات": "Target client IDs",
  "مطلوب للنطاق المحدد": "Required for specific targeting",
  "clientId أو Firebase UID، مفصولة بفواصل أو أسطر": "clientId or Firebase UID, separated by commas or lines",
  "نص زر الإجراء": "Action button text",
  "رابط الإجراء": "Action link",
  "/booking أو رابط داخلي": "/booking or an internal link",
  "نطاق تطبيق العرض": "Offer application scope",
  "حدد ما إذا كان الخصم عامًا أو مرتبطًا بخدمات أو تصنيفات محددة.": "Choose whether the discount is general or linked to specific services or categories.",
  "كل الخدمات": "All services",
  "يطبق العرض على كامل كتالوج الصالون.": "Apply the offer to the entire salon catalog.",
  "خدمة محددة حاليًا.": "services currently selected.",
  "تصنيفات محددة": "Selected categories",
  "تصنيف محدد حاليًا.": "categories currently selected.",
  "اختيار الخدمات": "Select services",
  "تحديد الظاهر": "Select visible",
  "إلغاء الظاهر": "Clear visible",
  "إخفاء القائمة": "Hide list",
  "عرض القائمة": "Show list",
  "الخدمات المختارة": "Selected services",
  "ابحث باسم الخدمة أو القسم أو السعر...": "Search by service, section or price...",
  "لا توجد خدمات مطابقة للبحث.": "No services match the search.",
  "إعداد تسلسل الخدمات": "Configure service sequence",
  "اختياري للحجوزات التي تعتمد ترتيبًا وفواصل زمنية.": "Optional for bookings that require an ordered service sequence and time gaps.",
  "إخفاء": "Hide",
  "فتح": "Open",
  "الترتيب": "Order",
  "الخدمة": "Service",
  "الفاصل بعد الخدمة": "Gap after service",
  "اسم بديل": "Alternate name",
  "تحريك": "Move",
  "اسم اختياري": "Optional name",
  "اختيار التصنيفات": "Select categories",
  "تحديد الكل": "Select all",
  "إلغاء الكل": "Clear all",
  "صورة العرض": "Offer image",
  "ارفع صورة واضحة ومتناسقة مع هوية الصالون؛ الحد الأعلى": "Upload a clear image consistent with the salon identity; maximum size",
  "اختيار صورة العرض": "Choose offer image",
  "الملف الحالي": "Current file",
  "صورة محفوظة": "Saved image",
  "لم يتم اختيار صورة": "No image selected",
  "يفضل استخدام صورة أفقية واضحة بدون نصوص صغيرة لضمان ظهور جيد في الجوال.": "Use a clear horizontal image without small text for better mobile display.",
  "معاينة العرض": "Offer preview",
  "سيظهر وصف العرض هنا للعميلة.": "The offer description will appear here for the client.",
  "مفتوحة": "Open",
  "الجمهور": "Audience",
  "غير محدود": "Unlimited",
  "لكل عميلة": "Per client",
  "جاهزية العرض": "Offer readiness",
  "جاهز للحفظ": "Ready to save",
  "يحتاج مراجعة": "Needs review",
  "قيمة الخدمات المحددة": "Selected services value",
  "قيمة إرشادية محسوبة من أسعار الخدمات المختارة.": "Indicative value calculated from selected service prices.",
  "إلغاء": "Cancel",
  "تاريخ النهاية": "End date",
  "معاينة صورة العرض": "Offer image preview",
  "PNG أو JPG أو WEBP": "PNG or JPG or WEBP",
};

export function offersText(language: DashboardLanguage, arabic: string): string {
  if (language === "ar") return arabic;
  return offersEnglish[arabic] ?? dashboardText(language, arabic);
}
