import { createContext, useContext, useMemo, type ReactNode } from "react";
import {
  dashboardText,
  type DashboardLanguage,
} from "../../helpers/dashboardLanguage";

const employeeEnglish: Record<string, string> = {
  "غير مصرح": "Unauthorized",
  "سجّل دخول ثم جرّب مرة أخرى.": "Sign in, then try again.",
  "صلاحيات غير كافية": "Insufficient permissions",
  "هذه الصفحة مخصصة للإدارة.": "This page is restricted to authorized management accounts.",
  "ليست لديك صلاحية لإضافة موظفات.": "You do not have permission to add staff.",
  "تعذر إكمال العملية": "Unable to complete the action",
  "نعم، متابعة": "Yes, continue",
  "تراجع": "Cancel",
  "جارٍ التنفيذ...": "Processing...",
  "إدارة الملفات الوظيفية والحضور والخدمات والرواتب من مساحة موحدة.": "Manage staff profiles, attendance, services and payroll from one workspace.",
  "إضافة موظفة": "Add staff member",
  "تحديث البيانات": "Refresh data",
  "إحصاءات الموظفات": "Staff statistics",
  "إجمالي الملفات": "Total profiles",
  "كل الملفات المتاحة حسب الصلاحية": "All profiles available to your account",
  "على رأس العمل": "Active staff",
  "نشطات ولسن في إجازة": "Active and not on leave",
  "في إجازة": "On leave",
  "إجازة حالية من سجل الموظفة": "Current leave from the staff record",
  "تحتاج متابعة": "Needs attention",
  "غير نشطة أو بدون خدمات أو ملف غير مكتمل": "Inactive, no assigned services, or incomplete profile",
  "جاري فتح ملف الموظفة...": "Opening staff profile...",
  "يتم تحميل الملف من السجل الوظيفي الحالي بدون تغيير مسارات الحسابات.": "Loading the current employment record without changing account links.",
  "البيانات الأساسية": "Basic information",
  "الحجز والدوام": "Booking & schedule",
  "الخدمات": "Services",
  "الملف": "Profile",
  "الإحصائيات والإجازات": "Statistics & leave",
  "الاسم والحالة والظهور": "Name, status and visibility",
  "الملفات والصور": "Files & photos",
  "الصورة والمستندات والمرفقات والسجل": "Photo, documents, attachments and history",
  "الخدمات المسندة للموظفة": "Services assigned to this staff member",
  "الدوام والشفتات": "Schedule & shifts",
  "الجدول والقوالب والسياسات": "Schedule, templates and policies",
  "الحضور": "Attendance",
  "السجل اليومي": "Daily record",
  "سجل الرواتب": "Payroll record",
  "القفل والحساب": "Locking and calculation",
  "الطلبات": "Requests",
  "طلبات الموظفة": "Staff requests",
  "رصيد الإجازات": "Leave balance",
  "الحالة والرصيد والسجل": "Status, balance and ledger",
  "الرسائل": "Messages",
  "التواصل الداخلي": "Internal communication",
  "قائمة الموظفات": "Staff directory",
  "دليل الموظفات": "Staff directory",
  "بحث سريع وفتح ملف الموظفة من قائمة موحدة.": "Search and open staff profiles from one directory.",
  "ملف": "profiles",
  "البحث": "Search",
  "الاسم، الجوال، البريد أو الرقم الوظيفي": "Name, mobile, email or employee ID",
  "بحث في الموظفات": "Search staff",
  "الظهور": "Visibility",
  "الظاهرات في الدليل": "Visible in directory",
  "المخفيات من الدليل": "Hidden from directory",
  "كل الموظفات": "All staff",
  "الحالة": "Status",
  "كل الحالات": "All statuses",
  "النشطات فقط": "Active only",
  "غير النشطات فقط": "Inactive only",
  "الخدمة": "Service",
  "كل الخدمات": "All services",
  "بدون خدمات مسندة": "No assigned services",
  "إعادة ضبط": "Reset",
  "جاري تحميل الموظفات": "Loading staff",
  "حساب يحتاج مراجعة": "Account needs review",
  "موظفة بدون اسم": "Unnamed staff member",
  "إداري": "Administrative",
  "قسم غير محدد": "Unassigned department",
  "نشطة": "Active",
  "غير نشطة": "Inactive",
  "لا يوجد بريد": "No email",
  "لا يوجد جوال": "No mobile",
  "حالة الملف": "Profile status",
  "يحتاج إكمال": "Needs completion",
  "مكتمل": "Complete",
  "أداء الشهر": "Monthly performance",
  "فتح الملف": "Open profile",
  "لا توجد موظفات مطابقة": "No matching staff",
  "غيّري البحث أو أعيدي ضبط الفلاتر لعرض الملفات المتاحة.": "Change the search or reset filters to show available profiles.",
  "إعادة ضبط الفلاتر": "Reset filters",
  "إدارة بيانات الموظفة": "Manage staff information",
  "جاري حفظ التغييرات": "Saving changes",
  "توجد تعديلات غير محفوظة": "There are unsaved changes",
  "يتم الآن تثبيت بيانات الموظفة في المصدر الرئيسي.": "Saving staff data to the canonical source.",
  "اضغط حفظ التغييرات لتثبيت القيم الحالية.": "Select Save changes to persist the current values.",
  "إلغاء التعديلات": "Discard changes",
  "جاري الحفظ...": "Saving...",
  "حفظ التغييرات": "Save changes",
  "موظفة": "Staff member",
  "ملف الموظفة": "Staff profile",
  "مسار التنقل": "Breadcrumb",
  "الموظفات": "Staff",
  "صورة الموظفة": "Staff photo",
  "عرض فقط": "Read only",
  "ملف موظفة فعلي": "Canonical staff profile",
  "خدمة مرتبطة": "linked service",
  "بدون خدمات مرتبطة": "No linked services",
  "ملخص الموظفة": "Staff summary",
  "غير محددة": "Not specified",
  "القسم الحالي": "Current section",
  "بيانات فعلية": "Canonical data",
  "مساحة الموظفة": "Staff workspace",
  "إنهاء الخدمة": "End employment",
  "العودة إلى الموظفات": "Back to staff",
  "أقسام ملف الموظفة": "Staff profile sections",
  "ليست لديك صلاحية إنشاء حسابات دخول. يمكنك إنشاء الملف الوظيفي فقط.": "You do not have permission to create login accounts. You can create the employment profile only.",
  "أدخل بريدًا إلكترونيًا صحيحًا لإنشاء حساب الدخول.": "Enter a valid email address to create the login account.",
  "كلمة المرور المؤقتة يجب أن تكون 6 أحرف على الأقل.": "The temporary password must be at least 6 characters.",
  "إلغاء": "Cancel",
  "إنشاء الموظفة وحساب الدخول": "Create staff member & login",
  "إنشاء الموظفة": "Create staff member",
  "الملف الحالي": "Current profile",
  "أكملي بيانات الموظفة، ثم أنشئي ملفها وحساب الدخول من نفس العملية.": "Complete the staff details, then create the profile and login in the same flow.",
  "تعديل بيانات الموظفة من نافذة موحدة.": "Edit staff information in one workspace.",
  "بدون خدمات": "No services",
  "عملية إضافة الموظفة": "Add staff member flow",
  "عملية موحدة": "Unified flow",
  "ملف الموظفة وحساب الدخول في مكان واحد": "Staff profile and login in one place",
  "أكملي الأقسام بالترتيب المناسب لك. النظام ينشئ ويربط حساب الدخول تلقائيًا بدون أي معرّفات أو خطوات تقنية يدوية.": "Complete the sections in any order. The system creates and links the login automatically without manual IDs or technical steps.",
  "حساب الدخول": "Login account",
  "تسجيل دخول الموظفة": "Staff login",
  "اختياري. عند تفعيله سيتم إنشاء الحساب وربطه بالملف الوظيفي تلقائيًا ضمن نفس عملية الحفظ.": "Optional. When enabled, the account is created and linked to the employment profile in the same save flow.",
  "إنشاء وتفعيل حساب دخول": "Create and activate login",
  "لا تملك صلاحية إنشاء حسابات دخول؛ سيتم إنشاء الملف الوظيفي فقط.": "You do not have permission to create login accounts; only the employment profile will be created.",
  "البريد الإلكتروني": "Email",
  "سيستخدم لتسجيل الدخول واستعادة كلمة المرور.": "Used for sign-in and password recovery.",
  "اختياري إذا لم يتم إنشاء حساب دخول.": "Optional when no login account is created.",
  "رقم الجوال": "Mobile number",
  "الدور": "Role",
  "الاستقبال": "Reception",
  "المحاسبة": "Accounting",
  "الإدارة": "Management",
  "كلمة المرور المؤقتة": "Temporary password",
  "يمكن للموظفة تغييرها لاحقًا.": "The staff member can change it later.",
  "توليد": "Generate",
  "إنهاء خدمة الموظفة": "End staff employment",
  "آخر يوم عمل": "Last working day",
  "اختر آخر يوم عمل": "Select last working day",
  "سبب إنهاء الخدمة": "Reason for ending employment",
  "لن يُنشئ النظام تاريخًا أو سببًا تلقائيًا، ولن يعيد تعيين الحجوزات تلقائيًا.": "The system will not generate a date or reason automatically and will not reassign bookings automatically.",
  "جارٍ إنهاء الخدمة...": "Ending employment...",
  "تأكيد إنهاء الخدمة": "Confirm end of employment",
  "المراجع:": "References:",
  "تعديل البصمة": "Edit attendance record",
  "تعديل سجل الحضور والانصراف": "Edit attendance record",
  "الحضور والانصراف": "Attendance",
  "وقت الحضور": "Check-in time",
  "اختاري ساعة ودقيقة الحضور فقط.": "Select the check-in hour and minute.",
  "مسح الوقت": "Clear time",
  "وقت الانصراف": "Check-out time",
  "يمكن تركه فارغًا إذا لم تسجل الموظفة انصرافًا.": "Leave blank if the staff member has not checked out.",
  "ملاحظة الإدارة": "Management note",
  "يُفضّل توضيح سبب تعديل البصمة لأغراض المراجعة.": "Add the reason for the attendance edit for audit purposes.",
  "مثال: تصحيح بصمة من الإدارة": "Example: attendance correction by management",
  "حفظ تعديل البصمة": "Save attendance edit",
  "لا توجد إجازة أسبوعية ثابتة.": "No fixed weekly day off.",
  "السبت": "Saturday",
  "الأحد": "Sunday",
  "الاثنين": "Monday",
  "الثلاثاء": "Tuesday",
  "الأربعاء": "Wednesday",
  "الخميس": "Thursday",
  "الجمعة": "Friday",
  "إدارة اسم الموظفة وحالة الحساب وظهورها في الموقع والحجز من مكوّن V2 مستقل.": "Manage the staff member's name, account status, and visibility across the website and booking.",
  "هوية الموظفة": "Staff identity",
  "الاسم المعتمد داخل الإدارة وواجهات العميلات.": "The canonical name used in management and client-facing interfaces.",
  "اسم الموظفة": "Staff name",
  "بداية سنة الخدمة": "Employment start date",
  "الظهور العام": "Public visibility",
  "تحديد مواضع ظهور الموظفة أمام العميلات.": "Control where this staff member appears to clients.",
  "إظهار في دليل الموظفات": "Show in staff directory",
  "إخفاؤها من الدليل لا يحذف الملف ولا يؤثر على الحضور أو الرواتب.": "Hiding the profile from the directory does not delete it or affect attendance or payroll.",
  "الظهور في صفحة من نحن": "Show on About page",
  "عرض الصورة والنبذة ضمن فريق الصالون.": "Show the photo and bio in the salon team section.",
  "الظهور في صفحة الحجز": "Show on booking page",
  "إتاحة اختيار الموظفة للخدمات المسندة.": "Allow clients to select this staff member for assigned services.",
  "الحساب غير نشط. فعّل حالة الحساب أولاً ثم أعد تفعيل الظهور في صفحة الحجز.": "The account is inactive. Activate the account first, then enable booking-page visibility.",
  "الحجز المباشر متوقف": "Direct booking disabled",
  "الحجوزات السابقة محفوظة، لكن الموظفة لن تظهر في الحجوزات الجديدة.": "Existing bookings are preserved, but this staff member will not appear in new bookings.",
  "الحساب": "Account",
  "ظاهرة": "Visible",
  "مخفية": "Hidden",
  "من نحن": "About us",
  "الحجز": "Booking",
  "متاحة": "Available",
  "متوقفة": "Disabled",
  "الإجازة الأسبوعية": "Weekly day off",
  "تُعدل من جدول الدوام": "Managed from the work schedule",
  "وضع العرض فقط": "Read-only mode",
  "صلاحيتك تسمح بمراجعة البيانات دون تعديلها.": "Your permission allows you to review this data but not edit it.",
  "مستبدلة": "Replaced",
  "مؤرشفة": "Archived",
  "الحالية": "Current",
  "غير معروف": "Unknown",
  "الصورة الشخصية والملف العام": "Profile photo & public profile",
  "إدارة الصورة الشخصية والسيرة والتقييم وسجل الصور السابقة.": "Manage the profile photo, bio, rating, and previous photo history.",
  "الصورة جاهزة": "Photo available",
  "بدون صورة": "No photo",
  "الصورة الشخصية": "Profile photo",
  "الصورة الحالية المعتمدة في ملف الموظفة.": "The current approved photo for this staff profile.",
  "جاري رفع الصورة...": "Uploading photo...",
  "تغيير الصورة": "Change photo",
  "رفع صورة": "Upload photo",
  "حذف الصورة": "Remove photo",
  "لا توجد صورة": "No photo available",
  "ارفعي صورة شخصية من الجهاز.": "Upload a profile photo from this device.",
  "إدارة الصورة غير متاحة": "Photo management unavailable",
  "يجب حفظ سجل الموظفة أولًا قبل إدارة الصورة الشخصية.": "Save the staff record before managing the profile photo.",
  "التقييم": "Rating",
  "بيانات الملف العام": "Public profile information",
  "السيرة والتقييمات المرتبطة بملف الموظفة.": "Bio and ratings linked to this staff profile.",
  "رابط السيرة الذاتية": "CV link",
  "تقييم العرض": "Display rating",
  "عدد التقييمات": "Review count",
  "النبذة التعريفية": "Profile bio",
  "النص الذي يظهر للعميلات عند استعراض الموظفة.": "The text shown to clients when viewing this staff member.",
  "النبذة": "Bio",
  "سجل الصور السابقة": "Previous photo history",
  "الصور المستبدلة أو المؤرشفة تبقى محفوظة للسجل دون حذفها من R2.": "Replaced or archived photos remain in the record and are not deleted from R2.",
  "صورة شخصية": "Profile photo",
  "بدون تاريخ": "No date",
  "لا توجد صور سابقة": "No previous photos",
  "عند تغيير أو حذف الصورة الحالية ستظهر النسخ السابقة هنا.": "When the current photo is changed or removed, previous versions will appear here.",
  "إسناد الخدمات والبحث والتصفية من مكوّن V2 مستقل مرتبط بالقائمة الفعلية.": "Assign, search, and filter services from the live V2 service list.",
  "المتاح": "Available",
  "المحدد": "Selected",
  "نتائج التصفية": "Filtered results",
  "الأقسام": "Sections",
  "البحث والتصفية": "Search & filters",
  "قوائم V2 فقط، بدون select أصلي أو EmployeeSelect القديم.": "Uses the V2 controls and the canonical service list.",
  "اسم الخدمة أو القسم": "Service or section name",
  "القسم": "Section",
  "كل الأقسام": "All sections",
  "نطاق العرض": "Display scope",
  "الكل": "All",
  "المختارة": "Selected",
  "غير المختارة": "Not selected",
  "تحديد الظاهر": "Select visible",
  "مسح الكل": "Clear all",
  "الخدمات المتاحة": "Available services",
  "مدة غير محددة": "Duration not specified",
  "دقيقة": "min",
  "محددة": "Selected",
  "تحديد": "Select",
  "لا توجد نتائج": "No results",
  "غيّر البحث أو القسم أو نطاق العرض.": "Change the search, section, or display scope.",
  "عرض المزيد": "Show more",
  "الخدمات المختارة": "Selected services",
  "قائمة مستقلة مضغوطة.": "Compact selected-services list.",
  "البحث داخل المختارة": "Search selected services",
  "لا توجد نتيجة مطابقة": "No matching result",
  "لم تُحدد خدمات": "No services selected",
  "امسح عبارة البحث لعرض القائمة.": "Clear the search text to show the list.",
  "اختاري الخدمات من القائمة المجاورة.": "Select services from the adjacent list.",
  "مغلق اليوم": "Closed today",
  "متاح اليوم": "Available today",
  "لا توجد استثناءات": "No exceptions",
  "ساعات العمل الفعلية اليوم": "Today's effective working hours",
  "ملخص مباشر بعد تطبيق الجدول الأسبوعي والاستثناءات المحفوظة.": "Live summary after applying the weekly schedule and saved exceptions.",
  "حالة اليوم": "Today's status",
  "حسب الجدول الفعلي": "Based on the effective schedule",
  "نافذة العمل": "Working window",
  "بعد تطبيق جميع الاستثناءات": "After applying all exceptions",
  "الاستثناءات": "Exceptions",
  "آخر تحديث": "Last updated",
  "تحديث تلقائي للحالة": "Status updates automatically",
  "سبب الإغلاق": "Closure reason",
  "الدوام القادم": "Next shift",
  "أقرب نافذة دوام قادمة حسب Malikat Core.": "The next working window according to Malikat Core.",
  "نافذة العودة": "Return window",
  "سيُحدد لاحقًا": "To be determined",
  "الميلادي": "Gregorian",
  "غير محدد": "Not specified",
  "الهجري": "Hijri",
  "المصدر": "Source",
  "حالة الدوام": "Schedule status",
  "نهاية الحالة": "Status end",
  "ملاحظة": "Note",
  "استثناءات الدوام": "Schedule exceptions",
  "الفترات والتواريخ والأسباب المحفوظة.": "Saved periods, dates, and reasons.",
  "ملخص الاستثناءات": "Exceptions summary",
  "العنوان": "Title",
  "الوقت": "Time",
  "تفاصيل": "Details",
  "محفوظ": "Saved",
  "استثناء محفوظ": "Saved exception",
  "لا توجد استثناءات دوام محفوظة حاليًا.": "There are no saved schedule exceptions.",
  "ملاحظة الجدول": "Schedule note",
  "تفاصيل احتساب الدوام": "Schedule calculation details",
  "المصدر والجدول الأسبوعي والنتيجة النهائية.": "Source, weekly schedule, and final result.",
  "البند": "Item",
  "القيمة": "Value",
  "لا توجد تفاصيل احتساب إضافية.": "No additional calculation details.",
  "راحة أسبوعية": "Weekly day off",
  "راحة أسبوعية مؤقتة": "Temporary weekly day off",
  "يوم راحة استثنائي": "Exceptional day off",
  "عمل استثنائي في يوم الراحة": "Exceptional work on a day off",
  "تكليف يوم الراحة": "Day-off work assignment",
  "جدول الدوام الأسبوعي": "Weekly work schedule",
  "نقل مؤقت للراحة الأسبوعية": "Temporary weekly-day-off transfer",
  "استثناء يومي معتمد": "Approved daily exception",
  "مجدول": "Scheduled",
  "تعمل الآن": "Working now",
  "خارج الدوام": "Off duty",
  "استثناء يومي": "Daily exception",
  "راحة / إغلاق لهذا اليوم": "Day off / closed today",
  "وقت مخصص": "Custom hours",
  "شفت بديل": "Alternate shift",
  "شفت اليوم من جدول الموظفة": "Today's shift from the staff schedule",
  "شفت افتراضي قديم": "Legacy default shift",
  "تعيين احتياطي للموظفات القديمة": "Fallback assignment for legacy staff",
  "تعذر تحميل شفتات الحضور من Core. تم إيقاف تعديلات الحضور حتى ينجح التحقق.": "Could not load attendance shifts from Core. Attendance edits are disabled until verification succeeds.",
  "جاري التحقق من بيانات Core. لا يمكن تعديل البصمة الآن.": "Verifying Core data. Attendance records cannot be edited yet.",
  "ليست لديك صلاحية لمسح وقت البصمة.": "You do not have permission to clear attendance times.",
  "لا يوجد وقت حضور لمسحه في هذا اليوم.": "There is no check-in time to clear for this day.",
  "لا يوجد وقت انصراف لمسحه في هذا اليوم.": "There is no check-out time to clear for this day.",
  "الانصراف": "Check-out",
  "تم مسح وقت الحضور فقط، وبقيت بقية سجلات اليوم كما هي.": "The check-in time was cleared; the rest of the day's records were preserved.",
  "تم مسح وقت الانصراف فقط، وبقيت بقية سجلات اليوم كما هي.": "The check-out time was cleared; the rest of the day's records were preserved.",
  "إدارة أوقات بصمة اليوم المحدد": "Manage attendance times for the selected day",
  "جاري مسح الحضور...": "Clearing check-in...",
  "مسح وقت الحضور": "Clear check-in time",
  "جاري مسح الانصراف...": "Clearing check-out...",
  "مسح وقت الانصراف": "Clear check-out time",
  "تحديث": "Refresh",
  "إعادة المحاولة": "Try again",
  "نموذج التحميل": "Loading state",
  "جارٍ تحميل بيانات التبويب": "Loading tab data",
  "لا توجد بيانات بعد": "No data yet",
  "تظهر هنا البيانات عند إضافتها أو توفرها للموظفة.": "Data will appear here when it is added or available for the staff member.",
  "تعذر تحميل القسم": "Could not load section",
  "احتفظنا بالبيانات الحالية. أعد المحاولة بعد التحقق من الاتصال.": "Current data was preserved. Try again after checking the connection.",
  "تعذر جلب البيانات التجريبية": "Could not load preview data",
  "ملف الموظفة الداخلي": "Internal staff profile",
  "دليل الاستخدام": "Usage guide",
  "فهمت": "Got it",
  "ما الغرض من هذا القسم؟": "What is this section for?",
  "متى أستخدم هذا القسم؟": "When should I use this section?",
  "حدد الحالة الصحيحة قبل إجراء أي تعديل.": "Choose the correct scenario before making changes.",
  "استخدمه عندما": "Use it when",
  "لا تستخدمه من أجل": "Do not use it for",
  "مثال عملي": "Practical example",
  "مثال مبسط يوضح المدخلات والنتيجة داخل النظام.": "A simple example showing the inputs and expected result.",
  "ما الذي تفعله؟": "What should you do?",
  "النتيجة": "Result",
  "طريقة الاستخدام": "How to use",
  "اتبع الخطوات بالترتيب لتجنب تضارب الإعدادات.": "Follow the steps in order to avoid conflicting settings.",
  "مهم": "Important",
  "اختر لكل يوم قالب شفت أو راحة أسبوعية. أوقات وسياسات الدوام تُسحب تلقائيًا من القالب الموجود في نفس الصفحة.": "Choose a shift template or weekly day off for each day. Working times and attendance policies are inherited from the selected template.",
  "شرح الدوام والشفتات": "Explain schedule & shifts",
  "أيام العمل": "Working days",
  "أيام الراحة الأسبوعية": "Weekly days off",
  "قوالب الشفتات": "Shift templates",
  "محدد": "Selected",
  "إعدادات الجدول": "Schedule settings",
  "تاريخ بدء التطبيق وسبب تغيير جدول الموظفة.": "Set the effective date and document the reason for changing this staff schedule.",
  "شرح إعدادات الجدول": "Explain schedule settings",
  "الشفت هو مصدر الوقت والسياسة": "The shift is the source of time and policy",
  "لا يمكن تعديل بداية أو نهاية الدوام من جدول الأسبوع. عدّل قالب الشفت من قسم قوالب الشفتات في نفس الصفحة، أو استخدم استثناءً ليوم محدد.": "Start and end times cannot be edited from the weekly schedule. Edit the shift template or use a one-day exception.",
  "تطبيق الجدول من": "Schedule effective from",
  "تاريخ نهاية التوظيف": "Employment end date",
  "سبب تغيير الجدول": "Reason for schedule change",
  "اختيار موقع أو نطاق يسمح بالبصمة.": "Choose the location or zone where attendance clocking is allowed.",
  "شرح نطاق الحضور": "Explain attendance zone",
  "جاري التحميل": "Loading",
  "اختر النطاق": "Select zone",
  "بدون نطاق محدد": "No specific zone",
  "لا يوجد نطاق حضور": "No attendance zone",
  "تحديد النطاق يقلل أخطاء البصمة خارج الموقع.": "Selecting a zone reduces off-site clocking errors.",
  "الأسبوع التشغيلي": "Operational week",
  "لكل يوم: شفت من القوالب أو راحة أسبوعية.": "For each day, choose a shift template or a weekly day off.",
  "شرح الأسبوع التشغيلي": "Explain operational week",
  "تعذر تحميل قوالب الشفتات": "Could not load shift templates",
  "لا توجد قوالب شفتات": "No shift templates",
  "أنشئ قالب شفت واحدًا على الأقل من قسم قوالب الشفتات والاستثناءات الموجود أسفل هذه الصفحة، ثم ارجع لتوزيعه على أيام العمل.": "Create at least one shift template in the shifts and exceptions section below, then assign it to working days.",
  "يوم عمل": "Working day",
  "الشفت": "Shift",
  "جاري تحميل الشفتات": "Loading shifts",
  "اختر الشفت": "Select shift",
  "إغلاق البصمة غير مفعّل.": "Attendance lock is disabled.",
  "لا يوجد": "None",
  "إجازة": "Leave",
  "راحة": "Rest",
  "راحة / يوم استثنائي": "Rest / exceptional day",
  "تحميل": "Loading",
  "تعذر التحميل": "Load failed",
  "لا توجد سجلات": "No records",
  "بيانات محملة": "Data loaded",
  "عرض وتعديل سجل الحضور من مكوّن V2 مستقل.": "View and manage attendance records in the V2 workspace.",
  "أيام الشهر": "Days in month",
  "أيام عليها بصمة": "Days with attendance",
  "دقائق التأخير": "Late minutes",
  "أيام الإجازة": "Leave days",
  "تعذر تحديث سجل الحضور": "Could not refresh attendance records",
  "الأيام السابقة لتاريخ المباشرة لا تدخل في الحضور أو الغياب.": "Days before the employment start date are excluded from attendance and absence.",
  "فلتر الحضور": "Attendance filter",
  "اختر الشهر، ثم اضغط على أي يوم من التقويم لعرض تفاصيله.": "Choose a month, then select any day in the calendar to view its details.",
  "الشهر": "Month",
  "الشفت المطبق اليوم": "Effective shift for today",
  "المصدر الفعلي حسب أولوية: إجازة، استثناء، شفت محدد، جدول الموظفة، ثم دوام الصالون.": "The effective source follows this priority: leave, exception, assigned shift, staff schedule, then salon schedule.",
  "يتم تحديده تلقائياً من البيانات": "Determined automatically from the data",
  "الوقت الفعلي": "Effective time",
  "جاري تحميل الحضور": "Loading attendance",
  "يتم تحميل سجلات الحضور الفعلية لهذا الشهر.": "Loading the actual attendance records for this month.",
  "جاري تحميل سجل حضور الموظفة": "Loading staff attendance",
  "تعذر تحميل سجل الحضور": "Could not load attendance records",
  "تعذر تحميل سجل حضور الموظفة. أعد المحاولة بعد التحقق من الاتصال.": "Could not load the staff attendance record. Check the connection and try again.",
  "لا توجد بصمات أو إجازات معتمدة في الشهر المحدد.": "There are no attendance records or approved leave entries in the selected month.",
  "اضغطي على أي يوم مسجل لفتح تفاصيله.": "Select any recorded day to open its details.",
  "تأخير": "Late",
  "نقص ساعات": "Missing hours",
  "غير مكتمل": "Incomplete",
  "غياب": "Absent",
  "دوام في راحة أسبوعية": "Worked on weekly day off",
  "فترة الاستئذان": "Permission period",
  "تفاصيل اليوم المحدد": "Selected day details",
  "إلغاء الاستئذان": "Cancel permission",
  "إلغاء الإجازة": "Cancel leave",
  "تفاصيل يوم الحضور": "Attendance day details",
  "عرض البصمات والشفت والموقع والمراجعات.": "View attendance punches, shift, location, and review details.",
  "الدخول": "Check-in",
  "الخروج": "Check-out",
  "الحدث": "Event",
  "دخول": "Check-in",
  "خروج": "Check-out",
  "غير مسجل": "Not recorded",
  "ملاحظة المراجعة": "Review note",
  "سجل الشهر": "Monthly record",
  "السجلات المحملة للموظفة في الشهر الحالي.": "Attendance records loaded for this staff member in the current month.",
  "اليوم": "Day",
  "إجراء": "Action",
  "لا توجد سجلات حضور في هذا الشهر.": "There are no attendance records for this month.",
  "هيكل الراتب، إعدادات الدوام، وتصنيف التأمينات التي يستخدمها مسير الرواتب.": "Salary structure, work settings, and insurance classification used by payroll.",
  "الإضافي مفعّل": "Overtime enabled",
  "الإضافي متوقف": "Overtime disabled",
  "حفظ إعدادات الراتب والتأمينات": "Save payroll & insurance settings",
  "هيكل الراتب والدوام": "Salary & work structure",
  "الراتب الأساسي والبدلات محفوظة كعناصر مستقلة؛ إجمالي الراتب التعاقدي يُحسب تلقائيًا من مجموعها.": "Base salary and allowances are stored separately; total contractual salary is calculated automatically.",
  "الراتب الأساسي": "Base salary",
  "بدل السكن": "Housing allowance",
  "بدل النقل": "Transport allowance",
  "بدلات أخرى": "Other allowances",
  "ساعات اليوم": "Hours per day",
  "ساعات الشهر": "Hours per month",
  "معامل الإضافي": "Overtime multiplier",
  "سياسة الحضور للراتب": "Payroll attendance policy",
  "يعتمد على البصمة": "Attendance required",
  "معفى من البصمة — راتب حسب الجدول": "Attendance exempt — salary based on schedule",
  "سبب الإعفاء": "Exemption reason",
  "مثال: موظف إداري / إدارة": "Example: administrative employee / management",
  "معفى من البصمة — الجدول يبقى معتمدًا": "Attendance exempt — schedule remains authoritative",
  "الإعفاء يلغي شرط البصمة والتأخير والخروج المبكر من الراتب فقط. جدول الدوام الرسمي يبقى مصدر أيام وساعات العمل والفترة والإجازات والغياب المسجل.": "The exemption removes attendance, lateness, and early-leave deductions from payroll only. The official schedule remains the source for working days, hours, periods, leave, and recorded absence.",
  "طريقة الخصم": "Deduction method",
  "حسب اليوم": "By day",
  "حسب الساعة": "By hour",
  "بدون خصم تلقائي": "No automatic deduction",
  "إجمالي الراتب التعاقدي": "Total contractual salary",
  "مكونات الراتب": "Salary components",
  "أساسي + سكن + نقل + بدلات أخرى": "Base + housing + transport + other allowances",
  "تفعيل احتساب الإضافي": "Enable overtime calculation",
  "يعتمد على إعدادات الراتب والشفتات الحالية.": "Uses the current payroll and shift settings.",
  "التأمينات الاجتماعية (GOSI)": "Social Insurance (GOSI)",
  "التصنيف والسياسة محفوظان مع تاريخ السريان؛ الحساب المالي نفسه ينفذه محرك GOSI المركزي عند إنشاء المسير.": "Classification and policy are stored with an effective date; the central GOSI engine performs the financial calculation when payroll is generated.",
  "تصنيف التأمينات": "Insurance classification",
  "سعودي — مشترك بالنظام القائم": "Saudi — existing system",
  "سعودي — النظام الجديد": "Saudi — new system",
  "خليجي — مد الحماية": "GCC national — protection extension",
  "غير سعودي": "Non-Saudi",
  "تاريخ سريان التصنيف": "Classification effective date",
  "سبب / ملاحظة التصنيف": "Classification reason / note",
  "مثال: حسب سجل الاشتراك أو مستند الموظفة": "Example: based on contribution record or staff document",
  "طريقة أجر الاشتراك": "Contribution wage method",
  "تلقائي من العناصر النظامية": "Automatic from statutory components",
  "أجر اشتراك معتمد يدويًا": "Approved manual contribution wage",
  "أجر الاشتراك المعتمد": "Approved contribution wage",
  "سبب الأجر المعتمد": "Reason for approved wage",
  "لماذا يختلف عن الاحتساب التلقائي؟": "Why does it differ from automatic calculation?",
  "دولة الموظفة الخليجية": "GCC nationality country",
  "مثال: KW / AE / BH / OM / QA": "Example: KW / AE / BH / OM / QA",
  "إعداد التأمينات غير مكتمل": "Insurance setup incomplete",
  "لن يمكن اعتماد مسير الراتب حتى يكتمل تصنيف التأمينات وتاريخ السريان وأي بيانات مطلوبة لأجر الاشتراك.": "Payroll cannot be approved until the insurance classification, effective date, and required contribution-wage data are complete.",
  "إعداد التأمينات مكتمل": "Insurance setup complete",
  "بيانات التصنيف وأجر الاشتراك جاهزة للحساب المركزي عند إنشاء مسير الرواتب.": "Classification and contribution-wage data are ready for central calculation when payroll is generated.",
  "أجر الاشتراك يُحسب تلقائيًا": "Contribution wage is calculated automatically",
  "لا تدخل نسبة Pension أو SANED يدويًا. محرك GOSI المركزي يحدد السياسة الفعالة حسب تصنيف الموظفة وتاريخ المسير، ويحتفظ بالـSnapshot المستخدم.": "Do not enter Pension or SANED percentages manually. The central GOSI engine selects the effective policy based on classification and payroll date and stores the calculation snapshot.",
  "Override موثق": "Documented override",
  "استخدم الأجر المعتمد يدويًا فقط عندما يكون لديك أجر اشتراك موثق مختلف، ويجب تسجيل السبب حتى يمكن فهم الحركة مستقبلًا.": "Use a manual approved contribution wage only when a different documented wage exists, and record the reason for auditability.",
  "الخليجي مستقل عن غير السعودي": "GCC classification is separate from Non-Saudi",
  "لن يحوله النظام إلى Non-Saudi تلقائيًا. يبقى اعتماد الراتب متوقفًا حتى تكتمل بيانات وسياسة مد الحماية.": "The system will not automatically convert GCC staff to Non-Saudi. Payroll approval remains blocked until protection-extension data and policy are complete.",
  "يرتبط هذا التبويب بوحدة تشغيل مستقلة داخل النظام.": "This tab is linked to an independent operational module.",
  "لا توجد ملاحظات إضافية": "No additional notes",
  "سيتم عرض البيانات عند ربط الوحدة المباشرة بهذا التبويب.": "Data will appear when the corresponding live module is connected to this tab.",
  "يناير": "January",
  "فبراير": "February",
  "مارس": "March",
  "أبريل": "April",
  "مايو": "May",
  "يونيو": "June",
  "يوليو": "July",
  "أغسطس": "August",
  "سبتمبر": "September",
  "أكتوبر": "October",
  "نوفمبر": "November",
  "ديسمبر": "December",
  "لا توجد سجلات لهذا الشهر": "No records for this month",
  "ستظهر البصمات والإجازات تلقائياً عند توفرها من نظام الحضور.": "Attendance and approved leave will appear automatically when available.",
  "دليل ألوان التقويم": "Calendar legend",
  "دوام في راحة": "Worked on day off",
  "إجازة تعويضية": "Compensatory leave",
  "إجازة سنوية": "Annual leave",
  "إجازة استثنائية": "Exceptional leave",
  "وقت الدخول": "Check-in time",
  "وقت الخروج": "Check-out time",
  "الشفت الفعلي": "Effective shift",
  "مصدر الشفت": "Shift source",
  "حالة الشفت": "Shift status",
  "سماحية التأخير": "Late grace",
  "الموقع": "Location",
  "السجلات": "Records",
  "الملاحظات": "Notes",
  "حذف البصمة": "Delete attendance",
  "تسجيل إجازة أو استئذان": "Record leave or permission",
  "إغلاق": "Close",
  "الخروج المبكر": "Early leave",
  "يُحسب من أول دقيقة": "Calculated from the first minute",
  "تعديل": "Edit",
  "حذف": "Delete",
  "غير متاح": "Unavailable",
  "الدوام المعتمد غير متاح": "Effective schedule unavailable",
  "يوم راحة": "Day off",
  "إجازة معتمدة": "Approved leave",
  "الإجازة المعتمدة من Core": "Approved leave from Core",
  "جاري فحص الشفت المعتمد…": "Checking the effective shift...",
  "جاري التحقق": "Verifying",
  "لم يسجل بعد": "Not recorded yet",
  "إجازة مرضية": "Sick leave",
  "استئذان / اضطراري": "Permission / emergency",
  "إجازة بدون راتب": "Unpaid leave",
  "طلب إداري": "Administrative request",
  "مقبول": "Approved",
  "مرفوض": "Rejected",
  "ملغي": "Cancelled",
  "معلق": "Pending",
  "الطلبات المقبولة": "Approved requests",
  "الطلبات المرفوضة": "Rejected requests",
  "الطلبات الملغية": "Cancelled requests",
  "كل الطلبات": "All requests",
  "الطلبات المعلقة": "Pending requests",
  "تعذر تحميل طلبات الموظفة.": "Could not load staff requests.",
  "تعذر تحديد مستخدم الإدارة للمراجعة.": "Could not identify the management user for review.",
  "قبول": "Approve",
  "رفض": "Reject",
  "تم قبول الطلب.": "Request approved.",
  "تم رفض الطلب.": "Request rejected.",
  "تم إلغاء الطلب.": "Request cancelled.",
  "تعذر تحديث حالة الطلب.": "Could not update request status.",
  "مراجعة الطلبات والمرفقات والملاحظات الإدارية وسجل الإجراءات.": "Review requests, attachments, management notes, and action history.",
  "جاهزة": "Ready",
  "تعذر تحديث الطلبات": "Could not refresh requests",
  "احتفظنا بالطلبات الحالية. أعد المحاولة بعد التحقق من الاتصال.": "Current requests were preserved. Check the connection and try again.",
  "تم تحديث الطلب": "Request updated",
  "تصفية الطلبات": "Request filters",
  "اختيار حالة الطلب للعرض فقط، أما حالة البيانات فتظهر تلقائيًا.": "Choose a request status for display; data status is determined automatically.",
  "حالة الطلب": "Request status",
  "المعلقة": "Pending",
  "المقبولة": "Approved",
  "المرفوضة": "Rejected",
  "الملغية": "Cancelled",
  "جاري تحميل الطلبات": "Loading requests",
  "يتم جلب طلبات الموظفة الفعلية.": "Loading the staff member's actual requests.",
  "جاري تحميل طلبات الموظفة": "Loading staff requests",
  "تعذر تحميل الطلبات": "Could not load requests",
  "احتفظنا بالطلبات الحالية إن وجدت. أعد المحاولة بعد التحقق من الاتصال.": "Existing requests were preserved. Check the connection and try again.",
  "لا توجد طلبات مطابقة للبيانات الحالية.": "No requests match the current data.",
  "الرقم": "Number",
  "النوع": "Type",
  "تاريخ التقديم": "Submission date",
  "الفترة المطلوبة": "Requested period",
  "السبب": "Reason",
  "المرفقات": "Attachments",
  "الإجراءات": "Actions",
  "لا توجد طلبات في هذه الحالة.": "No requests in this status.",
  "بدون مرفقات": "No attachments",
  "ملاحظات الإدارة": "Management notes",
  "ملاحظة مرتبطة بآخر إجراء على الطلب.": "Note associated with the latest request action.",
  "الملاحظة": "Note",
  "اكتب سبب القبول أو الرفض أو أي توجيه للموظفة...": "Enter the reason for approval/rejection or any guidance for the staff member...",
  "سجل الإجراءات": "Action history",
  "تسلسل زمني لا يمكن تعديله.": "Read-only chronological history.",
  "بواسطة الموظفة": "By staff member",
  "بانتظار الإجراء": "Awaiting action",
  "لم يُسجل بعد": "Not recorded yet",
  "لا توجد طلبات معلقة": "No pending requests",
  "الآن": "Now",
  "الموظفة": "Staff member",
  "تعذر تحميل رسائل الموظفة.": "Could not load staff messages.",
  "تعذر تحديد مستخدم الإدارة للإرسال.": "Could not identify the management user for sending.",
  "تعذر تحديد الموظفة للإرسال.": "Could not identify the staff member for sending.",
  "اكتب نص الرسالة قبل الإرسال.": "Enter a message before sending.",
  "تم إرسال الرسالة.": "Message sent.",
  "تعذر إرسال الرسالة.": "Could not send message.",
  "تم تعليم المحادثة كمقروءة.": "Conversation marked as read.",
  "تعذر تعليم المحادثة كمقروءة.": "Could not mark the conversation as read.",
  "محادثة موجودة": "Conversation available",
  "لا توجد رسائل": "No messages",
  "محادثة داخلية كاملة بحالة الموظفة والقراءة والمرفقات وإعادة محاولة الإرسال.": "Complete internal conversation with staff status, read state, attachments, and retry support.",
  "تعذر تحديث المحادثة": "Could not refresh conversation",
  "احتفظنا بالرسائل الحالية. أعد المحاولة بعد التحقق من الاتصال.": "Current messages were preserved. Check the connection and try again.",
  "تم تحديث المحادثة": "Conversation updated",
  "حالة المحادثة": "Conversation status",
  "تظهر تلقائيًا حسب تحميل البيانات ووجود الرسائل.": "Determined automatically from loading state and available messages.",
  "لا توجد رسائل بعد": "No messages yet",
  "المحادثة الداخلية": "Internal conversation",
  "جاري تحميل رسائل الموظفة وسجل القراءة.": "Loading staff messages and read history.",
  "جاري تحميل رسائل الموظفة": "Loading staff messages",
  "تعذر تحميل المحادثة": "Could not load conversation",
  "احتفظنا بالرسائل الحالية إن وجدت. أعد المحاولة بعد التحقق من الاتصال.": "Existing messages were preserved. Check the connection and try again.",
  "الرسائل محفوظة ضمن ملف الموظفة وسجل الإدارة.": "Messages are stored in the staff profile and management record.",
  "لا يوجد معرف موظفة": "No staff ID",
  " · مرسلة ✓": " · Sent ✓",
  " · غير مقروءة": " · Unread",
  " · مقروءة": " · Read",
  "كتابة رسالة": "Write message",
  "إرسال رسالة إدارية مباشرة إلى هذه الموظفة.": "Send an internal management message directly to this staff member.",
  "نص الرسالة": "Message",
  "اكتب رسالة داخلية للموظفة...": "Write an internal message to the staff member...",
  "جارٍ الإرسال": "Sending",
  "إرسال": "Send",
  "إدارة المحادثة": "Conversation management",
  "إجراءات السجل والحالة غير المقروءة.": "Record actions and unread status.",
  "هوية": "Identity",
  "عقود": "Contracts",
  "شهادات": "Certificates",
  "أخرى": "Other",
  "كل المستندات": "All documents",
  "محذوف": "Deleted",
  "مستبدل": "Replaced",
  "منتهي": "Expired",
  "قريب الانتهاء": "Expiring soon",
  "مقروء": "Read",
  "ساري": "Valid",
  "تعذر تحميل ملفات الموظفة من Core.": "Could not load staff files from Core.",
  "حجم الملف أكبر من 10 ميجابايت.": "File size exceeds 10 MB.",
  "اكتب اسم المستند قبل الحفظ.": "Enter a document name before saving.",
  "تعذر تحديد الموظفة لإضافة الملف.": "Could not identify the staff member for file upload.",
  "اختر الملف من الجهاز قبل الحفظ.": "Choose a file from the device before saving.",
  "تم رفع النسخة الجديدة وربطها بالمستند السابق.": "The new version was uploaded and linked to the previous document.",
  "تم رفع المستند إلى Core D1 / R2.": "Document uploaded to Core D1 / R2.",
  "تعذر رفع الملف إلى Core/R2.": "Could not upload the file to Core/R2.",
  "تم تسجيل حالة الملف كمقروءة في Core.": "File marked as read in Core.",
  "تعذر تسجيل حالة القراءة.": "Could not update read status.",
  "تم تسجيل الملفات النشطة كمقروءة في Core.": "Active files marked as read in Core.",
  "تعذر تحديث حالات قراءة الملفات.": "Could not update file read statuses.",
  "نسخة مستند محدثة": "Updated document version",
  "المستندات والسجل": "Documents & history",
  "إدارة المستندات النشطة والنسخ المستبدلة والمؤرشفة من Core D1 وR2 ضمن مركز موحد.": "Manage active documents, replaced versions, and archived records from Core D1 and R2 in one workspace.",
  "ملف قريب الانتهاء": "Document expiring soon",
  "السارية": "Valid",
  "المنتهية": "Expired",
  "تعذر تنفيذ العملية": "Could not complete the action",
  "تم تحديث الملفات": "Files updated",
  "تصنيفات المستندات": "Document categories",
  "تصفية القائمة حسب النوع.": "Filter the list by document type.",
  "تصنيفات الملفات": "File categories",
  "الهوية": "Identity",
  "العقود": "Contracts",
  "الشهادات": "Certificates",
  "رفع ملف": "Upload file",
  "السحب والإفلات أو اختيار ملف من الجهاز — حتى 10 ميجابايت.": "Drag and drop or choose a file from the device — up to 10 MB.",
  "أفلِت الملف هنا": "Drop the file here",
  "اسحب الملف وأفلته هنا": "Drag and drop the file here",
  "أو اضغط لاختيار ملف": "or click to choose a file",
  "رفع النسخة البديلة": "Upload replacement version",
  "رفع مستند جديد": "Upload new document",
  "قائمة المستندات": "Document list",
  "الفتح والتنزيل يمران عبر Core Files API بمصادقة كاملة ولا يتم استخدام روابط تخزين مباشرة.": "Opening and downloading go through the authenticated Core Files API; direct storage links are not used.",
  "التصنيف": "Category",
  "اسم المستند": "Document name",
  "تاريخ الرفع": "Upload date",
  "تاريخ الانتهاء": "Expiry date",
  "لا توجد مستندات في هذا التصنيف.": "No documents in this category.",
  "جاري تحميل ملفات الموظفة": "Loading staff files",
  "تعذر تحميل الملفات": "Could not load files",
  "تعذر الوصول إلى Core/R2. لم يتم استخدام أي Firestore fallback.": "Could not access Core/R2. No Firestore fallback was used.",
  "بيانات النسخة البديلة": "Replacement version details",
  "بيانات مستند": "Document details",
  "بيانات المستند تحفظ في D1 والملف نفسه يرفع إلى R2.": "Document metadata is stored in D1 and the file itself is uploaded to R2.",
  "شهادة صحية": "Health certificate",
  "عقد": "Contract",
  "شهادة": "Certificate",
  "الملف المختار": "Selected file",
  "اختر ملفًا من منطقة الرفع": "Choose a file from the upload area",
  "يلزم التجديد قبل انتهاء الصلاحية": "Renewal is required before expiry",
  "غير متوفر": "Unavailable",
  "إجازة / خصم": "Leave / deduction",
  "إضافة": "Addition",
  "سنوية مدفوعة": "Paid annual leave",
  "مرضية مدفوعة": "Paid sick leave",
  "طارئة مدفوعة": "Paid emergency leave",
  "راحة معتمدة": "Approved rest",
  "راحة أسبوعية تعويضية": "Compensatory weekly rest",
  "إجازة أخرى": "Other leave",
  "على إجازة": "On leave",
  "إجازة قادمة": "Upcoming leave",
  "حالة الإعداد": "Setup status",
  "راتب اليوم": "Daily salary",
  "راتب الساعة": "Hourly salary",
  "إجمالي الشهر": "Monthly total",
  "الإيراد": "Revenue",
  "أجر الاشتراك في GOSI": "GOSI contribution wage",
  "غير محسوب": "Not calculated",
  "خصم الموظفة GOSI": "Staff GOSI deduction",
  "نسبة خصم الموظفة GOSI": "Staff GOSI deduction rate",
  "غير محسوبة": "Not calculated",
  "نسبة مساهمة المنشأة GOSI": "Employer GOSI contribution rate",
  "مساهمة المنشأة GOSI": "Employer GOSI contribution",
  "مصدر أجر الاشتراك": "Contribution wage source",
  "سياسة GOSI": "GOSI policy",
  "حساب GOSI غير جاهز": "GOSI calculation not ready",
  "الموظفة مصنفة خليجية. لا يتم تحويلها تلقائيًا إلى غير سعودية؛ يجب استكمال سياسة مد الحماية قبل اعتماد الراتب.": "The staff member is classified as GCC. The system will not convert this classification to Non-Saudi automatically; protection-extension policy must be completed before payroll approval.",
  "تم تطبيق حد على أجر الاشتراك": "Contribution wage limit applied",
  "أجر الاشتراك المدخل أقل من الحد الأدنى المطبق في سياسة GOSI الحالية، لذلك استخدم المحرك الحد الأدنى.": "The entered contribution wage is below the current GOSI policy minimum, so the engine applied the minimum.",
  "أجر الاشتراك المدخل أعلى من الحد الأعلى المطبق في سياسة GOSI الحالية، لذلك استخدم المحرك الحد الأعلى.": "The entered contribution wage is above the current GOSI policy maximum, so the engine applied the maximum.",
  "إعداد الراتب غير مكتمل": "Payroll setup incomplete",
  "الإجازات والراحة": "Leave & rest",
  "مرجع واحد للإجازة السنوية والراحة الأسبوعية والراحة التعويضية والاستدعاءات التشغيلية.": "One reference for annual leave, weekly rest, compensatory rest, and operational recalls.",
  "تفاصيل الإجازة والرصيد السنوي": "Leave details & annual balance",
  "التفاصيل الإدارية الحالية تبقى هنا منفصلة عن الراحة الأسبوعية والتعويضية.": "Current administrative details remain separate from weekly and compensatory rest.",
  "الرصيد الحالي": "Current balance",
  "بداية الإجازة": "Leave start",
  "نهاية الإجازة": "Leave end",
  "نوع الإجازة": "Leave type",
  "سجل الحركات": "Transaction history",
  "حالة الإجازة الحالية": "Current leave status",
  "الإجازات هنا معتمدة ومرتبطة بالحضور والراتب.": "Leave shown here is approved and linked to attendance and payroll.",
  "لا توجد إجازة فعالة": "No active leave",
  "تاريخ غير محدد": "Date not specified",
  "سجّل إجازة جديدة ليتم اعتمادها وإظهارها في الحضور وربط أثرها بالراتب.": "Record a new leave request so it can be approved, reflected in attendance, and linked to payroll.",
  "الأثر المالي يُحدد حسب النوع": "Financial impact depends on leave type",
  "الإجازات السنوية والمرضية والطارئة تظهر في الحضور ولا تخصم من الراتب، بينما الإجازة بدون راتب تظهر كإجازة معتمدة ويُخصم مقابل أيامها من الراتب.": "Annual, sick, and emergency leave appears in attendance without salary deduction; unpaid leave is approved leave whose days are deducted from payroll.",
  "انتهى تاريخ الإجازة": "Leave period ended",
  "يمكن إنهاء الحالة الحالية أو تسجيل إجازة جديدة بمدى زمني صحيح.": "You can end the current state or record a new leave with a valid date range.",
  "تاريخ الاستحقاق وتعديل الرصيد.": "Entitlement date and balance adjustments.",
  "تاريخ الاستحقاق": "Entitlement date",
  "تاريخ الحركة": "Transaction date",
  "عدد الأيام": "Number of days",
  "سبب الحركة": "Transaction reason",
  "سجل حركات الإجازات": "Leave transaction history",
  "آخر 12 حركة محفوظة.": "Latest 12 saved transactions.",
  "التاريخ": "Date",
  "التغيير": "Change",
  "قبل": "Before",
  "بعد": "After",
  "جاري تحميل السجل...": "Loading history...",
  "لا توجد حركات إجازات محفوظة.": "No saved leave transactions.",
  "الملغاة": "Cancelled",
  "تعديل هذا التعيين": "Edit this assignment",
  "إنهاء اليوم": "End today",
  "قوالب الشفتات والاستثناءات": "Shift templates & exceptions",
  "أنشئ القوالب وسياسات الحضور هنا، ثم وزّعها على أيام الأسبوع من جدول الدوام الموجود في نفس الصفحة.": "Create shift templates and attendance policies here, then assign them to weekdays using the work schedule on this page.",
  "شرح قوالب الشفتات والاستثناءات": "Explain shift templates & exceptions",
  "تم التحديث": "Updated",
  "تغييرات تمس فترة رواتب مقفلة": "Changes affecting a locked payroll period",
  "اترك هذا الخيار مغلقًا في الوضع الطبيعي. فعّله فقط عندما تريد السماح لـ Core بحفظ التغيير مع إنشاء تسوية بعد الإقفال بدل تعديل الراتب المقفل بصمت.": "Keep this disabled normally. Enable it only when Core should save a change that affects a locked payroll period and create a post-lock adjustment instead of silently changing locked payroll.",
  "السماح بتسجيل تسوية بعد إقفال الرواتب": "Allow post-lock payroll adjustment",
  "الشفت المطبق الآن": "Effective shift now",
  "هذه هي المعلومة الأساسية: الشفت الذي سيُستخدم في الحضور والراتب لهذا اليوم.": "This is the effective shift that attendance and payroll will use for the selected day.",
  "شرح الشفت المطبق الآن": "Explain effective shift",
  "تاريخ الفحص": "Check date",
  "مفتوح": "Open-ended",
  "مرونة الحضور": "Late grace",
  "إغلاق البصمة": "Attendance lock",
  "غير مفعّل": "Disabled",
  "التعيينات القديمة والاحتياطية": "Legacy & fallback assignments",
  "للتوافق مع البيانات القديمة فقط": "For legacy compatibility only",
  "المصدر الأساسي الآن هو جدول الدوام الأسبوعي. استخدم التعيين الاحتياطي فقط لموظفة قديمة لا يوجد لها جدول أسبوعي، واستخدم الاستثناء لتغيير يوم أو فترة محددة.": "The weekly schedule is now the primary source. Use a fallback assignment only for legacy staff without a complete weekly schedule, and use an exception for a specific day or period.",
  "شرح تعيين الشفت الاحتياطي": "Explain fallback shift assignment",
  "وضع التعديل نشط": "Edit mode active",
  "التعديل الآن على التعيين الذي اخترته من جدول تعيينات الموظفة. اضغط حفظ التعديل أو إلغاء التعديل.": "You are editing the assignment selected from the staff assignment table. Save the change or cancel edit mode.",
  "الشفت المطلوب": "Required shift",
  "يبدأ من": "Starts on",
  "المدة": "Duration",
  "دائم / مفتوح": "Permanent / open-ended",
  "مؤقت / له نهاية": "Temporary / has end date",
  "ينتهي في": "Ends on",
  "تعيين مفتوح": "Open-ended assignment",
  "عند اختيار دائم يتم تجاهل تاريخ النهاية وحفظ التعيين كمفتوح. إذا تحتاج نهاية محددة اختر مؤقت.": "For a permanent assignment, the end date is ignored and the assignment stays open-ended. Choose temporary if an end date is required.",
  "سبب التغيير": "Reason for change",
  "تأثير الحفظ المتوقع": "Expected save impact",
  "إلغاء التعديل": "Cancel editing",
  "تعيينات الموظفة": "Staff shift assignments",
  "يعرض الحالي والقادم فقط. السجل القديم موجود أسفل الجدول لتقليل التشويش.": "Shows current and upcoming assignments only. Historical records are available below to reduce clutter.",
  "شرح تعيينات الموظفة": "Explain staff shift assignments",
  "لا يوجد شفت نشط أو قادم لهذه الموظفة.": "There is no active or upcoming fallback shift for this staff member.",
  "لا يوجد سجل تاريخي.": "No historical records.",
  "لا توجد تعيينات ملغية.": "No cancelled assignments.",
  "إدارة قوالب الشفتات والاستثناءات": "Manage shift templates & exceptions",
  "القالب عام ويؤثر على أي موظفة تستخدمه. لا تعدله إلا إذا تريد تغيير القالب نفسه للجميع.": "A template is shared and affects every staff member using it. Edit it only when the shared template itself should change.",
  "شرح إنشاء قالب الشفت": "Explain shift template creation",
  "تنبيه": "Notice",
  "لتغيير شفت يوم أسبوعي استخدم جدول الدوام أعلى هذه الصفحة. لتغيير يوم أو فترة محددة استخدم الاستثناء؛ تعديل القالب يغيّر السياسة العامة لكل من يستخدمه.": "Use the weekly schedule above to change a weekday shift. Use an exception for a specific day or period; editing a template changes the shared policy for everyone using it.",
  "اسم الشفت": "Shift name",
  "الشفت الصباحي": "Morning shift",
  "الكود": "Code",
  "البداية": "Start",
  "النهاية": "End",
  "مدة الاستراحة (دقيقة)": "Break duration (min)",
  "بدء الإضافي بعد (دقيقة)": "Overtime starts after (min)",
  "فترة سماح التأخير": "Late grace period",
  "إغلاق بصمة الحضور بعد": "Lock check-in after",
  "لا يوجد سماح خروج مبكر": "No early-leave grace",
  "الخروج قبل نهاية الشفت يُحسب من أول دقيقة. سماح التأخير مرونة للحضور فقط، ويجب تعويض التأخير عند الانصراف.": "Leaving before the shift ends is counted from the first minute. Late grace applies to check-in only, and late minutes must be compensated at check-out.",
  "إغلاق بصمة الحضور المتأخرة": "Lock late check-in",
  "عند تجاوز المدة المحددة تُقفل بصمة الحضور وتُسجل الموظفة غائبة تلقائيًا، بينما يبقى تسجيل الانصراف متاحًا لمن بصمت حضورًا.": "After the configured period, check-in is locked and the staff member is automatically marked absent; check-out remains available for staff who already checked in.",
  "القالب نشط": "Template active",
  "تفريغ": "Clear form",
  "حفظ القالب": "Save template",
  "استثناء شفت": "Shift exception",
  "استخدمه لراحة يوم، شفت بديل، أو وقت مخصص لفترة محددة.": "Use this for a day off, alternate shift, or custom hours for a specific period.",
  "شرح استثناء الشفت": "Explain shift exception",
  "نوع الاستثناء": "Exception type",
  "الشفت البديل": "Alternate shift",
  "من تاريخ": "From date",
  "إلى تاريخ": "To date",
  "بداية مخصصة": "Custom start",
  "نهاية مخصصة": "Custom end",
  "تأثير الاستثناء المتوقع": "Expected exception impact",
  "حفظ الاستثناء": "Save exception",
  "القوالب الفعلية المحملة من Core.": "Canonical templates loaded from Core.",
  "شرح قائمة قوالب الشفتات": "Explain shift template list",
  "نشط": "Active",
  "تعديل القالب": "Edit template",
  "لا توجد قوالب شفتات.": "No shift templates.",
  "استثناءات الموظفة": "Staff exceptions",
  "الأولوية للاستثناء قبل الشفت الأساسي.": "Exceptions take priority over the base shift.",
  "فلتر الاستثناءات": "Exception filter",
  "شرح استثناءات الموظفة": "Explain staff exceptions",
  "لا توجد استثناءات شفت لهذه الموظفة.": "There are no shift exceptions for this staff member.",
  "قابل للتعديل": "Editable",
  "مفعّل": "Enabled",
  "لا يوجد دوام مطلوب": "No work required",
  "وقت الدوام الفعلي": "Effective working time",
  "إغلاق بصمة الحضور فقط؛ الانصراف يبقى متاحًا": "Only check-in is locked; check-out remains available",
  "تسمح بالحضور المتأخر، لكن الدقائق غير المعوضة تُحسب": "Late check-in is allowed within the grace window, but uncompensated minutes are still counted",
  "إنشاء مصدر وقت الدوام وسياساته، ثم معالجة الحالات المؤقتة دون كسر الجدول الأساسي.": "Create a canonical source for working hours and attendance policies, then handle temporary cases without changing the base schedule.",
  "قالب الشفت هو التعريف المركزي ليوم العمل: اسمه، وقت بدايته ونهايته، فترة سماح التأخير، وإمكانية إغلاق بصمة الحضور بعد مدة محددة. بعد إنشاء القالب يتم توزيعه على الموظفات وأيام الأسبوع. أما الاستثناء فيتقدم على الجدول لفترة قصيرة فقط، ثم يعود النظام تلقائيًا إلى الجدول الأساسي.": "A shift template is the central definition of a workday: name, start and end times, late grace, and optional check-in locking after a configured period. Templates are assigned to staff and weekdays. Exceptions temporarily override the schedule, after which the base schedule resumes automatically.",
  "تريد إنشاء شفت صباحي أو مسائي يُستخدم أكثر من مرة، تعديل سياسة حضور مشتركة، أو تسجيل تغيير مؤقت مثل رمضان أو تدريب.": "Use this when creating reusable morning/evening shifts, changing a shared attendance policy, or recording a temporary change such as Ramadan hours or training.",
  "تغيير يوم راحة أسبوعية ثابت أو تسجيل إجازة سنوية/مرضية؛ يوم الراحة من الأسبوع التشغيلي والإجازة من رصيد الإجازات.": "Do not use this for a permanent weekly day off or annual/sick leave; weekly rest belongs in the operational week and leave belongs in the leave system.",
  "شفت مسائي مع دوام رمضان": "Evening shift with Ramadan hours",
  "الدوام العادي 3:00 م إلى 11:00 م، سماح التأخير 15 دقيقة، وإغلاق بصمة الحضور بعد 30 دقيقة. في رمضان فقط يصبح الدوام 2:00 م إلى 10:00 م.": "Normal hours are 3:00 PM to 11:00 PM, with 15 minutes late grace and check-in locked after 30 minutes. During Ramadan only, hours become 2:00 PM to 10:00 PM.",
  "أنشئ قالب «المسائي» بالسياسات العادية ووزعه على أيام الموظفة. لرمضان أنشئ استثناءً للفترة المطلوبة بساعات 2:00 م إلى 10:00 م بدل تعديل القالب العام.": "Create the Evening template with normal policies and assign it to the staff schedule. For Ramadan, create an exception for the required period with 2:00 PM to 10:00 PM hours instead of editing the shared template.",
  "تستخدم جميع الأيام العادية القالب المسائي، وتستخدم أيام رمضان وقت الاستثناء فقط، ثم يعود الدوام تلقائيًا إلى 3:00 م بعد انتهاء الفترة.": "Normal days use the evening template, Ramadan dates use only the exception hours, and the schedule automatically returns to 3:00 PM after the exception ends.",
  "أنشئ القالب": "Create the template",
  "حدد اسم الشفت ووقته وسياسة التأخير وإغلاق بصمة الحضور.": "Set the shift name, hours, late policy, and check-in lock policy.",
  "وزّعه على الجدول": "Assign it to the schedule",
  "ارجع للأسبوع التشغيلي واختر القالب لأيام عمل الموظفة.": "Return to the operational week and select the template for the staff member's working days.",
  "استخدم الاستثناء عند الحاجة": "Use an exception when needed",
  "لراحة يوم أو شفت بديل أو وقت مؤقت استخدم الاستثناء بدل تعديل القالب العام.": "For a day off, alternate shift, or temporary hours, use an exception instead of changing the shared template.",
  "راجع الشفت المطبق": "Review the effective shift",
  "اختر تاريخًا وتأكد من المصدر والوقت النهائي قبل الاعتماد.": "Choose a date and verify the source and final hours before approving the setup.",
  "تعديل قالب مستخدم ينعكس على كل الموظفات والأيام المرتبطة به؛ لا تعدله لمعالجة حالة تخص موظفة أو يومًا واحدًا.": "Editing a template affects every staff member and day linked to it; do not edit a shared template to handle one staff member or one day.",
  "معاينة النتيجة النهائية التي سيستخدمها الحضور والراتب في تاريخ محدد.": "Preview the final result attendance and payroll will use on a selected date.",
  "يجمع هذا القسم جميع المصادر ويعرض القرار النهائي لليوم: يبدأ بالاستثناء إن وجد، ثم جدول الأسبوع، ثم التعيين الاحتياطي للبيانات القديمة. يوضح أيضًا وقت البداية والنهاية وسياسة التأخير وإغلاق البصمة، حتى تعرف بالضبط لماذا ظهر اليوم بهذا الشكل.": "This section resolves all sources into the final result for the day: exception first, then weekly schedule, then legacy fallback assignment. It also shows start/end times, late grace, and check-in lock policy so the effective result is explainable.",
  "تلاحظ أن يومًا ظهر بوقت غير متوقع، تريد التأكد من أولوية استثناء، أو تراجع سبب احتساب تأخير أو غياب.": "Use this when a day shows unexpected hours, when checking exception priority, or when reviewing why lateness or absence was calculated.",
  "إجراء التعديل نفسه؛ هذه شاشة تحقق ومعاينة، والتعديل يتم من القالب أو الأسبوع التشغيلي أو الاستثناء.": "This is not where the source is edited; it is a verification view. Make changes in the template, operational week, or exception.",
  "استثناء يتقدم على الجدول": "Exception overrides the schedule",
  "الثلاثاء في الجدول الأسبوعي مرتبط بالشفت المسائي 3:00 م إلى 11:00 م، لكن يوجد استثناء تدريب في نفس التاريخ من 10:00 ص إلى 2:00 م.": "Tuesday is assigned to the evening shift from 3:00 PM to 11:00 PM, but a training exception exists on the same date from 10:00 AM to 2:00 PM.",
  "اختر تاريخ الثلاثاء في «الشفت المطبق الآن» وراجع خانة المصدر والوقت.": "Select Tuesday in Effective shift now and review the source and time.",
  "سيظهر المصدر «استثناء» والوقت 10:00 ص إلى 2:00 م؛ لأن الاستثناء أعلى أولوية. بعد انتهاء الاستثناء يعود الثلاثاء إلى الشفت المسائي.": "The source will show Exception and the time will be 10:00 AM to 2:00 PM because the exception has higher priority. After it ends, Tuesday returns to the evening shift.",
  "اختر التاريخ": "Choose the date",
  "حدد اليوم الذي تريد معرفة شفته الفعلي.": "Select the day whose effective shift you want to inspect.",
  "راجع المصدر": "Review the source",
  "تحقق هل النتيجة جاءت من استثناء، جدول أسبوعي، أو تعيين احتياطي.": "Check whether the result came from an exception, weekly schedule, or fallback assignment.",
  "راجع السياسة": "Review the policy",
  "تأكد من وقت الدوام ومرونة الحضور ووقت إغلاق بصمة الحضور.": "Verify working hours, late grace, and check-in lock time.",
  "صحح المصدر": "Correct the source",
  "عند وجود خطأ عدّل المصدر الذي ظهر في المعاينة بدل تغيير سجل الحضور يدويًا.": "If the result is wrong, edit the source shown in the preview instead of manually changing attendance records.",
  "المعاينة لا تحفظ أي تغيير؛ هدفها تفسير النتيجة النهائية قبل تعديل المصدر الصحيح.": "The preview saves nothing; it explains the effective result before you change the correct source.",
  "تعيين الشفت الاحتياطي": "Fallback shift assignment",
  "مسار توافق للموظفات القديمة التي لا يوجد لها أسبوع تشغيلي مكتمل.": "Compatibility path for legacy staff without a complete operational week.",
  "يحفظ شفتًا افتراضيًا على مستوى الموظفة ويستخدمه فقط عندما لا يجد النظام استثناءً ولا جدولًا أسبوعيًا صالحًا لذلك اليوم. وجوده يمنع ضياع وقت الدوام للبيانات القديمة أثناء الانتقال إلى النظام الجديد، لكنه ليس المسار المفضل للموظفات الجديدة.": "Stores a staff-level fallback shift used only when no exception or valid weekly schedule exists for the day. It protects legacy data during migration but is not the preferred path for new staff.",
  "لديك موظفة قديمة ما زالت بياناتها تعتمد على تعيين شفت عام، أو تحتاج فترة انتقالية قبل استكمال أسبوعها التشغيلي.": "Use this for a legacy staff member still relying on a general shift assignment or during a transition before completing the weekly schedule.",
  "إنشاء جدول موظفة جديدة أو توزيع أيام الراحة؛ استخدم الأسبوع التشغيلي لأنه أوضح وأدق.": "Do not use this to create a new staff schedule or assign weekly rest days; use the operational week.",
  "موظفة قديمة بلا جدول أسبوعي": "Legacy staff without a weekly schedule",
  "ملف موظفة قديم يحتوي حضورًا ورواتب، لكنه لا يحتوي توزيع شفتات لكل يوم.": "A legacy staff record has attendance and payroll history but no weekday shift distribution.",
  "اختر قالب «المسائي»، حدد بداية التطبيق كتعيين دائم، افحص التداخلات ثم احفظ. بعد إنشاء الأسبوع التشغيلي سيصبح هو المصدر الأعلى.": "Choose the Evening template, set the effective start as a permanent assignment, check overlaps, then save. Once a weekly schedule exists, it becomes the higher-priority source.",
  "يستطيع النظام حل وقت الدوام للأيام التي لا يوجد لها جدول، دون أن يمنع الانتقال لاحقًا إلى الأسبوع التشغيلي.": "The system can resolve working hours for days without a weekly schedule without blocking a later transition to the operational week.",
  "اختر القالب": "Choose the template",
  "حدد شفتًا جاهزًا يناسب بيانات الموظفة القديمة.": "Choose an existing shift that matches the legacy staff data.",
  "حدد المدة": "Set the period",
  "اختر دائمًا أو مؤقتًا وحدد بداية ونهاية التطبيق بدقة.": "Choose permanent or temporary and set the effective start and end accurately.",
  "افحص التداخل": "Check overlaps",
  "راجع أي تعيين سابق أو فترة رواتب مقفلة قبل الحفظ.": "Review existing assignments and locked payroll periods before saving.",
  "خطط للانتقال": "Plan the migration",
  "أنشئ الأسبوع التشغيلي عند توفر البيانات ثم أوقف الاعتماد على التعيين الاحتياطي.": "Create the operational week when the data is available, then stop relying on the fallback assignment.",
  "الاستثناء وجدول الأسبوع يتقدمان على هذا التعيين. لا تعتبره بديلًا دائمًا عن توزيع الشفتات الأسبوعي.": "Exceptions and the weekly schedule take priority over this assignment. Do not treat it as a permanent replacement for weekday shift distribution.",
  "عرض سجل تعيينات الشفت الاحتياطية الحالية والقادمة والمنتهية.": "View current, upcoming, and ended fallback shift assignments.",
  "يوضح هذا السجل أي قالب احتياطي عُيّن للموظفة، متى بدأ، متى ينتهي، وما حالته. يفيد في اكتشاف التداخلات، مراجعة سبب استخدام شفت قديم، وإنهاء تعيين لم يعد مطلوبًا دون تعديل قالب الشفت نفسه.": "This history shows which fallback template was assigned, when it starts and ends, and its status. Use it to identify overlaps, understand legacy shift usage, and end assignments without changing the shared template.",
  "تراجع موظفة قديمة، تريد معرفة لماذا استُخدم شفت احتياطي، أو تحتاج إنهاء/تعديل تعيين مؤقت.": "Use this when reviewing legacy staff, investigating why a fallback shift was used, or ending/editing a temporary assignment.",
  "عرض توزيع الشفت اليومي؛ ذلك موجود في الأسبوع التشغيلي، وهذه القائمة تخص التعيينات الاحتياطية فقط.": "Do not use this to view weekday shift distribution; that belongs to the operational week. This list is for fallback assignments only.",
  "تعيين مؤقت ثم عودة للتعيين الدائم": "Temporary assignment followed by the permanent assignment",
  "للموظفة تعيين دائم مسائي، وتم تعيين شفت صباحي مؤقت من 1 إلى 15 أغسطس.": "The staff member has a permanent evening assignment and a temporary morning shift from August 1 to 15.",
  "راجع القائمة للتأكد من أن المؤقت له تاريخ نهاية صحيح ولا يتداخل مع تعيين آخر غير مقصود.": "Review the list to ensure the temporary assignment has the correct end date and no unintended overlap.",
  "يُستخدم الصباحي خلال الفترة المحددة، ثم يعود التعيين الدائم بعد 15 أغسطس إذا لم يوجد أسبوع تشغيلي أو استثناء أعلى أولوية.": "The morning shift is used during the specified period, then the permanent assignment resumes after August 15 if no higher-priority weekly schedule or exception applies.",
  "راجع الحالة": "Review status",
  "نشط يعني مطبق الآن، مجدول يعني سيبدأ لاحقًا، ومنتهٍ يعني انتهت فترته.": "Active means currently effective, Scheduled means it starts later, and Ended means its period has finished.",
  "راجع المدة": "Review the period",
  "تأكد من البداية والنهاية وعدم وجود فجوة أو تداخل غير مقصود.": "Verify the start/end dates and make sure there is no unintended gap or overlap.",
  "عدّل أو أنهِ": "Edit or end",
  "غيّر التعيين نفسه ولا تعدّل القالب العام إذا كانت المشكلة تخص موظفة واحدة.": "Change the assignment itself; do not edit the shared template when the issue applies to one staff member.",
  "وجود تعيين هنا لا يلغي أولوية الاستثناء أو جدول الأسبوع، لذلك راجع «الشفت المطبق الآن» لمعرفة النتيجة النهائية.": "An assignment here does not override exceptions or the weekly schedule. Review Effective shift now to see the final result.",
  "إنشاء قالب شفت": "Create shift template",
  "تعريف وقت يوم العمل وسياسة الحضور مرة واحدة لإعادة استخدامها.": "Define workday hours and attendance policy once so they can be reused.",
  "القالب يجمع كل القواعد المشتركة ليوم العمل في سجل واحد: الاسم، رمز الشفت، وقت البداية والنهاية، مدة الاستراحة، فترة سماح التأخير، وإغلاق بصمة الحضور. عندما تختاره في أي يوم لا يعيد المستخدم كتابة هذه الإعدادات، ويضمن النظام أن الحضور والراتب يستخدمان نفس السياسة.": "A shift template stores the shared workday rules in one record: name, code, start/end times, break duration, late grace, and check-in locking. Selecting the template reuses these settings and keeps attendance and payroll on the same policy.",
  "لديك نمط دوام متكرر مثل صباحي، مسائي، أو شفت رمضان سيُستخدم مع أكثر من موظفة أو أكثر من يوم.": "Use this for recurring patterns such as morning, evening, or Ramadan shifts that will be reused across staff or days.",
  "تغيير ساعات موظفة ليوم واحد أو فترة قصيرة؛ أنشئ استثناءً بدل إنشاء/تعديل قالب عام.": "Do not use this for a one-day or short-term staff change; create an exception instead of changing a shared template.",
  "قالب الشفت المسائي": "Evening shift template",
  "العمل من 3:00 م إلى 11:00 م، فترة سماح التأخير 15 دقيقة، وإغلاق بصمة الحضور بعد 30 دقيقة.": "Working hours are 3:00 PM to 11:00 PM, with 15 minutes late grace and check-in locked after 30 minutes.",
  "أنشئ قالبًا باسم «الشفت المسائي»، أدخل الوقت، اجعل السماح 15، فعّل إغلاق الحضور وأدخل 30. بعد ذلك وزعه على أيام العمل.": "Create an Evening shift template, enter the hours, set late grace to 15, enable the check-in lock and set it to 30, then assign it to working days.",
  "إذا حضرت الموظفة 3:11 وخرجت 11:11 فلا يبقى تأخير غير معوض. إذا خرجت 11:05 يبقى 6 دقائق تأخير. بعد 3:30 تُغلق بصمة الحضور إذا كان الإغلاق مفعلًا، مع بقاء الإدارة قادرة على التصحيح.": "If the staff member checks in at 3:11 PM and out at 11:11 PM, no uncompensated lateness remains. If she checks out at 11:05 PM, 6 minutes remain. After 3:30 PM check-in is locked when enabled, while management can still correct records.",
  "سمّ الشفت": "Name the shift",
  "استخدم اسمًا واضحًا مثل الصباحي 8-4 أو المسائي 3-11.": "Use a clear name such as Morning 8-4 or Evening 3-11.",
  "حدد الوقت": "Set the hours",
  "أدخل بداية ونهاية الدوام الفعليتين، بما في ذلك الشفت الذي يتجاوز منتصف الليل إن كان مدعومًا.": "Enter the actual start and end times, including overnight shifts when supported.",
  "حدد المرونة": "Set late grace",
  "فترة سماح التأخير تسمح بالدخول خلال النافذة، لكنها لا تلغي الدقائق غير المعوضة عند نهاية الدوام.": "Late grace allows check-in within the window but does not erase uncompensated minutes at the end of the shift.",
  "حدد إغلاق البصمة": "Set check-in locking",
  "فعّل الإغلاق وحدد المدة التي بعدها لا تقبل بصمة حضور الموظفة.": "Enable the lock and set how long after shift start employee check-in is no longer accepted.",
  "راجع قبل التوزيع": "Review before assigning",
  "تأكد أن مدة الإغلاق ليست أقل من فترة السماح وأن القالب نشط.": "Make sure the lock duration is not shorter than late grace and that the template is active.",
  "لا يوجد سماح خروج مبكر. الخروج قبل وقت نهاية الشفت يُحسب نقصًا من أول دقيقة، والتأخير لا يُعفى إلا بمقدار ما عُوّض بعد نهاية الشفت.": "There is no early-leave grace. Leaving before shift end is counted from the first minute, and lateness is offset only by time actually worked after shift end.",
  "استثناء الشفت": "Shift exception",
  "تغيير مؤقت ليوم أو فترة دون تعديل القالب أو الجدول الأساسي.": "Apply a temporary change for a day or period without editing the base template or schedule.",
  "الاستثناء يضع قاعدة مؤقتة أعلى من الأسبوع التشغيلي خلال تواريخ محددة. يمكن أن يجعل الفترة راحة/إغلاقًا معتمدًا، يبدلها إلى قالب شفت آخر، أو يحدد وقتًا مخصصًا. عند انتهاء الفترة يختفي أثره تلقائيًا ويعود النظام إلى الجدول الأصلي.": "An exception creates a temporary rule above the operational week for specific dates. It can mark the period as approved rest/closure, use another shift template, or set custom hours. Its effect ends automatically and the original schedule resumes.",
  "دوام رمضان، تدريب، مناسبة، تبديل شفت مؤقت، إغلاق فرع، أو تغيير ساعات ليوم/فترة محددة.": "Use this for Ramadan hours, training, events, temporary shift swaps, branch closures, or date-specific hour changes.",
  "راحة أسبوعية تتكرر دائمًا أو إجازة تخص رصيد الموظفة؛ استخدم الأسبوع التشغيلي أو نظام الإجازات.": "Do not use this for recurring weekly rest or leave that affects the staff leave balance; use the operational week or leave system.",
  "تدريب يوم واحد": "One-day training",
  "الموظفة شفتها المعتاد 3:00 م إلى 11:00 م، لكن يوم 12 أغسطس لديها تدريب من 10:00 ص إلى 2:00 م.": "The staff member normally works 3:00 PM to 11:00 PM, but on August 12 she has training from 10:00 AM to 2:00 PM.",
  "أنشئ استثناءً ليوم 12 أغسطس بنوع وقت مخصص، وأدخل 10:00 ص إلى 2:00 م مع ملاحظة «تدريب».": "Create a custom-time exception for August 12 from 10:00 AM to 2:00 PM and add the note Training.",
  "يحسب الحضور ذلك اليوم على وقت التدريب فقط، وفي يوم 13 أغسطس يعود النظام تلقائيًا إلى الشفت المسائي المعتاد.": "Attendance for that day uses only the training hours, and on August 13 the system automatically returns to the normal evening shift.",
  "اختر النوع": "Choose the type",
  "حدد راحة/إغلاق، شفت بديل، أو وقتًا مخصصًا.": "Choose rest/closure, an alternate shift, or custom hours.",
  "حدد الفترة": "Set the period",
  "اختر تاريخ البداية والنهاية؛ اجعلهما متطابقين لاستثناء يوم واحد.": "Choose the start and end dates; use the same date for a one-day exception.",
  "أدخل المصدر الصحيح": "Set the correct source",
  "اختر القالب البديل أو الساعات المخصصة حسب نوع الاستثناء.": "Choose the alternate template or custom hours according to the exception type.",
  "افحص الاستثناء": "Check the exception",
  "راجع أثره والمصدر النهائي قبل الحفظ.": "Review its impact and effective source before saving.",
  "الاستثناء أعلى أولوية من جدول الأسبوع خلال مدته. استخدم ملاحظة واضحة لأن أثره يصل إلى الحضور والراتب.": "An exception has higher priority than the weekly schedule during its period. Use a clear note because it affects attendance and payroll.",
  "قائمة قوالب الشفتات": "Shift template list",
  "مراجعة القوالب العامة المحفوظة والسياسات المرتبطة بكل قالب.": "Review saved shared templates and the policies attached to each one.",
  "تعرض القائمة جميع القوالب التي يمكن توزيعها على الموظفات، مع وقت كل قالب، فترة السماح، إعداد إغلاق البصمة، وحالته. من هنا تعرف أي قالب مستخدم قبل فتحه للتعديل، وتمنع إنشاء قوالب مكررة بأسماء مختلفة لنفس الوقت.": "The list shows all assignable templates with hours, late grace, check-in lock settings, and status. Use it to understand existing templates before editing and avoid duplicate templates for the same hours.",
  "تريد مراجعة القوالب المتاحة، تعديل سياسة عامة، تعطيل قالب قديم، أو اختيار القالب الصحيح قبل توزيعه.": "Use this to review available templates, change a shared policy, deactivate an old template, or choose the right template before assignment.",
  "تغيير يوم موظفة بعينها؛ تعديل القالب ينعكس على كل استخداماته وليس على موظفة واحدة فقط.": "Do not use this to change one staff member's day; editing a template affects every place where it is used.",
  "تعديل سماح قالب مستخدم": "Changing grace on an active template",
  "قالب «المسائي» مستخدم لدى خمس موظفات، وفترة السماح الحالية 15 دقيقة.": "The Evening template is used by five staff members and currently has 15 minutes late grace.",
  "قبل تغييرها إلى 20 دقيقة، راجع أن القرار مقصود لكل الموظفات والأيام المرتبطة بالقالب، ثم افتح القالب وعدله.": "Before changing it to 20 minutes, confirm that the decision is intended for every linked staff member and day, then edit the template.",
  "من تاريخ اعتماد التعديل ستستخدم جميع الأيام المرتبطة بالقالب السياسة الجديدة؛ لذلك لا تستخدم هذا الإجراء لمعالجة حالة فردية.": "From the effective date of the change, all linked days use the new policy, so do not use this action for an individual case.",
  "راجع الاسم والوقت": "Review name and hours",
  "تأكد أن القالب ليس نسخة مكررة من قالب قائم.": "Make sure the template is not a duplicate of an existing one.",
  "افحص فترة السماح وإغلاق البصمة قبل التعديل.": "Review late grace and check-in lock settings before editing.",
  "عدّل بحذر": "Edit carefully",
  "تذكر أن التعديل يؤثر في كل الموظفات والأيام التي تستخدم القالب.": "Remember that the change affects every staff member and day using the template.",
  "عطّل بدل الحذف": "Deactivate instead of deleting",
  "عند إيقاف استخدام قالب قديم عطّله مع الحفاظ على السجل التاريخي.": "When retiring an old template, deactivate it while preserving historical records.",
  "لا تحذف أو تغيّر قالبًا مستخدمًا في فترات رواتب مقفلة دون مراجعة الأثر التاريخي.": "Do not delete or change a template used in locked payroll periods without reviewing the historical impact.",
  "مراجعة التغييرات المؤقتة المسجلة وتواريخها ومصادرها.": "Review recorded temporary changes, their dates, and sources.",
  "تعرض هذه القائمة كل استثناء مسجل للموظفة، سواء كان إغلاقًا، شفتًا بديلًا، أو وقتًا مخصصًا. تساعدك على اكتشاف استثناء قديم ما زال يغطي تاريخًا غير مقصود، ومعرفة لماذا لم يستخدم النظام جدول الأسبوع في يوم معين.": "This list shows every staff exception, whether a closure, alternate shift, or custom time. Use it to find old exceptions covering unintended dates and understand why the weekly schedule was not used on a day.",
  "تراجع سبب ظهور يوم كشفت مختلف، تريد إلغاء استثناء انتهت الحاجة إليه، أو تتحقق من عدم وجود فترات متداخلة.": "Use this when investigating an unexpected day, cancelling an exception that is no longer needed, or checking for overlapping periods.",
  "إدارة الراحة الأسبوعية أو قوالب الشفتات العامة؛ هذه القائمة تخص الاستثناءات المؤقتة للموظفة فقط.": "Do not use this to manage recurring weekly rest or shared shift templates; this list is only for temporary staff exceptions.",
  "استثناء خاطئ يغطي يومين": "Incorrect exception covering two days",
  "تم تسجيل تدريب ليوم 5 أغسطس، لكن تاريخ النهاية وُضع 6 أغسطس بالخطأ.": "Training was recorded for August 5, but the end date was incorrectly set to August 6.",
  "افتح الاستثناء من القائمة وعدّل النهاية إلى 5 أغسطس، أو ألغِه ثم أنشئ السجل الصحيح.": "Open the exception and change the end date to August 5, or cancel it and create the correct record.",
  "يوم 5 يستخدم وقت التدريب، ويوم 6 يعود إلى جدول الأسبوع بدل الاستمرار على الاستثناء الخاطئ.": "August 5 uses the training hours and August 6 returns to the weekly schedule instead of continuing the incorrect exception.",
  "راجع الفترة": "Review the date range",
  "تأكد من تاريخ البداية والنهاية وعدم تغطية أيام إضافية.": "Verify start and end dates and make sure no extra dates are covered.",
  "راجع النوع والوقت": "Review type and time",
  "تأكد أن الإغلاق أو الشفت البديل أو الوقت المخصص هو المقصود.": "Confirm that the intended source is closure, alternate shift, or custom hours.",
  "عدّل أو ألغِ": "Edit or cancel",
  "عند الإلغاء يعود النظام إلى المصدر التالي: جدول الأسبوع ثم التعيين الاحتياطي.": "After cancellation, the system falls back to the next source: weekly schedule, then fallback assignment.",
  "الراحة الأسبوعية الثابتة لا تظهر هنا؛ تُدار من الأسبوع التشغيلي. والإجازات الفعلية تُدار من نظام الإجازات.": "Recurring weekly rest is managed in the operational week and does not appear here. Actual leave is managed in the leave system.",
  "تمت العملية بنجاح": "Operation completed successfully",
  "ليست لديك صلاحية لحذف الموظفات.": "You do not have permission to delete staff.",
  "ليست لديك صلاحية لإدارة رصيد الإجازات.": "You do not have permission to manage leave balances.",
  "لم يتم تحديد الموظفة.": "No staff member was selected.",
  "اختر يومًا صحيحًا قبل حفظ تعديل البصمة.": "Choose a valid date before saving the attendance edit.",
  "ليست لديك صلاحية لإضافة بصمة إدارية.": "You do not have permission to add an administrative attendance record.",
  "ليست لديك صلاحية لتعديل بصمة الموظفة.": "You do not have permission to edit this staff member's attendance record.",
  "لمسح اليوم كاملًا استخدم إجراء حذف سجل اليوم بدل مسح الوقتين من نافذة التعديل.": "To clear the entire day, delete the day's attendance record instead of clearing both times from the edit dialog.",
  "اختر وقت الحضور قبل إنشاء يوم حضور يدوي.": "Choose a check-in time before creating a manual attendance day.",
  "تعذر تحديد ترتيب وقت الحضور والانصراف.": "Could not determine the order of check-in and check-out times.",
  "ليست لديك صلاحية لمسح بصمة الموظفة.": "You do not have permission to delete this staff member's attendance record.",
  "تعذر تحديد المستخدم المنفذ للعملية.": "Could not identify the user performing this action.",
  "اختر يومًا صحيحًا لتسجيل الإجازة.": "Choose a valid date to record leave.",
  "تعذر تحديد حساب الموظفة لتسجيل الإجازة.": "Could not identify the staff account for leave recording.",
  "هذا اليوم مسجل كإجازة معتمدة بالفعل.": "This date is already recorded as approved leave.",
  "لا يمكن تحويل يوم عليه بصمة إلى إجازة مفاجئة من هذا الإجراء.": "A day with attendance records cannot be converted to sudden leave from this action.",
  "اختر يومًا صحيحًا لإلغاء الإجازة.": "Choose a valid date to cancel leave.",
  "لم يتم العثور على إجازة أو استئذان معتمد لهذا اليوم.": "No approved leave or permission record was found for this date.",
  "تعذر تحديد الموظفة أو المستخدم المنفذ.": "Could not identify the staff member or the user performing the action.",
  "تعذر العثور على ملف الموظفة.": "Could not find the staff profile.",
  "تعذر العثور على ملف الموظفة المطلوب. تم الرجوع إلى قائمة الموظفين.": "The requested staff profile could not be found. Returned to the staff directory.",
  "ليست لديك صلاحية لإدارة الرواتب.": "You do not have permission to manage payroll.",
  "اكتب اسم الموظفة قبل حفظ إعدادات الراتب.": "Enter the staff member's name before saving payroll settings.",
  "اكتب سبب إعفاء الموظف من البصمة قبل حفظ إعدادات الراتب.": "Enter the reason for attendance exemption before saving payroll settings.",
  "حدد تصنيف التأمينات الاجتماعية للموظفة قبل حفظ إعدادات الراتب.": "Select the staff member's Social Insurance classification before saving payroll settings.",
  "حدد تاريخ سريان تصنيف التأمينات حتى يبقى السجل المالي واضحًا مستقبلًا.": "Set the effective date for the insurance classification so the financial history remains auditable.",
  "اكتب أجر الاشتراك في GOSI عند استخدام الإدخال المعتمد يدويًا.": "Enter the GOSI contribution wage when using the approved manual value.",
  "اكتب سبب استخدام أجر اشتراك GOSI مختلف عن الأساسي + بدل السكن.": "Enter the reason for using a GOSI contribution wage different from base salary plus housing allowance.",
  "حدد دولة الموظفة الخليجية لإعداد مد الحماية دون معاملتها كغير سعودية.": "Select the GCC staff member's country to configure protection extension without treating them as Non-Saudi.",
  "اكتب اسم الموظفة": "Enter the staff member's name.",
  "صيغة التاريخ الهجري يجب أن تكون: يوم/شهر/سنة (مثال: 09/09/1447).": "Hijri date format must be day/month/year (example: 09/09/1447).",
  "تعذر تحويل التاريخ الهجري. تأكد من إدخال تاريخ هجري صحيح.": "Could not convert the Hijri date. Check that the entered Hijri date is valid.",
  "لا توجد استثناءات حالية لتعديلها.": "There are no current exceptions to edit.",
  "اكتب عدد أيام صحيح بفواصل نصف يوم مثل 0.5 أو 1 أو 1.5.": "Enter a valid number of days in half-day increments such as 0.5, 1, or 1.5.",
  "اختر تاريخ العملية.": "Choose the transaction date.",
  "تعذر تحديد سجل الإجازة المطلوب.": "Could not identify the requested leave record.",
  "تاريخ الاستحقاق غير صحيح.": "The entitlement date is invalid.",
  "تم حفظ إعدادات الراتب والدوام في مصدر مسيرات الرواتب.": "Payroll and work-schedule settings were saved to the payroll source.",
  "تم حفظ التغييرات بنجاح.": "Changes saved successfully.",
  "تاريخ آخر يوم عمل مطلوب.": "The last working date is required.",
  "سبب إنهاء الخدمة مطلوب.": "A reason for ending employment is required.",
  "لا يمكن إنهاء الخدمة قبل إعادة تعيين الحجوزات التشغيلية القادمة المرتبطة بالموظفة.": "Employment cannot be ended until upcoming operational bookings assigned to this staff member are reassigned.",
  "تاريخ آخر يوم عمل يتعارض مع نشاط أو حجز نهائي مسجل بعد هذا التاريخ. يلزم مراجعة الدليل التشغيلي قبل المتابعة.": "The last working date conflicts with an activity or finalized booking recorded after that date. Review the operational record before continuing.",
  "إنهاء الخدمة الفوري لا يقبل تاريخًا مستقبليًا. استخدم تاريخ اليوم أو تاريخًا سابقًا مثبتًا.": "Immediate employment termination cannot use a future date. Use today or a verified earlier date.",
  "الحساب المرتبط يملك صلاحيات إدارية/مميزة ويحتاج مراجعة وصول مستقلة قبل إنهاء الخدمة.": "The linked account has administrative or privileged permissions and requires a separate access review before employment can be ended.",
  "هوية الحساب مرتبطة حاليًا بموظف آخر؛ تم إيقاف العملية لحماية الحساب من التعطيل الخاطئ.": "The account identity is currently linked to another staff member. The action was stopped to prevent disabling the wrong account.",
  "اختيار شهر الحضور": "Choose attendance month",
  "اختيار الشهر": "Choose month",
  "السنة السابقة": "Previous year",
  "السنة التالية": "Next year",
  "هذا الشهر": "This month",
  "خروج مبكر": "Early leave",
  "حضور": "Present",
  "استئذان": "Permission",
  "يحتاج مراجعة": "Needs review",
  "لم تُسجّل بصمة الخروج — يجب مراجعة السجل قبل اعتماد الراتب": "Check-out was not recorded — review the record before payroll approval",
  "إجازة أسبوعية": "Weekly day off",
  "إجازة أسبوعية حسب الجدول": "Weekly day off per schedule",
  "راحة أسبوعية حسب جدول الدوام": "Weekly day off per work schedule",
  "راحة أسبوعية منقولة مؤقتًا لهذا اليوم": "Weekly day off temporarily moved to this date",
  "يوم مغلق باستثناء معتمد": "Closed day by approved exception",
  "تكليف عمل مع إبقاء أصل اليوم راحة أسبوعية": "Work assignment while retaining the original weekly day off",
  "راحة بسبب استثناء اليوم": "Day off due to today's exception",
  "استئذان معتمد — الفترة فقط محجوبة": "Approved permission — only the specified period is blocked",
  "مكتمل ومطابق": "Complete and compliant",
  "لا توجد بيانات": "No data",
  "إجازة اضطرارية": "Emergency leave",
  "قبل المباشرة": "Before employment start",
  "بعد انتهاء الخدمة": "After employment end",
  "إجازة معتمدة — لا تتطلب بصمة": "Approved leave — no attendance required",
  "راحة معتمدة — لا تتطلب بصمة": "Approved rest — no attendance required",
  "راحة أسبوعية — لا تتطلب بصمة": "Weekly day off — no attendance required",
  "يوم مغلق — لا تتطلب بصمة": "Closed day — no attendance required",
  "لم تسجل بصمة دخول أو خروج": "No check-in or check-out was recorded",
  "غير مصنف": "Unclassified",
  "لا توجد بيانات بصمة أو حالة معتمدة": "No attendance record or approved status",
  "لا توجد بيانات بصمة": "No attendance records",
  "تأخير / نقص ساعات": "Late / Missing hours",
  "تأخير / خروج مبكر": "Late / Early leave",
  "خروج مبكر / نقص ساعات": "Early leave / Missing hours",
  "تأخير / خروج مبكر / نقص ساعات": "Late / Early leave / Missing hours",
  "لا توجد بيانات للعرض.": "No data to display.",
  "شفت افتراضي": "Default shift",
  "لا يوجد شفت Core": "No Core shift",
  "الموارد البشرية": "Human Resources",
  "منشور": "Published",
  "مسودة": "Draft",
  "معتمد": "Approved",
  "استثناء": "Exception",
  "الحالي": "Current",
  "لا توجد هوية Core صالحة لهذه الموظفة.": "No valid Core identity is available for this staff member.",
  "تعذر تحميل الشفتات من Core.": "Could not load shifts from Core.",
  "تعذر تحميل الشفت المطبق من Core.": "Could not load the effective shift from Core.",
  "التعيين المؤقت يحتاج تاريخ نهاية.": "A temporary assignment requires an end date.",
  "تاريخ نهاية التعيين لا يمكن أن يكون قبل تاريخ البداية.": "The assignment end date cannot be before the start date.",
  "تعذر فحص تأثير تعيين الشفت من Core. لم يتم تنفيذ أي تغيير.": "Could not check the shift assignment impact in Core. No changes were made.",
  "تاريخ نهاية الاستثناء لا يمكن أن يكون قبل تاريخ البداية.": "The exception end date cannot be before the start date.",
  "اختر شفت بديل.": "Choose an alternate shift.",
  "أدخل وقت بداية ونهاية صحيحين ومختلفين للاستثناء المخصص.": "Enter valid and different start and end times for the custom exception.",
  "تعذر فحص تأثير الاستثناء من Core. لم يتم تنفيذ أي تغيير.": "Could not check the exception impact in Core. No changes were made.",
  "تعذر إكمال فحص تأثير التغيير؛ لم يتم الحفظ.": "Could not complete the change-impact check; nothing was saved.",
  "يوجد استثناء نشط متداخل مع الفترة المحددة. ألغِ الاستثناء المتداخل أو غيّر الفترة قبل الحفظ.": "An active exception overlaps the selected period. Cancel the overlapping exception or change the period before saving.",
  "يوجد فترة رواتب مقفلة. فعّل خيار تسجيل تسوية بعد الإقفال قبل الحفظ.": "A locked payroll period is affected. Enable post-lock adjustment recording before saving.",
  "اسم الشفت مطلوب.": "Shift name is required.",
  "وقت بداية ونهاية الشفت مطلوبان بصيغة صحيحة.": "Valid shift start and end times are required.",
  "وقت بداية الشفت ونهايته لا يمكن أن يكونا متطابقين.": "Shift start and end times cannot be identical.",
  "قيم الدقائق في سياسة الشفت يجب أن تكون أرقامًا صحيحة.": "Minute values in the shift policy must be valid numbers.",
  "تحقق من مدد الاستراحة والسماح والإغلاق والإضافي؛ القيم خارج النطاق المسموح.": "Check break, grace, lock, and overtime durations; one or more values are outside the allowed range.",
  "مدة الاستراحة يجب أن تكون أقل من مدة الشفت الفعلية.": "Break duration must be shorter than the effective shift duration.",
  "مدة إغلاق البصمة يجب أن تكون مساوية لفترة سماح التأخير أو أكبر منها.": "Attendance lock duration must be equal to or greater than the late-grace period.",
  "تعذر حفظ قالب الشفت.": "Could not save the shift template.",
  "لا يمكن تعديل تعيين ملغي. أنشئ تعيينًا جديدًا بدلًا من تعديل سجل ملغي.": "A cancelled assignment cannot be edited. Create a new assignment instead.",
  "تعذر تحديد هوية الموظفة في Core. أعد تحميل الملف قبل الحفظ.": "Could not identify the staff member in Core. Reload the profile before saving.",
  "الشفت وتاريخ البداية وسبب التغيير مطلوبة.": "Shift, start date, and change reason are required.",
  "هذا التعيين لم يبدأ بعد. استخدم الإلغاء بدل إنهائه.": "This assignment has not started yet. Cancel it instead of ending it.",
  "تعذر إنهاء الشفت.": "Could not end the shift assignment.",
  "تاريخ الاستثناء مطلوب.": "Exception date is required.",
  "وقت البداية والنهاية مطلوبان للاستثناء المخصص.": "Start and end times are required for a custom exception.",
  "وقت بداية الاستثناء ونهايته لا يمكن أن يكونا متطابقين.": "Exception start and end times cannot be identical.",
  "تعذر حفظ الاستثناء.": "Could not save the exception.",
  "تعذر إلغاء الاستثناء.": "Could not cancel the exception.",
  "يمكن استعادة الاستثناءات الملغاة فقط.": "Only cancelled exceptions can be restored.",
  "تم حفظ قالب الشفت.": "Shift template saved.",
  "وضع التعديل نشط: عدّل التعيين ثم اضغط حفظ التعديل.": "Edit mode is active: update the assignment, then select Save changes.",
  "جاهز لتعيين شفت جديد. سيتم إغلاق أي تداخل سابق لنفس الموظفة تلقائيًا.": "Ready for a new shift assignment. Any previous overlap for the same staff member will be closed automatically.",
  "تم تعديل تعيين الشفت للموظفة.": "Staff shift assignment updated.",
  "تم تعيين الشفت للموظفة.": "Shift assigned to staff member.",
  "تم إلغاء تعيين الشفت.": "Shift assignment cancelled.",
  "تم إنهاء الشفت.": "Shift assignment ended.",
  "تم حفظ الاستثناء.": "Exception saved.",
  "تم إلغاء الاستثناء.": "Exception cancelled.",
  "تمت استعادة الاستثناء كسجل Core نشط جديد.": "Exception restored as a new active Core record.",
  "حذف سجل البصمة؟": "Delete attendance record?",
  "نعم، احذف السجل": "Yes, delete record",
  "إلغاء الاستئذان المعتمد؟": "Cancel approved permission?",
  "نعم، ألغِ الاستئذان": "Yes, cancel permission",
  "إلغاء الإجازة المعتمدة؟": "Cancel approved leave?",
  "نعم، ألغِ الإجازة": "Yes, cancel leave",
  "إنهاء الإجازة الحالية؟": "End current leave?",
  "سيتم إنهاء الإجازة الحالية وإلغاء أثرها المستقبلي.": "The current leave will be ended and its future effect will be cancelled.",
  "نعم، أنهِ الإجازة": "Yes, end leave",
  "الموظفة مخفية من الحجز": "Staff member is hidden from booking",
  "الموظفة لديها خدمات لكنها مخفية من الحجز. هل تريد الحفظ بهذا الشكل؟": "This staff member has assigned services but is hidden from booking. Save this configuration?",
  "نعم، احفظ بهذا الشكل": "Yes, save this way",
  "حذف سجل الإجازة؟": "Delete leave record?",
  "تم تحديث حالة الموظفة": "Staff status updated",
  "تعذر تحميل نطاقات الحضور.": "Could not load attendance zones.",
  "تعذر تحميل سجل حضور الموظفة.": "Could not load the staff attendance record.",
  "تعذر حفظ تعديل البصمة.": "Could not save the attendance edit.",
  "تعذر مسح البصمة.": "Could not delete the attendance record.",
  "تعذر التحقق من الإجازات والاستئذانات المعتمدة من Core. لم يتم تنفيذ العملية.": "Could not verify approved leave and permission records from Core. No action was performed.",
  "تعذر إلغاء الاستئذان.": "Could not cancel the permission.",
  "تعذر إلغاء الإجازة.": "Could not cancel the leave.",
  "تعذر تسجيل الاستئذان وربطه بالحضور والحجز.": "Could not record the permission and link it to attendance and booking.",
  "تعذر تسجيل الإجازة وربطها بالحضور والراتب.": "Could not record the leave and link it to attendance and payroll.",
  "تعذر إنهاء الإجازة الحالية.": "Could not end the current leave.",
  "تعذر تحميل رصيد الإجازات من Core.": "Could not load the leave balance from Core.",
  "تعذر تحميل الخدمات من Core.": "Could not load services from Core.",
  "تعذر تحميل الموظفات.": "Could not load staff.",
  "تعذر حفظ إعدادات الراتب.": "Could not save payroll settings.",
  "تعذر حفظ الموظفة.": "Could not save the staff profile.",
  "تعذر إنهاء خدمة الموظفة.": "Could not end the staff member's employment.",
  "تعذر حفظ حركة الإجازة في Core.": "Could not save the leave transaction in Core.",
  "تعذر عكس حركة الإجازة في Core.": "Could not reverse the leave transaction in Core.",
  "تعذر حفظ تاريخ الاستحقاق في Core.": "Could not save the entitlement date in Core.",
  "الفترة": "Period",
  "الإجراء": "Action",
  "القالب": "Template",
  "التأخير": "Lateness",
  "مطبق": "Applied",
  "تحديث النطاقات": "Refresh zones",
  "نوع التاريخ": "Date type",
  "من تاريخ هجري": "Hijri start date",
  "إلى تاريخ هجري": "Hijri end date",
  "بداية الدوام": "Work start",
  "نهاية الدوام": "Work end",
  "طريقة التطبيق": "Application method",
  "ملاحظة داخلية": "Internal note",
  "نوع التعديل المؤقت": "Temporary change type",
  "اليوم المؤقت": "Temporary day",
  "خصم ثابت متفق عليه": "Agreed recurring deduction",
  "قرض / سلفة خارجية موثقة": "Documented loan / external advance",
  "خصم إداري يدوي": "Manual administrative deduction",
  "غياب يدوي موثق": "Documented manual absence",
  "تأخير يدوي موثق": "Documented manual lateness",
  "تعويض عهدة / أصل": "Asset reimbursement",
  "اشتراك": "Subscription",
  "التزام آخر": "Other obligation",
  "خصم ثابت متكرر": "Recurring fixed deduction",
  "إدخال إداري": "Administrative entry",
  "سلفة راتب": "Salary advance",
  "خصومات GOSI النظامية لا يمكن تأجيلها أو تقسيطها من هذه الشاشة.": "Statutory GOSI deductions cannot be deferred or split into installments from this screen.",
  "اكتب سبب الخصم أو القرار المالي.": "Enter the reason for the deduction or financial decision.",
  "اكتب مبلغًا أكبر من صفر.": "Enter an amount greater than zero.",
  "مجموع الأقساط يجب أن يساوي إجمالي الالتزام تمامًا.": "The installment total must exactly equal the obligation total.",
  "شهور الأقساط يجب أن تكون بعد شهر نشوء الالتزام.": "Installment months must be later than the obligation origin month.",
  "شهر التأجيل يجب أن يكون بعد شهر التحصيل الحالي.": "The deferred collection month must be later than the current collection month.",
  "لا يمكن تعديل تحصيل شهر له مسير Approved/Paid.": "Collection cannot be changed for a month with an Approved/Paid payroll.",
  "تغيرت الالتزامات بعد إنشاء المسير. أعد توليد المسير قبل الاعتماد.": "Obligations changed after payroll generation. Regenerate payroll before approval.",
  "مسدد جزئيًا": "Partially settled",
  "مسدد": "Settled",
  "مرحّل": "Deferred",
  "الخصومات والالتزامات": "Deductions & obligations",
  "كل مبلغ موثق بنوعه وسببه وشهر نشوئه وشهر تحصيله. التأجيل والتقسيط يغيران موعد التحصيل ولا يحذفان أصل الالتزام.": "Every amount is documented by type, reason, origin month, and collection month. Deferral and installments change collection timing without deleting the original obligation.",
  "مؤجل من أشهر سابقة": "Deferred from prior months",
  "الأقساط القادمة": "Upcoming installments",
  "إجمالي الالتزامات المفتوحة": "Total open obligations",
  "فصل مالي صريح": "Explicit financial separation",
  "هذه الخصومات الإدارية مستقلة عن GOSI وعن Carryover. خصم GOSI النظامي لا يقبل التأجيل أو التقسيط هنا، وCarryover يبقى فقط لتصحيح فروقات اكتشفت بعد اعتماد المسير.": "Administrative deductions are separate from GOSI and Carryover. Statutory GOSI deductions cannot be deferred or split here, and Carryover remains only for differences discovered after payroll approval.",
  "تم": "Completed",
  "المستحق في هذا الشهر": "Due this month",
  "هذه هي البنود التي سيدخلها مسير الرواتب Draft لهذا الشهر. البنود المرحّلة تظهر في شهر التحصيل الجديد مع الاحتفاظ بالشهر الأصلي.": "These items will enter this month's Draft payroll. Deferred items appear in the new collection month while preserving the original month.",
  "المبلغ": "Amount",
  "شهر الأصل": "Origin month",
  "شهر التحصيل": "Collection month",
  "خصم": "Deduction",
  "خصم ثابت": "Recurring deduction",
  "متوقع / قبل الحفظ": "Expected / before save",
  "التزام محفوظ": "Saved obligation",
  "جاري تحميل الخصومات...": "Loading deductions...",
  "لا توجد خصومات أو التزامات مستحقة للتحصيل في هذا الشهر.": "There are no deductions or obligations due for collection this month.",
  "ينشئ بندًا شهريًا متوقعًا من شهر البداية إلى شهر النهاية إن وجد. لا يتم إنشاء حركة تحصيل فعلية إلا عند بناء/حفظ مسير الشهر.": "Creates an expected monthly item from the start month through the optional end month. An actual collection transaction is created only when the monthly payroll is built/saved.",
  "اسم الخصم": "Deduction name",
  "مثال: خصم اشتراك شهري": "Example: monthly subscription deduction",
  "نوع الخصم": "Deduction type",
  "المبلغ الشهري (ر.س)": "Monthly amount (SAR)",
  "شهر البداية": "Start month",
  "شهر النهاية — اختياري": "End month — optional",
  "السبب / الأساس": "Reason / basis",
  "لماذا يوجد هذا الخصم؟": "Why does this deduction exist?",
  "ملاحظة — اختياري": "Note — optional",
  "الاسم": "Name",
  "من": "From",
  "إلى": "To",
  "مستمر": "Ongoing",
  "موقوف": "Paused",
  "لا توجد خصومات ثابتة محفوظة.": "No recurring deductions are saved.",
  "التزام أو خصم لمرة واحدة": "One-time obligation or deduction",
  "سجّل أصل المبلغ أولًا، ثم اختر تحصيله في شهر الأصل أو تأجيله إلى شهر لاحق أو تقسيمه على عدة أشهر.": "Record the original amount first, then collect it in the origin month, defer it, or split it across multiple months.",
  "نوع الالتزام": "Obligation type",
  "إجمالي المبلغ (ر.س)": "Total amount (SAR)",
  "شهر نشوء الالتزام": "Obligation origin month",
  "طريقة التحصيل": "Collection method",
  "شهر التحصيل الجديد": "New collection month",
  "سبب الخصم / قرار التأجيل": "Deduction reason / deferral decision",
  "سبب الخصم / قرار التقسيط": "Deduction reason / installment decision",
  "سبب مالي واضح وقابل للمراجعة": "Clear, auditable financial reason",
  "عدد الأقساط": "Number of installments",
  "متوسط قيمة القسط": "Average installment amount",
  "توزيع تلقائي": "Automatic distribution",
  "جدول الأقساط": "Installment schedule",
  "مبلغ القسط (ر.س)": "Installment amount (SAR)",
  "القسط": "Installment",
  "سبب التأجيل": "Deferral reason",
  "مثال: ظرف الموظفة — بموافقة الإدارة": "Example: staff circumstances — management approved",
  "تأجيل قسط مجدول": "Defer a scheduled installment",
  "اختر قسطًا لم يُطبق بعد وحدد الشهر الجديد والسبب. يحتفظ النظام بالقسط القديم بحالة «مرحّل» ويربطه بالقسط البديل.": "Choose an unapplied installment, then set the new month and reason. The original installment remains as Deferred and is linked to the replacement.",
  "سجل الالتزامات": "Obligation history",
  "السجل يوضح أصل كل التزام، المتبقي، وحالة كل قسط ومتى كان مقررًا تحصيله.": "The history shows each obligation's origin, remaining balance, installment status, and planned collection timing.",
  "سبب الإلغاء — يستخدم عند الضغط على إلغاء": "Cancellation reason — used when cancelling",
  "سبب الإلغاء مطلوب للتدقيق": "Cancellation reason is required for audit.",
  "المبلغ الأصلي": "Original amount",
  "الشهر الأصلي": "Original month",
  "جدول التحصيل": "Collection schedule",
  "المتبقي": "Remaining",
  "لا توجد أقساط": "No installments",
  "جاري تحميل الالتزامات...": "Loading obligations...",
  "لا توجد التزامات محفوظة.": "No obligations are saved.",
};

function employeeDynamicEnglishText(arabic: string): string | null {
  const patterns: Array<[RegExp, (match: RegExpMatchArray) => string]> = [
    [/^(\d+(?:[.,]\d+)?) ملف$/, (m) => `${m[1]} profiles`],
    [/^فتح ملف (.+)$/, (m) => `Open ${m[1]} profile`],
    [/^صورة (.+)$/, (m) => `${m[1]} photo`],
    [/^(\d+) خدمة مرتبطة$/, (m) => `${m[1]} linked services`],
    [/^تفصيل (\d+)$/, (m) => `Detail ${m[1]}`],
    [/^(\d+) طلبات معلقة$/, (m) => `${m[1]} pending requests`],
    [/^(\d+) طلبات في الحالة المحددة\.$/, (m) => `${m[1]} requests in the selected status.`],
    [/^(\d+) غير مقروءة$/, (m) => `${m[1]} unread`],
    [/^آخر رسالة (.+)$/, (m) => `Last message ${m[1]}`],
    [/^يحتاج تجديد خلال (\d+) يومًا$/, (m) => `Needs renewal in ${m[1]} days`],
    [/^(\d+) حرف$/, (m) => `${m[1]} characters`],
    [/^(\d+) خدمات محددة$/, (m) => `${m[1]} selected services`],
    [/^(\d+) نتيجة$/, (m) => `${m[1]} results`],
    [/^إزالة (.+)$/, (m) => `Remove ${m[1]}`],
    [/^(\d+(?:[.,]\d+)?) يوم$/, (m) => `${m[1]} day(s)`],
    [/^بعد (\d+(?:[.,]\d+)?) دقيقة$/, (m) => `After ${m[1]} min`],
    [/^تأخير (\d+(?:[.,]\d+)?) دقيقة$/, (m) => `Late ${m[1]} min`],
    [/^خروج مبكر (\d+(?:[.,]\d+)?) دقيقة$/, (m) => `Early leave ${m[1]} min`],
    [/^نقص ساعات (\d+(?:[.,]\d+)?) دقيقة$/, (m) => `Missing hours ${m[1]} min`],
    [/^في إجازة حتى (.+)$/, (m) => `On leave until ${m[1]}`],
    [/^دوام في (.+)$/, (m) => `Worked during ${employeeEnglish[m[1]] || m[1]}`],
    [/^سيتم مسح سجل البصمة ليوم (.+)\.$/, (m) => `The attendance record for ${m[1]} will be deleted.`],
    [/^سيتم إلغاء الاستئذان المعتمد ليوم (.+)\.$/, (m) => `The approved permission for ${m[1]} will be cancelled.`],
    [/^سيتم إلغاء الإجازة المعتمدة ليوم (.+)\.$/, (m) => `The approved leave for ${m[1]} will be cancelled.`],
    [/^اختاري شفتًا لأيام العمل التالية: (.+)$/, (m) => `Choose a shift for the following working days: ${m[1]}`],
  ];

  for (const [pattern, translate] of patterns) {
    const match = arabic.match(pattern);
    if (match) return translate(match);
  }
  return null;
}

export function employeeText(language: DashboardLanguage, arabic: string): string {
  if (language !== "en") return arabic;
  const direct = employeeEnglish[arabic];
  if (direct) return direct;
  const dashboard = dashboardText(language, arabic);
  if (dashboard !== arabic) return dashboard;
  return employeeDynamicEnglishText(arabic) || arabic;
}

type EmployeeLanguageContextValue = {
  language: DashboardLanguage;
  direction: "rtl" | "ltr";
  t: (arabic: string) => string;
  tr: (arabic: string, english: string) => string;
};

const EmployeeLanguageContext = createContext<EmployeeLanguageContextValue>({
  language: "ar",
  direction: "rtl",
  t: (arabic) => arabic,
  tr: (arabic) => arabic,
});

export function EmployeeLanguageProvider({
  language,
  children,
}: {
  language: DashboardLanguage;
  children: ReactNode;
}) {
  const value = useMemo<EmployeeLanguageContextValue>(
    () => ({
      language,
      direction: language === "en" ? "ltr" : "rtl",
      t: (arabic) => employeeText(language, arabic),
      tr: (arabic, english) => (language === "en" ? english : arabic),
    }),
    [language]
  );

  return (
    <EmployeeLanguageContext.Provider value={value}>
      {children}
    </EmployeeLanguageContext.Provider>
  );
}

export function useEmployeeLanguage() {
  return useContext(EmployeeLanguageContext);
}
