import { createContext, useContext, useMemo, type ReactNode } from "react";
import {
  dashboardText,
  type DashboardLanguage,
} from "../../helpers/dashboardLanguage";

const employeeEnglish: Record<string, string> = {
  "غير مصرح": "Unauthorized",
  "سجّل دخول ثم جرّب مرة أخرى.": "Sign in, then try again.",
  "صلاحيات غير كافية": "Insufficient permissions",
  "هذه الصفحة مخصصة للإدارة.": "This page is restricted to authorized management accounts.",
  "ليست لديك صلاحية لإضافة موظفات.": "You do not have permission to add staff.",
  "تعذر إكمال العملية": "Unable to complete the action",
  "نعم، متابعة": "Yes, continue",
  "تراجع": "Cancel",
  "جارٍ التنفيذ...": "Processing...",
  "إدارة الملفات الوظيفية والحضور والخدمات والرواتب من مساحة موحدة.": "Manage staff profiles, attendance, services and payroll from one workspace.",
  "إضافة موظفة": "Add staff member",
  "تحديث البيانات": "Refresh data",
  "إحصاءات الموظفات": "Staff statistics",
  "إجمالي الملفات": "Total profiles",
  "كل الملفات المتاحة حسب الصلاحية": "All profiles available to your account",
  "على رأس العمل": "Active staff",
  "نشطات ولسن في إجازة": "Active and not on leave",
  "في إجازة": "On leave",
  "إجازة حالية من سجل الموظفة": "Current leave from the staff record",
  "تحتاج متابعة": "Needs attention",
  "غير نشطة أو بدون خدمات أو ملف غير مكتمل": "Inactive, no assigned services, or incomplete profile",
  "جاري فتح ملف الموظفة...": "Opening staff profile...",
  "يتم تحميل الملف من السجل الوظيفي الحالي بدون تغيير مسارات الحسابات.": "Loading the current employment record without changing account links.",
  "البيانات الأساسية": "Basic information",
  "الحجز والدوام": "Booking & schedule",
  "الخدمات": "Services",
  "الملف": "Profile",
  "الإحصائيات والإجازات": "Statistics & leave",
  "الاسم والحالة والظهور": "Name, status and visibility",
  "الملفات والصور": "Files & photos",
  "الصورة والمستندات والمرفقات والسجل": "Photo, documents, attachments and history",
  "الخدمات المسندة للموظفة": "Services assigned to this staff member",
  "الدوام والشفتات": "Schedule & shifts",
  "الجدول والقوالب والسياسات": "Schedule, templates and policies",
  "الحضور": "Attendance",
  "السجل اليومي": "Daily record",
  "سجل الرواتب": "Payroll record",
  "القفل والحساب": "Locking and calculation",
  "الطلبات": "Requests",
  "طلبات الموظفة": "Staff requests",
  "رصيد الإجازات": "Leave balance",
  "الحالة والرصيد والسجل": "Status, balance and ledger",
  "الرسائل": "Messages",
  "التواصل الداخلي": "Internal communication",
  "قائمة الموظفات": "Staff directory",
  "دليل الموظفات": "Staff directory",
  "بحث سريع وفتح ملف الموظفة من قائمة موحدة.": "Search and open staff profiles from one directory.",
  "ملف": "profiles",
  "البحث": "Search",
  "الاسم، الجوال، البريد أو الرقم الوظيفي": "Name, mobile, email or employee ID",
  "بحث في الموظفات": "Search staff",
  "الظهور": "Visibility",
  "الظاهرات في الدليل": "Visible in directory",
  "المخفيات من الدليل": "Hidden from directory",
  "كل الموظفات": "All staff",
  "الحالة": "Status",
  "كل الحالات": "All statuses",
  "النشطات فقط": "Active only",
  "غير النشطات فقط": "Inactive only",
  "الخدمة": "Service",
  "كل الخدمات": "All services",
  "بدون خدمات مسندة": "No assigned services",
  "إعادة ضبط": "Reset",
  "جاري تحميل الموظفات": "Loading staff",
  "حساب يحتاج مراجعة": "Account needs review",
  "موظفة بدون اسم": "Unnamed staff member",
  "إداري": "Administrative",
  "قسم غير محدد": "Unassigned department",
  "نشطة": "Active",
  "غير نشطة": "Inactive",
  "لا يوجد بريد": "No email",
  "لا يوجد جوال": "No mobile",
  "حالة الملف": "Profile status",
  "يحتاج إكمال": "Needs completion",
  "مكتمل": "Complete",
  "أداء الشهر": "Monthly performance",
  "فتح الملف": "Open profile",
  "لا توجد موظفات مطابقة": "No matching staff",
  "غيّري البحث أو أعيدي ضبط الفلاتر لعرض الملفات المتاحة.": "Change the search or reset filters to show available profiles.",
  "إعادة ضبط الفلاتر": "Reset filters",
  "إدارة بيانات الموظفة": "Manage staff information",
  "جاري حفظ التغييرات": "Saving changes",
  "توجد تعديلات غير محفوظة": "There are unsaved changes",
  "يتم الآن تثبيت بيانات الموظفة في المصدر الرئيسي.": "Saving staff data to the canonical source.",
  "اضغط حفظ التغييرات لتثبيت القيم الحالية.": "Select Save changes to persist the current values.",
  "إلغاء التعديلات": "Discard changes",
  "جاري الحفظ...": "Saving...",
  "حفظ التغييرات": "Save changes",
  "موظفة": "Staff member",
  "ملف الموظفة": "Staff profile",
  "مسار التنقل": "Breadcrumb",
  "الموظفات": "Staff",
  "صورة الموظفة": "Staff photo",
  "عرض فقط": "Read only",
  "ملف موظفة فعلي": "Canonical staff profile",
  "خدمة مرتبطة": "linked service",
  "بدون خدمات مرتبطة": "No linked services",
  "ملخص الموظفة": "Staff summary",
  "غير محددة": "Not specified",
  "القسم الحالي": "Current section",
  "بيانات فعلية": "Canonical data",
  "مساحة الموظفة": "Staff workspace",
  "إنهاء الخدمة": "End employment",
  "العودة إلى الموظفات": "Back to staff",
  "أقسام ملف الموظفة": "Staff profile sections",
  "ليست لديك صلاحية إنشاء حسابات دخول. يمكنك إنشاء الملف الوظيفي فقط.": "You do not have permission to create login accounts. You can create the employment profile only.",
  "أدخل بريدًا إلكترونيًا صحيحًا لإنشاء حساب الدخول.": "Enter a valid email address to create the login account.",
  "كلمة المرور المؤقتة يجب أن تكون 6 أحرف على الأقل.": "The temporary password must be at least 6 characters.",
  "إلغاء": "Cancel",
  "إنشاء الموظفة وحساب الدخول": "Create staff member & login",
  "إنشاء الموظفة": "Create staff member",
  "الملف الحالي": "Current profile",
  "أكملي بيانات الموظفة، ثم أنشئي ملفها وحساب الدخول من نفس العملية.": "Complete the staff details, then create the profile and login in the same flow.",
  "تعديل بيانات الموظفة من نافذة موحدة.": "Edit staff information in one workspace.",
  "بدون خدمات": "No services",
  "عملية إضافة الموظفة": "Add staff member flow",
  "عملية موحدة": "Unified flow",
  "ملف الموظفة وحساب الدخول في مكان واحد": "Staff profile and login in one place",
  "أكملي الأقسام بالترتيب المناسب لك. النظام ينشئ ويربط حساب الدخول تلقائيًا بدون أي معرّفات أو خطوات تقنية يدوية.": "Complete the sections in any order. The system creates and links the login automatically without manual IDs or technical steps.",
  "حساب الدخول": "Login account",
  "تسجيل دخول الموظفة": "Staff login",
  "اختياري. عند تفعيله سيتم إنشاء الحساب وربطه بالملف الوظيفي تلقائيًا ضمن نفس عملية الحفظ.": "Optional. When enabled, the account is created and linked to the employment profile in the same save flow.",
  "إنشاء وتفعيل حساب دخول": "Create and activate login",
  "لا تملك صلاحية إنشاء حسابات دخول؛ سيتم إنشاء الملف الوظيفي فقط.": "You do not have permission to create login accounts; only the employment profile will be created.",
  "البريد الإلكتروني": "Email",
  "سيستخدم لتسجيل الدخول واستعادة كلمة المرور.": "Used for sign-in and password recovery.",
  "اختياري إذا لم يتم إنشاء حساب دخول.": "Optional when no login account is created.",
  "رقم الجوال": "Mobile number",
  "الدور": "Role",
  "الاستقبال": "Reception",
  "المحاسبة": "Accounting",
  "الإدارة": "Management",
  "كلمة المرور المؤقتة": "Temporary password",
  "يمكن للموظفة تغييرها لاحقًا.": "The staff member can change it later.",
  "توليد": "Generate",
  "إنهاء خدمة الموظفة": "End staff employment",
  "آخر يوم عمل": "Last working day",
  "اختر آخر يوم عمل": "Select last working day",
  "سبب إنهاء الخدمة": "Reason for ending employment",
  "لن يُنشئ النظام تاريخًا أو سببًا تلقائيًا، ولن يعيد تعيين الحجوزات تلقائيًا.": "The system will not generate a date or reason automatically and will not reassign bookings automatically.",
  "جارٍ إنهاء الخدمة...": "Ending employment...",
  "تأكيد إنهاء الخدمة": "Confirm end of employment",
  "المراجع:": "References:",
  "تعديل البصمة": "Edit attendance record",
  "تعديل سجل الحضور والانصراف": "Edit attendance record",
  "الحضور والانصراف": "Attendance",
  "وقت الحضور": "Check-in time",
  "اختاري ساعة ودقيقة الحضور فقط.": "Select the check-in hour and minute.",
  "مسح الوقت": "Clear time",
  "وقت الانصراف": "Check-out time",
  "يمكن تركه فارغًا إذا لم تسجل الموظفة انصرافًا.": "Leave blank if the staff member has not checked out.",
  "ملاحظة الإدارة": "Management note",
  "يُفضّل توضيح سبب تعديل البصمة لأغراض المراجعة.": "Add the reason for the attendance edit for audit purposes.",
  "مثال: تصحيح بصمة من الإدارة": "Example: attendance correction by management",
  "حفظ تعديل البصمة": "Save attendance edit",
  "لا توجد إجازة أسبوعية ثابتة.": "No fixed weekly day off.",
  "السبت": "Saturday",
  "الأحد": "Sunday",
  "الاثنين": "Monday",
  "الثلاثاء": "Tuesday",
  "الأربعاء": "Wednesday",
  "الخميس": "Thursday",
  "الجمعة": "Friday",
  "إدارة اسم الموظفة وحالة الحساب وظهورها في الموقع والحجز من مكوّن V2 مستقل.": "Manage the staff member's name, account status, and visibility across the website and booking.",
  "هوية الموظفة": "Staff identity",
  "الاسم المعتمد داخل الإدارة وواجهات العميلات.": "The canonical name used in management and client-facing interfaces.",
  "اسم الموظفة": "Staff name",
  "بداية سنة الخدمة": "Employment start date",
  "الظهور العام": "Public visibility",
  "تحديد مواضع ظهور الموظفة أمام العميلات.": "Control where this staff member appears to clients.",
  "إظهار في دليل الموظفات": "Show in staff directory",
  "إخفاؤها من الدليل لا يحذف الملف ولا يؤثر على الحضور أو الرواتب.": "Hiding the profile from the directory does not delete it or affect attendance or payroll.",
  "الظهور في صفحة من نحن": "Show on About page",
  "عرض الصورة والنبذة ضمن فريق الصالون.": "Show the photo and bio in the salon team section.",
  "الظهور في صفحة الحجز": "Show on booking page",
  "إتاحة اختيار الموظفة للخدمات المسندة.": "Allow clients to select this staff member for assigned services.",
  "الحساب غير نشط. فعّل حالة الحساب أولاً ثم أعد تفعيل الظهور في صفحة الحجز.": "The account is inactive. Activate the account first, then enable booking-page visibility.",
  "الحجز المباشر متوقف": "Direct booking disabled",
  "الحجوزات السابقة محفوظة، لكن الموظفة لن تظهر في الحجوزات الجديدة.": "Existing bookings are preserved, but this staff member will not appear in new bookings.",
  "الحساب": "Account",
  "دليل الموظفات": "Staff directory",
  "ظاهرة": "Visible",
  "مخفية": "Hidden",
  "من نحن": "About us",
  "الحجز": "Booking",
  "متاحة": "Available",
  "متوقفة": "Disabled",
  "الإجازة الأسبوعية": "Weekly day off",
  "تُعدل من جدول الدوام": "Managed from the work schedule",
  "وضع العرض فقط": "Read-only mode",
  "صلاحيتك تسمح بمراجعة البيانات دون تعديلها.": "Your permission allows you to review this data but not edit it.",
  "مستبدلة": "Replaced",
  "مؤرشفة": "Archived",
  "الحالية": "Current",
  "غير معروف": "Unknown",
  "الصورة الشخصية والملف العام": "Profile photo & public profile",
  "إدارة الصورة الشخصية والسيرة والتقييم وسجل الصور السابقة.": "Manage the profile photo, bio, rating, and previous photo history.",
  "الصورة جاهزة": "Photo available",
  "بدون صورة": "No photo",
  "الصورة الشخصية": "Profile photo",
  "الصورة الحالية المعتمدة في ملف الموظفة.": "The current approved photo for this staff profile.",
  "جاري رفع الصورة...": "Uploading photo...",
  "تغيير الصورة": "Change photo",
  "رفع صورة": "Upload photo",
  "حذف الصورة": "Remove photo",
  "لا توجد صورة": "No photo available",
  "ارفعي صورة شخصية من الجهاز.": "Upload a profile photo from this device.",
  "إدارة الصورة غير متاحة": "Photo management unavailable",
  "يجب حفظ سجل الموظفة أولًا قبل إدارة الصورة الشخصية.": "Save the staff record before managing the profile photo.",
  "التقييم": "Rating",
  "بيانات الملف العام": "Public profile information",
  "السيرة والتقييمات المرتبطة بملف الموظفة.": "Bio and ratings linked to this staff profile.",
  "رابط السيرة الذاتية": "CV link",
  "تقييم العرض": "Display rating",
  "عدد التقييمات": "Review count",
  "النبذة التعريفية": "Profile bio",
  "النص الذي يظهر للعميلات عند استعراض الموظفة.": "The text shown to clients when viewing this staff member.",
  "النبذة": "Bio",
  "سجل الصور السابقة": "Previous photo history",
  "الصور المستبدلة أو المؤرشفة تبقى محفوظة للسجل دون حذفها من R2.": "Replaced or archived photos remain in the record and are not deleted from R2.",
  "صورة شخصية": "Profile photo",
  "بدون تاريخ": "No date",
  "لا توجد صور سابقة": "No previous photos",
  "عند تغيير أو حذف الصورة الحالية ستظهر النسخ السابقة هنا.": "When the current photo is changed or removed, previous versions will appear here.",
  "إسناد الخدمات والبحث والتصفية من مكوّن V2 مستقل مرتبط بالقائمة الفعلية.": "Assign, search, and filter services from the live V2 service list.",
  "المتاح": "Available",
  "المحدد": "Selected",
  "نتائج التصفية": "Filtered results",
  "الأقسام": "Sections",
  "البحث والتصفية": "Search & filters",
  "قوائم V2 فقط، بدون select أصلي أو EmployeeSelect القديم.": "Uses the V2 controls and the canonical service list.",
  "اسم الخدمة أو القسم": "Service or section name",
  "القسم": "Section",
  "كل الأقسام": "All sections",
  "نطاق العرض": "Display scope",
  "الكل": "All",
  "المختارة": "Selected",
  "غير المختارة": "Not selected",
  "تحديد الظاهر": "Select visible",
  "مسح الكل": "Clear all",
  "الخدمات المتاحة": "Available services",
  "مدة غير محددة": "Duration not specified",
  "دقيقة": "min",
  "محددة": "Selected",
  "تحديد": "Select",
  "لا توجد نتائج": "No results",
  "غيّر البحث أو القسم أو نطاق العرض.": "Change the search, section, or display scope.",
  "عرض المزيد": "Show more",
  "الخدمات المختارة": "Selected services",
  "قائمة مستقلة مضغوطة.": "Compact selected-services list.",
  "البحث داخل المختارة": "Search selected services",
  "لا توجد نتيجة مطابقة": "No matching result",
  "لم تُحدد خدمات": "No services selected",
  "امسح عبارة البحث لعرض القائمة.": "Clear the search text to show the list.",
  "اختاري الخدمات من القائمة المجاورة.": "Select services from the adjacent list.",
};

export function employeeText(language: DashboardLanguage, arabic: string): string {
  if (language !== "en") return arabic;
  return employeeEnglish[arabic] || dashboardText(language, arabic);
}

type EmployeeLanguageContextValue = {
  language: DashboardLanguage;
  direction: "rtl" | "ltr";
  t: (arabic: string) => string;
  tr: (arabic: string, english: string) => string;
  "مغلق اليوم": "Closed today",
  "متاح اليوم": "Available today",
  "لا توجد استثناءات": "No exceptions",
  "ساعات العمل الفعلية اليوم": "Today's effective working hours",
  "ملخص مباشر بعد تطبيق الجدول الأسبوعي والاستثناءات المحفوظة.": "Live summary after applying the weekly schedule and saved exceptions.",
  "حالة اليوم": "Today's status",
  "حسب الجدول الفعلي": "Based on the effective schedule",
  "نافذة العمل": "Working window",
  "بعد تطبيق جميع الاستثناءات": "After applying all exceptions",
  "الاستثناءات": "Exceptions",
  "آخر تحديث": "Last updated",
  "تحديث تلقائي للحالة": "Status updates automatically",
  "سبب الإغلاق": "Closure reason",
  "الدوام القادم": "Next shift",
  "أقرب نافذة دوام قادمة حسب Malikat Core.": "The next working window according to Malikat Core.",
  "نافذة العودة": "Return window",
  "سيُحدد لاحقًا": "To be determined",
  "الميلادي": "Gregorian",
  "غير محدد": "Not specified",
  "الهجري": "Hijri",
  "المصدر": "Source",
  "حالة الدوام": "Schedule status",
  "نهاية الحالة": "Status end",
  "ملاحظة": "Note",
  "استثناءات الدوام": "Schedule exceptions",
  "الفترات والتواريخ والأسباب المحفوظة.": "Saved periods, dates, and reasons.",
  "ملخص الاستثناءات": "Exceptions summary",
  "العنوان": "Title",
  "الوقت": "Time",
  "تفاصيل": "Details",
  "محفوظ": "Saved",
  "استثناء محفوظ": "Saved exception",
  "لا توجد استثناءات دوام محفوظة حاليًا.": "There are no saved schedule exceptions.",
  "ملاحظة الجدول": "Schedule note",
  "تفاصيل احتساب الدوام": "Schedule calculation details",
  "المصدر والجدول الأسبوعي والنتيجة النهائية.": "Source, weekly schedule, and final result.",
  "البند": "Item",
  "القيمة": "Value",
  "لا توجد تفاصيل احتساب إضافية.": "No additional calculation details.",
  "راحة أسبوعية": "Weekly day off",
  "راحة أسبوعية مؤقتة": "Temporary weekly day off",
  "يوم راحة استثنائي": "Exceptional day off",
  "عمل استثنائي في يوم الراحة": "Exceptional work on a day off",
  "تكليف يوم الراحة": "Day-off work assignment",
  "جدول الدوام الأسبوعي": "Weekly work schedule",
  "نقل مؤقت للراحة الأسبوعية": "Temporary weekly-day-off transfer",
  "استثناء يومي معتمد": "Approved daily exception",
  "مجدول": "Scheduled",
  "تعمل الآن": "Working now",
  "خارج الدوام": "Off duty",
  "استثناء يومي": "Daily exception",
  "راحة / إغلاق لهذا اليوم": "Day off / closed today",
  "وقت مخصص": "Custom hours",
  "شفت بديل": "Alternate shift",
  "شفت اليوم من جدول الموظفة": "Today's shift from the staff schedule",
  "شفت افتراضي قديم": "Legacy default shift",
  "تعيين احتياطي للموظفات القديمة": "Fallback assignment for legacy staff",
  "تعذر تحميل شفتات الحضور من Core. تم إيقاف تعديلات الحضور حتى ينجح التحقق.": "Could not load attendance shifts from Core. Attendance edits are disabled until verification succeeds.",
  "جاري التحقق من بيانات Core. لا يمكن تعديل البصمة الآن.": "Verifying Core data. Attendance records cannot be edited yet.",
  "ليست لديك صلاحية لمسح وقت البصمة.": "You do not have permission to clear attendance times.",
  "لا يوجد وقت حضور لمسحه في هذا اليوم.": "There is no check-in time to clear for this day.",
  "لا يوجد وقت انصراف لمسحه في هذا اليوم.": "There is no check-out time to clear for this day.",
  "الانصراف": "Check-out",
  "تم مسح وقت الحضور فقط، وبقيت بقية سجلات اليوم كما هي.": "The check-in time was cleared; the rest of the day's records were preserved.",
  "تم مسح وقت الانصراف فقط، وبقيت بقية سجلات اليوم كما هي.": "The check-out time was cleared; the rest of the day's records were preserved.",
  "إدارة أوقات بصمة اليوم المحدد": "Manage attendance times for the selected day",
  "جاري مسح الحضور...": "Clearing check-in...",
  "مسح وقت الحضور": "Clear check-in time",
  "جاري مسح الانصراف...": "Clearing check-out...",
  "مسح وقت الانصراف": "Clear check-out time",
  "تحديث": "Refresh",
  "إعادة المحاولة": "Try again",
  "نموذج التحميل": "Loading state",
  "جارٍ تحميل بيانات التبويب": "Loading tab data",
  "لا توجد بيانات بعد": "No data yet",
  "تظهر هنا البيانات عند إضافتها أو توفرها للموظفة.": "Data will appear here when it is added or available for the staff member.",
  "تعذر تحميل القسم": "Could not load section",
  "احتفظنا بالبيانات الحالية. أعد المحاولة بعد التحقق من الاتصال.": "Current data was preserved. Try again after checking the connection.",
  "تعذر جلب البيانات التجريبية": "Could not load preview data",
  "ملف الموظفة الداخلي": "Internal staff profile",
  "دليل الاستخدام": "Usage guide",
  "فهمت": "Got it",
  "ما الغرض من هذا القسم؟": "What is this section for?",
  "متى أستخدم هذا القسم؟": "When should I use this section?",
  "حدد الحالة الصحيحة قبل إجراء أي تعديل.": "Choose the correct scenario before making changes.",
  "استخدمه عندما": "Use it when",
  "لا تستخدمه من أجل": "Do not use it for",
  "مثال عملي": "Practical example",
  "مثال مبسط يوضح المدخلات والنتيجة داخل النظام.": "A simple example showing the inputs and expected result.",
  "ما الذي تفعله؟": "What should you do?",
  "النتيجة": "Result",
  "طريقة الاستخدام": "How to use",
  "اتبع الخطوات بالترتيب لتجنب تضارب الإعدادات.": "Follow the steps in order to avoid conflicting settings.",
  "مهم": "Important",

};

const EmployeeLanguageContext = createContext<EmployeeLanguageContextValue>({
  language: "ar",
  direction: "rtl",
  t: (arabic) => arabic,
  tr: (arabic) => arabic,
});

export function EmployeeLanguageProvider({
  language,
  children,
}: {
  language: DashboardLanguage;
  children: ReactNode;
}) {
  const value = useMemo<EmployeeLanguageContextValue>(
    () => ({
      language,
      direction: language === "en" ? "ltr" : "rtl",
      t: (arabic) => employeeText(language, arabic),
      tr: (arabic, english) => (language === "en" ? english : arabic),
    }),
    [language]
  );

  return (
    <EmployeeLanguageContext.Provider value={value}>
      {children}
    </EmployeeLanguageContext.Provider>
  );
}

export function useEmployeeLanguage() {
  return useContext(EmployeeLanguageContext);
}
