import { createContext, useContext, useMemo, type ReactNode } from "react";
import {
  dashboardText,
  type DashboardLanguage,
} from "../../helpers/dashboardLanguage";

const employeeEnglish: Record<string, string> = {
  "غير مصرح": "Unauthorized",
  "سجّل دخول ثم جرّب مرة أخرى.": "Sign in, then try again.",
  "صلاحيات غير كافية": "Insufficient permissions",
  "هذه الصفحة مخصصة للإدارة.": "This page is restricted to authorized management accounts.",
  "ليست لديك صلاحية لإضافة موظفات.": "You do not have permission to add staff.",
  "تعذر إكمال العملية": "Unable to complete the action",
  "نعم، متابعة": "Yes, continue",
  "تراجع": "Cancel",
  "جارٍ التنفيذ...": "Processing...",
  "إدارة الملفات الوظيفية والحضور والخدمات والرواتب من مساحة موحدة.": "Manage staff profiles, attendance, services and payroll from one workspace.",
  "إضافة موظفة": "Add staff member",
  "تحديث البيانات": "Refresh data",
  "إحصاءات الموظفات": "Staff statistics",
  "إجمالي الملفات": "Total profiles",
  "كل الملفات المتاحة حسب الصلاحية": "All profiles available to your account",
  "على رأس العمل": "Active staff",
  "نشطات ولسن في إجازة": "Active and not on leave",
  "في إجازة": "On leave",
  "إجازة حالية من سجل الموظفة": "Current leave from the staff record",
  "تحتاج متابعة": "Needs attention",
  "غير نشطة أو بدون خدمات أو ملف غير مكتمل": "Inactive, no assigned services, or incomplete profile",
  "جاري فتح ملف الموظفة...": "Opening staff profile...",
  "يتم تحميل الملف من السجل الوظيفي الحالي بدون تغيير مسارات الحسابات.": "Loading the current employment record without changing account links.",
  "البيانات الأساسية": "Basic information",
  "الحجز والدوام": "Booking & schedule",
  "الخدمات": "Services",
  "الملف": "Profile",
  "الإحصائيات والإجازات": "Statistics & leave",
  "الاسم والحالة والظهور": "Name, status and visibility",
  "الملفات والصور": "Files & photos",
  "الصورة والمستندات والمرفقات والسجل": "Photo, documents, attachments and history",
  "الخدمات المسندة للموظفة": "Services assigned to this staff member",
  "الدوام والشفتات": "Schedule & shifts",
  "الجدول والقوالب والسياسات": "Schedule, templates and policies",
  "الحضور": "Attendance",
  "السجل اليومي": "Daily record",
  "سجل الرواتب": "Payroll record",
  "القفل والحساب": "Locking and calculation",
  "الطلبات": "Requests",
  "طلبات الموظفة": "Staff requests",
  "رصيد الإجازات": "Leave balance",
  "الحالة والرصيد والسجل": "Status, balance and ledger",
  "الرسائل": "Messages",
  "التواصل الداخلي": "Internal communication",
  "قائمة الموظفات": "Staff directory",
  "دليل الموظفات": "Staff directory",
  "بحث سريع وفتح ملف الموظفة من قائمة موحدة.": "Search and open staff profiles from one directory.",
  "ملف": "profiles",
  "البحث": "Search",
  "الاسم، الجوال، البريد أو الرقم الوظيفي": "Name, mobile, email or employee ID",
  "بحث في الموظفات": "Search staff",
  "الظهور": "Visibility",
  "الظاهرات في الدليل": "Visible in directory",
  "المخفيات من الدليل": "Hidden from directory",
  "كل الموظفات": "All staff",
  "الحالة": "Status",
  "كل الحالات": "All statuses",
  "النشطات فقط": "Active only",
  "غير النشطات فقط": "Inactive only",
  "الخدمة": "Service",
  "كل الخدمات": "All services",
  "بدون خدمات مسندة": "No assigned services",
  "إعادة ضبط": "Reset",
  "جاري تحميل الموظفات": "Loading staff",
  "حساب يحتاج مراجعة": "Account needs review",
  "موظفة بدون اسم": "Unnamed staff member",
  "إداري": "Administrative",
  "قسم غير محدد": "Unassigned department",
  "نشطة": "Active",
  "غير نشطة": "Inactive",
  "لا يوجد بريد": "No email",
  "لا يوجد جوال": "No mobile",
  "حالة الملف": "Profile status",
  "يحتاج إكمال": "Needs completion",
  "مكتمل": "Complete",
  "أداء الشهر": "Monthly performance",
  "فتح الملف": "Open profile",
  "لا توجد موظفات مطابقة": "No matching staff",
  "غيّري البحث أو أعيدي ضبط الفلاتر لعرض الملفات المتاحة.": "Change the search or reset filters to show available profiles.",
  "إعادة ضبط الفلاتر": "Reset filters",
  "إدارة بيانات الموظفة": "Manage staff information",
  "جاري حفظ التغييرات": "Saving changes",
  "توجد تعديلات غير محفوظة": "There are unsaved changes",
  "يتم الآن تثبيت بيانات الموظفة في المصدر الرئيسي.": "Saving staff data to the canonical source.",
  "اضغط حفظ التغييرات لتثبيت القيم الحالية.": "Select Save changes to persist the current values.",
  "إلغاء التعديلات": "Discard changes",
  "جاري الحفظ...": "Saving...",
  "حفظ التغييرات": "Save changes",
  "موظفة": "Staff member",
  "ملف الموظفة": "Staff profile",
  "مسار التنقل": "Breadcrumb",
  "الموظفات": "Staff",
  "صورة الموظفة": "Staff photo",
  "عرض فقط": "Read only",
  "ملف موظفة فعلي": "Canonical staff profile",
  "خدمة مرتبطة": "linked service",
  "بدون خدمات مرتبطة": "No linked services",
  "ملخص الموظفة": "Staff summary",
  "غير محددة": "Not specified",
  "القسم الحالي": "Current section",
  "بيانات فعلية": "Canonical data",
  "مساحة الموظفة": "Staff workspace",
  "إنهاء الخدمة": "End employment",
  "العودة إلى الموظفات": "Back to staff",
  "أقسام ملف الموظفة": "Staff profile sections",
  "ليست لديك صلاحية إنشاء حسابات دخول. يمكنك إنشاء الملف الوظيفي فقط.": "You do not have permission to create login accounts. You can create the employment profile only.",
  "أدخل بريدًا إلكترونيًا صحيحًا لإنشاء حساب الدخول.": "Enter a valid email address to create the login account.",
  "كلمة المرور المؤقتة يجب أن تكون 6 أحرف على الأقل.": "The temporary password must be at least 6 characters.",
  "إلغاء": "Cancel",
  "إنشاء الموظفة وحساب الدخول": "Create staff member & login",
  "إنشاء الموظفة": "Create staff member",
  "الملف الحالي": "Current profile",
  "أكملي بيانات الموظفة، ثم أنشئي ملفها وحساب الدخول من نفس العملية.": "Complete the staff details, then create the profile and login in the same flow.",
  "تعديل بيانات الموظفة من نافذة موحدة.": "Edit staff information in one workspace.",
  "بدون خدمات": "No services",
  "عملية إضافة الموظفة": "Add staff member flow",
  "عملية موحدة": "Unified flow",
  "ملف الموظفة وحساب الدخول في مكان واحد": "Staff profile and login in one place",
  "أكملي الأقسام بالترتيب المناسب لك. النظام ينشئ ويربط حساب الدخول تلقائيًا بدون أي معرّفات أو خطوات تقنية يدوية.": "Complete the sections in any order. The system creates and links the login automatically without manual IDs or technical steps.",
  "حساب الدخول": "Login account",
  "تسجيل دخول الموظفة": "Staff login",
  "اختياري. عند تفعيله سيتم إنشاء الحساب وربطه بالملف الوظيفي تلقائيًا ضمن نفس عملية الحفظ.": "Optional. When enabled, the account is created and linked to the employment profile in the same save flow.",
  "إنشاء وتفعيل حساب دخول": "Create and activate login",
  "لا تملك صلاحية إنشاء حسابات دخول؛ سيتم إنشاء الملف الوظيفي فقط.": "You do not have permission to create login accounts; only the employment profile will be created.",
  "البريد الإلكتروني": "Email",
  "سيستخدم لتسجيل الدخول واستعادة كلمة المرور.": "Used for sign-in and password recovery.",
  "اختياري إذا لم يتم إنشاء حساب دخول.": "Optional when no login account is created.",
  "رقم الجوال": "Mobile number",
  "الدور": "Role",
  "الاستقبال": "Reception",
  "المحاسبة": "Accounting",
  "الإدارة": "Management",
  "كلمة المرور المؤقتة": "Temporary password",
  "يمكن للموظفة تغييرها لاحقًا.": "The staff member can change it later.",
  "توليد": "Generate",
  "إنهاء خدمة الموظفة": "End staff employment",
  "آخر يوم عمل": "Last working day",
  "اختر آخر يوم عمل": "Select last working day",
  "سبب إنهاء الخدمة": "Reason for ending employment",
  "لن يُنشئ النظام تاريخًا أو سببًا تلقائيًا، ولن يعيد تعيين الحجوزات تلقائيًا.": "The system will not generate a date or reason automatically and will not reassign bookings automatically.",
  "جارٍ إنهاء الخدمة...": "Ending employment...",
  "تأكيد إنهاء الخدمة": "Confirm end of employment",
  "المراجع:": "References:",
  "تعديل البصمة": "Edit attendance record",
  "تعديل سجل الحضور والانصراف": "Edit attendance record",
  "الحضور والانصراف": "Attendance",
  "وقت الحضور": "Check-in time",
  "اختاري ساعة ودقيقة الحضور فقط.": "Select the check-in hour and minute.",
  "مسح الوقت": "Clear time",
  "وقت الانصراف": "Check-out time",
  "يمكن تركه فارغًا إذا لم تسجل الموظفة انصرافًا.": "Leave blank if the staff member has not checked out.",
  "ملاحظة الإدارة": "Management note",
  "يُفضّل توضيح سبب تعديل البصمة لأغراض المراجعة.": "Add the reason for the attendance edit for audit purposes.",
  "مثال: تصحيح بصمة من الإدارة": "Example: attendance correction by management",
  "حفظ تعديل البصمة": "Save attendance edit",
  "لا توجد إجازة أسبوعية ثابتة.": "No fixed weekly day off.",
  "السبت": "Saturday",
  "الأحد": "Sunday",
  "الاثنين": "Monday",
  "الثلاثاء": "Tuesday",
  "الأربعاء": "Wednesday",
  "الخميس": "Thursday",
  "الجمعة": "Friday",
  "إدارة اسم الموظفة وحالة الحساب وظهورها في الموقع والحجز من مكوّن V2 مستقل.": "Manage the staff member's name, account status, and visibility across the website and booking.",
  "هوية الموظفة": "Staff identity",
  "الاسم المعتمد داخل الإدارة وواجهات العميلات.": "The canonical name used in management and client-facing interfaces.",
  "اسم الموظفة": "Staff name",
  "بداية سنة الخدمة": "Employment start date",
  "الظهور العام": "Public visibility",
  "تحديد مواضع ظهور الموظفة أمام العميلات.": "Control where this staff member appears to clients.",
  "إظهار في دليل الموظفات": "Show in staff directory",
  "إخفاؤها من الدليل لا يحذف الملف ولا يؤثر على الحضور أو الرواتب.": "Hiding the profile from the directory does not delete it or affect attendance or payroll.",
  "الظهور في صفحة من نحن": "Show on About page",
  "عرض الصورة والنبذة ضمن فريق الصالون.": "Show the photo and bio in the salon team section.",
  "الظهور في صفحة الحجز": "Show on booking page",
  "إتاحة اختيار الموظفة للخدمات المسندة.": "Allow clients to select this staff member for assigned services.",
  "الحساب غير نشط. فعّل حالة الحساب أولاً ثم أعد تفعيل الظهور في صفحة الحجز.": "The account is inactive. Activate the account first, then enable booking-page visibility.",
  "الحجز المباشر متوقف": "Direct booking disabled",
  "الحجوزات السابقة محفوظة، لكن الموظفة لن تظهر في الحجوزات الجديدة.": "Existing bookings are preserved, but this staff member will not appear in new bookings.",
  "الحساب": "Account",
  "دليل الموظفات": "Staff directory",
  "ظاهرة": "Visible",
  "مخفية": "Hidden",
  "من نحن": "About us",
  "الحجز": "Booking",
  "متاحة": "Available",
  "متوقفة": "Disabled",
  "الإجازة الأسبوعية": "Weekly day off",
  "تُعدل من جدول الدوام": "Managed from the work schedule",
  "وضع العرض فقط": "Read-only mode",
  "صلاحيتك تسمح بمراجعة البيانات دون تعديلها.": "Your permission allows you to review this data but not edit it.",
  "مستبدلة": "Replaced",
  "مؤرشفة": "Archived",
  "الحالية": "Current",
  "غير معروف": "Unknown",
  "الصورة الشخصية والملف العام": "Profile photo & public profile",
  "إدارة الصورة الشخصية والسيرة والتقييم وسجل الصور السابقة.": "Manage the profile photo, bio, rating, and previous photo history.",
  "الصورة جاهزة": "Photo available",
  "بدون صورة": "No photo",
  "الصورة الشخصية": "Profile photo",
  "الصورة الحالية المعتمدة في ملف الموظفة.": "The current approved photo for this staff profile.",
  "جاري رفع الصورة...": "Uploading photo...",
  "تغيير الصورة": "Change photo",
  "رفع صورة": "Upload photo",
  "حذف الصورة": "Remove photo",
  "لا توجد صورة": "No photo available",
  "ارفعي صورة شخصية من الجهاز.": "Upload a profile photo from this device.",
  "إدارة الصورة غير متاحة": "Photo management unavailable",
  "يجب حفظ سجل الموظفة أولًا قبل إدارة الصورة الشخصية.": "Save the staff record before managing the profile photo.",
  "التقييم": "Rating",
  "بيانات الملف العام": "Public profile information",
  "السيرة والتقييمات المرتبطة بملف الموظفة.": "Bio and ratings linked to this staff profile.",
  "رابط السيرة الذاتية": "CV link",
  "تقييم العرض": "Display rating",
  "عدد التقييمات": "Review count",
  "النبذة التعريفية": "Profile bio",
  "النص الذي يظهر للعميلات عند استعراض الموظفة.": "The text shown to clients when viewing this staff member.",
  "النبذة": "Bio",
  "سجل الصور السابقة": "Previous photo history",
  "الصور المستبدلة أو المؤرشفة تبقى محفوظة للسجل دون حذفها من R2.": "Replaced or archived photos remain in the record and are not deleted from R2.",
  "صورة شخصية": "Profile photo",
  "بدون تاريخ": "No date",
  "لا توجد صور سابقة": "No previous photos",
  "عند تغيير أو حذف الصورة الحالية ستظهر النسخ السابقة هنا.": "When the current photo is changed or removed, previous versions will appear here.",
  "إسناد الخدمات والبحث والتصفية من مكوّن V2 مستقل مرتبط بالقائمة الفعلية.": "Assign, search, and filter services from the live V2 service list.",
  "المتاح": "Available",
  "المحدد": "Selected",
  "نتائج التصفية": "Filtered results",
  "الأقسام": "Sections",
  "البحث والتصفية": "Search & filters",
  "قوائم V2 فقط، بدون select أصلي أو EmployeeSelect القديم.": "Uses the V2 controls and the canonical service list.",
  "اسم الخدمة أو القسم": "Service or section name",
  "القسم": "Section",
  "كل الأقسام": "All sections",
  "نطاق العرض": "Display scope",
  "الكل": "All",
  "المختارة": "Selected",
  "غير المختارة": "Not selected",
  "تحديد الظاهر": "Select visible",
  "مسح الكل": "Clear all",
  "الخدمات المتاحة": "Available services",
  "مدة غير محددة": "Duration not specified",
  "دقيقة": "min",
  "محددة": "Selected",
  "تحديد": "Select",
  "لا توجد نتائج": "No results",
  "غيّر البحث أو القسم أو نطاق العرض.": "Change the search, section, or display scope.",
  "عرض المزيد": "Show more",
  "الخدمات المختارة": "Selected services",
  "قائمة مستقلة مضغوطة.": "Compact selected-services list.",
  "البحث داخل المختارة": "Search selected services",
  "لا توجد نتيجة مطابقة": "No matching result",
  "لم تُحدد خدمات": "No services selected",
  "امسح عبارة البحث لعرض القائمة.": "Clear the search text to show the list.",
  "اختاري الخدمات من القائمة المجاورة.": "Select services from the adjacent list.",
};

export function employeeText(language: DashboardLanguage, arabic: string): string {
  if (language !== "en") return arabic;
  return employeeEnglish[arabic] || dashboardText(language, arabic);
}

type EmployeeLanguageContextValue = {
  language: DashboardLanguage;
  direction: "rtl" | "ltr";
  t: (arabic: string) => string;
  tr: (arabic: string, english: string) => string;
  "مغلق اليوم": "Closed today",
  "متاح اليوم": "Available today",
  "لا توجد استثناءات": "No exceptions",
  "ساعات العمل الفعلية اليوم": "Today's effective working hours",
  "ملخص مباشر بعد تطبيق الجدول الأسبوعي والاستثناءات المحفوظة.": "Live summary after applying the weekly schedule and saved exceptions.",
  "حالة اليوم": "Today's status",
  "حسب الجدول الفعلي": "Based on the effective schedule",
  "نافذة العمل": "Working window",
  "بعد تطبيق جميع الاستثناءات": "After applying all exceptions",
  "الاستثناءات": "Exceptions",
  "آخر تحديث": "Last updated",
  "تحديث تلقائي للحالة": "Status updates automatically",
  "سبب الإغلاق": "Closure reason",
  "الدوام القادم": "Next shift",
  "أقرب نافذة دوام قادمة حسب Malikat Core.": "The next working window according to Malikat Core.",
  "نافذة العودة": "Return window",
  "سيُحدد لاحقًا": "To be determined",
  "الميلادي": "Gregorian",
  "غير محدد": "Not specified",
  "الهجري": "Hijri",
  "المصدر": "Source",
  "حالة الدوام": "Schedule status",
  "نهاية الحالة": "Status end",
  "ملاحظة": "Note",
  "استثناءات الدوام": "Schedule exceptions",
  "الفترات والتواريخ والأسباب المحفوظة.": "Saved periods, dates, and reasons.",
  "ملخص الاستثناءات": "Exceptions summary",
  "العنوان": "Title",
  "الوقت": "Time",
  "تفاصيل": "Details",
  "محفوظ": "Saved",
  "استثناء محفوظ": "Saved exception",
  "لا توجد استثناءات دوام محفوظة حاليًا.": "There are no saved schedule exceptions.",
  "ملاحظة الجدول": "Schedule note",
  "تفاصيل احتساب الدوام": "Schedule calculation details",
  "المصدر والجدول الأسبوعي والنتيجة النهائية.": "Source, weekly schedule, and final result.",
  "البند": "Item",
  "القيمة": "Value",
  "لا توجد تفاصيل احتساب إضافية.": "No additional calculation details.",
  "راحة أسبوعية": "Weekly day off",
  "راحة أسبوعية مؤقتة": "Temporary weekly day off",
  "يوم راحة استثنائي": "Exceptional day off",
  "عمل استثنائي في يوم الراحة": "Exceptional work on a day off",
  "تكليف يوم الراحة": "Day-off work assignment",
  "جدول الدوام الأسبوعي": "Weekly work schedule",
  "نقل مؤقت للراحة الأسبوعية": "Temporary weekly-day-off transfer",
  "استثناء يومي معتمد": "Approved daily exception",
  "مجدول": "Scheduled",
  "تعمل الآن": "Working now",
  "خارج الدوام": "Off duty",
  "استثناء يومي": "Daily exception",
  "راحة / إغلاق لهذا اليوم": "Day off / closed today",
  "وقت مخصص": "Custom hours",
  "شفت بديل": "Alternate shift",
  "شفت اليوم من جدول الموظفة": "Today's shift from the staff schedule",
  "شفت افتراضي قديم": "Legacy default shift",
  "تعيين احتياطي للموظفات القديمة": "Fallback assignment for legacy staff",
  "تعذر تحميل شفتات الحضور من Core. تم إيقاف تعديلات الحضور حتى ينجح التحقق.": "Could not load attendance shifts from Core. Attendance edits are disabled until verification succeeds.",
  "جاري التحقق من بيانات Core. لا يمكن تعديل البصمة الآن.": "Verifying Core data. Attendance records cannot be edited yet.",
  "ليست لديك صلاحية لمسح وقت البصمة.": "You do not have permission to clear attendance times.",
  "لا يوجد وقت حضور لمسحه في هذا اليوم.": "There is no check-in time to clear for this day.",
  "لا يوجد وقت انصراف لمسحه في هذا اليوم.": "There is no check-out time to clear for this day.",
  "الانصراف": "Check-out",
  "تم مسح وقت الحضور فقط، وبقيت بقية سجلات اليوم كما هي.": "The check-in time was cleared; the rest of the day's records were preserved.",
  "تم مسح وقت الانصراف فقط، وبقيت بقية سجلات اليوم كما هي.": "The check-out time was cleared; the rest of the day's records were preserved.",
  "إدارة أوقات بصمة اليوم المحدد": "Manage attendance times for the selected day",
  "جاري مسح الحضور...": "Clearing check-in...",
  "مسح وقت الحضور": "Clear check-in time",
  "جاري مسح الانصراف...": "Clearing check-out...",
  "مسح وقت الانصراف": "Clear check-out time",
  "تحديث": "Refresh",
  "إعادة المحاولة": "Try again",
  "نموذج التحميل": "Loading state",
  "جارٍ تحميل بيانات التبويب": "Loading tab data",
  "لا توجد بيانات بعد": "No data yet",
  "تظهر هنا البيانات عند إضافتها أو توفرها للموظفة.": "Data will appear here when it is added or available for the staff member.",
  "تعذر تحميل القسم": "Could not load section",
  "احتفظنا بالبيانات الحالية. أعد المحاولة بعد التحقق من الاتصال.": "Current data was preserved. Try again after checking the connection.",
  "تعذر جلب البيانات التجريبية": "Could not load preview data",
  "ملف الموظفة الداخلي": "Internal staff profile",
  "دليل الاستخدام": "Usage guide",
  "فهمت": "Got it",
  "ما الغرض من هذا القسم؟": "What is this section for?",
  "متى أستخدم هذا القسم؟": "When should I use this section?",
  "حدد الحالة الصحيحة قبل إجراء أي تعديل.": "Choose the correct scenario before making changes.",
  "استخدمه عندما": "Use it when",
  "لا تستخدمه من أجل": "Do not use it for",
  "مثال عملي": "Practical example",
  "مثال مبسط يوضح المدخلات والنتيجة داخل النظام.": "A simple example showing the inputs and expected result.",
  "ما الذي تفعله؟": "What should you do?",
  "النتيجة": "Result",
  "طريقة الاستخدام": "How to use",
  "اتبع الخطوات بالترتيب لتجنب تضارب الإعدادات.": "Follow the steps in order to avoid conflicting settings.",
  "مهم": "Important",

  "اختر لكل يوم قالب شفت أو راحة أسبوعية. أوقات وسياسات الدوام تُسحب تلقائيًا من القالب الموجود في نفس الصفحة.": "Choose a shift template or weekly day off for each day. Working times and attendance policies are inherited from the selected template.",
  "شرح الدوام والشفتات": "Explain schedule & shifts",
  "أيام العمل": "Working days",
  "أيام الراحة الأسبوعية": "Weekly days off",
  "قوالب الشفتات": "Shift templates",
  "محدد": "Selected",
  "إعدادات الجدول": "Schedule settings",
  "تاريخ بدء التطبيق وسبب تغيير جدول الموظفة.": "Set the effective date and document the reason for changing this staff schedule.",
  "شرح إعدادات الجدول": "Explain schedule settings",
  "الشفت هو مصدر الوقت والسياسة": "The shift is the source of time and policy",
  "لا يمكن تعديل بداية أو نهاية الدوام من جدول الأسبوع. عدّل قالب الشفت من قسم قوالب الشفتات في نفس الصفحة، أو استخدم استثناءً ليوم محدد.": "Start and end times cannot be edited from the weekly schedule. Edit the shift template or use a one-day exception.",
  "تطبيق الجدول من": "Schedule effective from",
  "تاريخ نهاية التوظيف": "Employment end date",
  "سبب تغيير الجدول": "Reason for schedule change",
  "اختيار موقع أو نطاق يسمح بالبصمة.": "Choose the location or zone where attendance clocking is allowed.",
  "شرح نطاق الحضور": "Explain attendance zone",
  "جاري التحميل": "Loading",
  "اختر النطاق": "Select zone",
  "بدون نطاق محدد": "No specific zone",
  "لا يوجد نطاق حضور": "No attendance zone",
  "تحديد النطاق يقلل أخطاء البصمة خارج الموقع.": "Selecting a zone reduces off-site clocking errors.",
  "الأسبوع التشغيلي": "Operational week",
  "لكل يوم: شفت من القوالب أو راحة أسبوعية.": "For each day, choose a shift template or a weekly day off.",
  "شرح الأسبوع التشغيلي": "Explain operational week",
  "تعذر تحميل قوالب الشفتات": "Could not load shift templates",
  "لا توجد قوالب شفتات": "No shift templates",
  "أنشئ قالب شفت واحدًا على الأقل من قسم قوالب الشفتات والاستثناءات الموجود أسفل هذه الصفحة، ثم ارجع لتوزيعه على أيام العمل.": "Create at least one shift template in the shifts and exceptions section below, then assign it to working days.",
  "يوم عمل": "Working day",
  "الشفت": "Shift",
  "جاري تحميل الشفتات": "Loading shifts",
  "اختر الشفت": "Select shift",
  "إغلاق البصمة غير مفعّل.": "Attendance lock is disabled.",
  "لا يوجد": "None",
  "إجازة": "Leave",
  "راحة": "Rest",
  "راحة / يوم استثنائي": "Rest / exceptional day",
  "تحميل": "Loading",
  "تعذر التحميل": "Load failed",
  "لا توجد سجلات": "No records",
  "بيانات محملة": "Data loaded",
  "عرض وتعديل سجل الحضور من مكوّن V2 مستقل.": "View and manage attendance records in the V2 workspace.",
  "أيام الشهر": "Days in month",
  "أيام عليها بصمة": "Days with attendance",
  "دقائق التأخير": "Late minutes",
  "أيام الإجازة": "Leave days",
  "تعذر تحديث سجل الحضور": "Could not refresh attendance records",
  "الأيام السابقة لتاريخ المباشرة لا تدخل في الحضور أو الغياب.": "Days before the employment start date are excluded from attendance and absence.",
  "فلتر الحضور": "Attendance filter",
  "اختر الشهر، ثم اضغط على أي يوم من التقويم لعرض تفاصيله.": "Choose a month, then select any day in the calendar to view its details.",
  "الشهر": "Month",
  "الشفت المطبق اليوم": "Effective shift for today",
  "المصدر الفعلي حسب أولوية: إجازة، استثناء، شفت محدد، جدول الموظفة، ثم دوام الصالون.": "The effective source follows this priority: leave, exception, assigned shift, staff schedule, then salon schedule.",
  "يتم تحديده تلقائياً من البيانات": "Determined automatically from the data",
  "الوقت الفعلي": "Effective time",
  "جاري تحميل الحضور": "Loading attendance",
  "يتم تحميل سجلات الحضور الفعلية لهذا الشهر.": "Loading the actual attendance records for this month.",
  "جاري تحميل سجل حضور الموظفة": "Loading staff attendance",
  "تعذر تحميل سجل الحضور": "Could not load attendance records",
  "تعذر تحميل سجل حضور الموظفة. أعد المحاولة بعد التحقق من الاتصال.": "Could not load the staff attendance record. Check the connection and try again.",
  "لا توجد بصمات أو إجازات معتمدة في الشهر المحدد.": "There are no attendance records or approved leave entries in the selected month.",
  "اضغطي على أي يوم مسجل لفتح تفاصيله.": "Select any recorded day to open its details.",
  "تأخير": "Late",
  "نقص ساعات": "Missing hours",
  "غير مكتمل": "Incomplete",
  "غياب": "Absent",
  "دوام في راحة أسبوعية": "Worked on weekly day off",
  "فترة الاستئذان": "Permission period",
  "تفاصيل اليوم المحدد": "Selected day details",
  "إلغاء الاستئذان": "Cancel permission",
  "إلغاء الإجازة": "Cancel leave",
  "تفاصيل يوم الحضور": "Attendance day details",
  "عرض البصمات والشفت والموقع والمراجعات.": "View attendance punches, shift, location, and review details.",
  "الدخول": "Check-in",
  "الخروج": "Check-out",
  "الحدث": "Event",
  "دخول": "Check-in",
  "خروج": "Check-out",
  "مكتمل": "Complete",
  "غير مسجل": "Not recorded",
  "ملاحظة المراجعة": "Review note",
  "سجل الشهر": "Monthly record",
  "السجلات المحملة للموظفة في الشهر الحالي.": "Attendance records loaded for this staff member in the current month.",
  "اليوم": "Day",
  "إجراء": "Action",
  "لا توجد سجلات حضور في هذا الشهر.": "There are no attendance records for this month.",
  "هيكل الراتب، إعدادات الدوام، وتصنيف التأمينات التي يستخدمها مسير الرواتب.": "Salary structure, work settings, and insurance classification used by payroll.",
  "الإضافي مفعّل": "Overtime enabled",
  "الإضافي متوقف": "Overtime disabled",
  "حفظ إعدادات الراتب والتأمينات": "Save payroll & insurance settings",
  "هيكل الراتب والدوام": "Salary & work structure",
  "الراتب الأساسي والبدلات محفوظة كعناصر مستقلة؛ إجمالي الراتب التعاقدي يُحسب تلقائيًا من مجموعها.": "Base salary and allowances are stored separately; total contractual salary is calculated automatically.",
  "الراتب الأساسي": "Base salary",
  "بدل السكن": "Housing allowance",
  "بدل النقل": "Transport allowance",
  "بدلات أخرى": "Other allowances",
  "ساعات اليوم": "Hours per day",
  "ساعات الشهر": "Hours per month",
  "معامل الإضافي": "Overtime multiplier",
  "سياسة الحضور للراتب": "Payroll attendance policy",
  "يعتمد على البصمة": "Attendance required",
  "معفى من البصمة — راتب حسب الجدول": "Attendance exempt — salary based on schedule",
  "سبب الإعفاء": "Exemption reason",
  "مثال: موظف إداري / إدارة": "Example: administrative employee / management",
  "معفى من البصمة — الجدول يبقى معتمدًا": "Attendance exempt — schedule remains authoritative",
  "الإعفاء يلغي شرط البصمة والتأخير والخروج المبكر من الراتب فقط. جدول الدوام الرسمي يبقى مصدر أيام وساعات العمل والفترة والإجازات والغياب المسجل.": "The exemption removes attendance, lateness, and early-leave deductions from payroll only. The official schedule remains the source for working days, hours, periods, leave, and recorded absence.",
  "طريقة الخصم": "Deduction method",
  "حسب اليوم": "By day",
  "حسب الساعة": "By hour",
  "بدون خصم تلقائي": "No automatic deduction",
  "إجمالي الراتب التعاقدي": "Total contractual salary",
  "مكونات الراتب": "Salary components",
  "أساسي + سكن + نقل + بدلات أخرى": "Base + housing + transport + other allowances",
  "تفعيل احتساب الإضافي": "Enable overtime calculation",
  "يعتمد على إعدادات الراتب والشفتات الحالية.": "Uses the current payroll and shift settings.",
  "التأمينات الاجتماعية (GOSI)": "Social Insurance (GOSI)",
  "التصنيف والسياسة محفوظان مع تاريخ السريان؛ الحساب المالي نفسه ينفذه محرك GOSI المركزي عند إنشاء المسير.": "Classification and policy are stored with an effective date; the central GOSI engine performs the financial calculation when payroll is generated.",
  "تصنيف التأمينات": "Insurance classification",
  "سعودي — مشترك بالنظام القائم": "Saudi — existing system",
  "سعودي — النظام الجديد": "Saudi — new system",
  "خليجي — مد الحماية": "GCC national — protection extension",
  "غير سعودي": "Non-Saudi",
  "تاريخ سريان التصنيف": "Classification effective date",
  "سبب / ملاحظة التصنيف": "Classification reason / note",
  "مثال: حسب سجل الاشتراك أو مستند الموظفة": "Example: based on contribution record or staff document",
  "طريقة أجر الاشتراك": "Contribution wage method",
  "تلقائي من العناصر النظامية": "Automatic from statutory components",
  "أجر اشتراك معتمد يدويًا": "Approved manual contribution wage",
  "أجر الاشتراك المعتمد": "Approved contribution wage",
  "سبب الأجر المعتمد": "Reason for approved wage",
  "لماذا يختلف عن الاحتساب التلقائي؟": "Why does it differ from automatic calculation?",
  "دولة الموظفة الخليجية": "GCC nationality country",
  "مثال: KW / AE / BH / OM / QA": "Example: KW / AE / BH / OM / QA",
  "إعداد التأمينات غير مكتمل": "Insurance setup incomplete",
  "لن يمكن اعتماد مسير الراتب حتى يكتمل تصنيف التأمينات وتاريخ السريان وأي بيانات مطلوبة لأجر الاشتراك.": "Payroll cannot be approved until the insurance classification, effective date, and required contribution-wage data are complete.",
  "إعداد التأمينات مكتمل": "Insurance setup complete",
  "بيانات التصنيف وأجر الاشتراك جاهزة للحساب المركزي عند إنشاء مسير الرواتب.": "Classification and contribution-wage data are ready for central calculation when payroll is generated.",
  "أجر الاشتراك يُحسب تلقائيًا": "Contribution wage is calculated automatically",
  "لا تدخل نسبة Pension أو SANED يدويًا. محرك GOSI المركزي يحدد السياسة الفعالة حسب تصنيف الموظفة وتاريخ المسير، ويحتفظ بالـSnapshot المستخدم.": "Do not enter Pension or SANED percentages manually. The central GOSI engine selects the effective policy based on classification and payroll date and stores the calculation snapshot.",
  "Override موثق": "Documented override",
  "استخدم الأجر المعتمد يدويًا فقط عندما يكون لديك أجر اشتراك موثق مختلف، ويجب تسجيل السبب حتى يمكن فهم الحركة مستقبلًا.": "Use a manual approved contribution wage only when a different documented wage exists, and record the reason for auditability.",
  "الخليجي مستقل عن غير السعودي": "GCC classification is separate from Non-Saudi",
  "لن يحوله النظام إلى Non-Saudi تلقائيًا. يبقى اعتماد الراتب متوقفًا حتى تكتمل بيانات وسياسة مد الحماية.": "The system will not automatically convert GCC staff to Non-Saudi. Payroll approval remains blocked until protection-extension data and policy are complete.",
  "يرتبط هذا التبويب بوحدة تشغيل مستقلة داخل النظام.": "This tab is linked to an independent operational module.",
  "لا توجد ملاحظات إضافية": "No additional notes",
  "سيتم عرض البيانات عند ربط الوحدة المباشرة بهذا التبويب.": "Data will appear when the corresponding live module is connected to this tab.",

};

const EmployeeLanguageContext = createContext<EmployeeLanguageContextValue>({
  language: "ar",
  direction: "rtl",
  t: (arabic) => arabic,
  tr: (arabic) => arabic,
});

export function EmployeeLanguageProvider({
  language,
  children,
}: {
  language: DashboardLanguage;
  children: ReactNode;
}) {
  const value = useMemo<EmployeeLanguageContextValue>(
    () => ({
      language,
      direction: language === "en" ? "ltr" : "rtl",
      t: (arabic) => employeeText(language, arabic),
      tr: (arabic, english) => (language === "en" ? english : arabic),
    }),
    [language]
  );

  return (
    <EmployeeLanguageContext.Provider value={value}>
      {children}
    </EmployeeLanguageContext.Provider>
  );
}

export function useEmployeeLanguage() {
  return useContext(EmployeeLanguageContext);
}
